import { useState } from "react";
import { CheckCircle2, Moon } from "lucide-react";

export function NightlyReviewModal({ open, onClose, onSubmit, submitting }: { open: boolean; onClose: () => void; onSubmit: (reflection: string, energy: number, difficulty: number) => Promise<void>; submitting?: boolean }) {
  const [reflection, setReflection] = useState("");
  const [energy, setEnergy] = useState(3);
  const [difficulty, setDifficulty] = useState(3);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4 backdrop-blur-sm">
    <div className="relative w-full max-w-lg overflow-hidden rounded-[2rem] border border-cyan-300/10 bg-[#07101d] p-6 shadow-[0_40px_120px_-55px_rgba(34,211,238,.45)] sm:p-8">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-28 bg-[radial-gradient(ellipse_at_top,rgba(34,211,238,.09),transparent_65%)]" />
      <div className="relative"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-cyan-300/80"><Moon className="h-4 w-4" />Daily evidence</div><h2 className="mt-2 text-2xl font-black text-white">Close the loop.</h2><p className="mt-2 text-sm leading-6 text-slate-400">Record what actually happened. OUTSTAND uses the result to protect tomorrow’s highest-value work.</p></div><CheckCircle2 className="h-5 w-5 text-cyan-300" /></div>
      <label className="mt-7 block text-xs font-black uppercase tracking-[.15em] text-slate-500">What changed your performance today?</label><textarea value={reflection} onChange={(e) => setReflection(e.target.value)} rows={5} placeholder="What was easy, hard, surprising, or incomplete? Mention a weakness or useful result when you can." className="mt-3 w-full rounded-2xl border border-white/[0.08] bg-white/[0.025] px-4 py-3 text-sm text-white outline-none transition focus:border-cyan-300/35 focus:ring-4 focus:ring-cyan-300/[0.06]" />
      <div className="mt-5 grid grid-cols-2 gap-3"><label className="rounded-2xl border border-white/[0.07] bg-white/[0.012] p-4 text-xs font-bold text-slate-400">Energy<select value={energy} onChange={(e) => setEnergy(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-white/[0.06] bg-[#050d18] px-3 py-2 text-white outline-none focus:border-cyan-300/30"><option value={1}>1 · Low</option><option value={2}>2</option><option value={3}>3 · Normal</option><option value={4}>4</option><option value={5}>5 · High</option></select></label><label className="rounded-2xl border border-white/[0.07] bg-white/[0.012] p-4 text-xs font-bold text-slate-400">Difficulty<select value={difficulty} onChange={(e) => setDifficulty(Number(e.target.value))} className="mt-2 w-full rounded-xl border border-white/[0.06] bg-[#050d18] px-3 py-2 text-white outline-none focus:border-cyan-300/30"><option value={1}>1 · Easy</option><option value={2}>2</option><option value={3}>3 · Right level</option><option value={4}>4</option><option value={5}>5 · Hard</option></select></label></div>
      <div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-white/10 bg-white/[0.02] px-4 py-2.5 text-xs font-bold text-slate-400 transition hover:bg-white/[0.06] hover:text-white">Not now</button><button type="button" disabled={submitting} onClick={() => void onSubmit(reflection, energy, difficulty)} className="rounded-xl bg-gradient-to-r from-cyan-300 via-sky-300 to-violet-300 px-4 py-2.5 text-xs font-black text-slate-950 shadow-[0_10px_30px_-16px_rgba(34,211,238,.8)] transition hover:-translate-y-0.5 disabled:opacity-50">{submitting ? "Saving…" : "Save evidence"}</button></div></div>
    </div>
  </div>;
}
