import type { ChallengeTheme, OutstandChallenge, ThemeName, ChallengeId } from "./challenges.types";
type I = Omit<OutstandChallenge,"id"|"theme"|"audio"|"haptics"> & {id:string;theme:ThemeName};
const id=(v:string)=>v as ChallengeId;
const m=(t:Record<ThemeName,ChallengeTheme>,d:I):OutstandChallenge=>({...d,id:id(d.id),theme:t[d.theme],audio:{onComplete:"success_chime"},haptics:{onComplete:"success"}});
export const createChallengeBatch02=(t:Record<ThemeName,ChallengeTheme>):OutstandChallenge[]=>[
 m(t,{id:"prod-01",title:"Priority Three",description:"Choose the three outcomes that matter most today and finish the first one before adding more.",emoji:"3️⃣",category:"Productivity",difficulty:"Medium",rarity:"Uncommon",durationMinutes:15,timeWindow:"Morning",actionType:"Reflection",xpReward:70,coinsReward:12,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Clarity removes noise.",cognitiveLoad:3},theme:"Ocean"}),
 m(t,{id:"prod-02",title:"Five-Minute Launch",description:"Spend five minutes preparing the exact materials needed for your next task, then begin.",emoji:"🚦",category:"Productivity",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Anytime",actionType:"Timer",xpReward:40,coinsReward:7,psychologicalProfile:{dopamineYield:"Low",flavorText:"Make starting automatic.",cognitiveLoad:1},theme:"Ice"}),
 m(t,{id:"prod-03",title:"Inbox Zero Hour",description:"Clear one small pile of pending school or personal tasks without opening entertainment apps.",emoji:"📥",category:"Productivity",difficulty:"Medium",rarity:"Rare",durationMinutes:30,timeWindow:"Anytime",actionType:"Timer",xpReward:130,coinsReward:25,psychologicalProfile:{dopamineYield:"High",flavorText:"Reduce open loops.",cognitiveLoad:3},theme:"Neon"}),
 m(t,{id:"prod-04",title:"Plan Tomorrow",description:"Write tomorrow's first task, study target, and one thing to avoid.",emoji:"🗓️",category:"Productivity",difficulty:"Easy",rarity:"Uncommon",durationMinutes:10,timeWindow:"Evening",actionType:"Reflection",xpReward:55,coinsReward:10,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Tomorrow starts tonight.",cognitiveLoad:2},theme:"Sunset"}),
 m(t,{id:"prod-05",title:"Finish the Smallest",description:"Complete the smallest useful task on your list before touching anything optional.",emoji:"✅",category:"Productivity",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:45,coinsReward:8,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Momentum starts small.",cognitiveLoad:1},theme:"Forest"}),
 m(t,{id:"discipline-01",title:"No Snooze Start",description:"Get out of bed when your alarm goes off and begin your planned morning action.",emoji:"⏰",category:"Discipline",difficulty:"Medium",rarity:"Rare",durationMinutes:10,timeWindow:"Morning",actionType:"Toggle",xpReward:75,coinsReward:15,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Keep promises to yourself.",cognitiveLoad:2},theme:"Volcano"}),
 m(t,{id:"discipline-02",title:"One Rule",description:"Pick one distraction rule for this session and follow it without negotiation.",emoji:"📜",category:"Discipline",difficulty:"Medium",rarity:"Uncommon",durationMinutes:20,timeWindow:"Anytime",actionType:"Timer",xpReward:85,coinsReward:16,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Rules reduce decisions.",cognitiveLoad:2},theme:"Royal"}),
 m(t,{id:"discipline-03",title:"Close the Loop",description:"Finish one task completely: no half-finished tabs, drafts, or loose notes.",emoji:"🔒",category:"Discipline",difficulty:"Hard",rarity:"Epic",durationMinutes:40,timeWindow:"Anytime",actionType:"Timer",xpReward:200,coinsReward:45,psychologicalProfile:{dopamineYield:"High",flavorText:"Complete before consuming more.",cognitiveLoad:4},theme:"Void"}),
 m(t,{id:"discipline-04",title:"Return on Time",description:"When a break ends, return to your planned task immediately.",emoji:"↩️",category:"Discipline",difficulty:"Medium",rarity:"Uncommon",durationMinutes:15,timeWindow:"Anytime",actionType:"Toggle",xpReward:60,coinsReward:10,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Breaks should end too.",cognitiveLoad:2},theme:"Ice"}),
 m(t,{id:"discipline-05",title:"Promise Kept",description:"Complete one commitment you made to yourself earlier today.",emoji:"🤝",category:"Discipline",difficulty:"Hard",rarity:"Epic",durationMinutes:30,timeWindow:"Anytime",actionType:"Timer",xpReward:180,coinsReward:40,psychologicalProfile:{dopamineYield:"High",flavorText:"Self-trust is built in private.",cognitiveLoad:4},theme:"Royal"}),
 m(t,{id:"fitness-04",title:"Walk Reset",description:"Take a brisk but comfortable walk and return ready for your next task.",emoji:"🚶‍♂️",category:"Fitness",difficulty:"Easy",rarity:"Common",durationMinutes:15,timeWindow:"Anytime",actionType:"Timer",xpReward:60,coinsReward:10,psychologicalProfile:{dopamineYield:"Low",flavorText:"Move to reset.",cognitiveLoad:1},theme:"Forest"}),
 m(t,{id:"fitness-05",title:"Mobility Minute",description:"Spend ten minutes on gentle mobility for the areas that feel stiff from sitting.",emoji:"🌀",category:"Fitness",difficulty:"Easy",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Timer",xpReward:50,coinsReward:9,psychologicalProfile:{dopamineYield:"Low",flavorText:"Small movement adds up.",cognitiveLoad:1},theme:"Ice"}),
 m(t,{id:"fitness-06",title:"Fresh-Air Break",description:"Step outside for a short fresh-air break before your next study block.",emoji:"🌤️",category:"Fitness",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:40,coinsReward:7,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Change the environment.",cognitiveLoad:1},theme:"Ocean"}),
 m(t,{id:"fitness-07",title:"Hydration Check",description:"Pause your work, get a drink, and return to the task without opening entertainment.",emoji:"💧",category:"Fitness",difficulty:"Easy",rarity:"Common",durationMinutes:5,timeWindow:"Anytime",actionType:"Toggle",xpReward:25,coinsReward:5,psychologicalProfile:{dopamineYield:"Low",flavorText:"Support the basics.",cognitiveLoad:1},theme:"Sky" as ThemeName}),
 m(t,{id:"fitness-08",title:"Desk-to-Door",description:"Leave your desk for a short movement break, then return and restart your focus block.",emoji:"🚪",category:"Fitness",difficulty:"Medium",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Timer",xpReward:50,coinsReward:9,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Interrupt sitting, not momentum.",cognitiveLoad:1},theme:"Forest"}),
 m(t,{id:"mindset-06",title:"Name the Blocker",description:"Write the single reason you are stuck, then choose one action that makes it smaller.",emoji:"🧭",category:"Mindset",difficulty:"Medium",rarity:"Rare",durationMinutes:10,timeWindow:"Anytime",actionType:"Reflection",xpReward:70,coinsReward:14,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Specific problems invite specific actions.",cognitiveLoad:3},theme:"Galaxy"}),
 m(t,{id:"mindset-07",title:"Progress Snapshot",description:"Record one measurable improvement from this week instead of judging the whole week.",emoji:"📸",category:"Mindset",difficulty:"Easy",rarity:"Uncommon",durationMinutes:10,timeWindow:"Evening",actionType:"Reflection",xpReward:55,coinsReward:10,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Progress deserves evidence.",cognitiveLoad:2},theme:"Neon"}),
 m(t,{id:"mindset-08",title:"Boring Is Powerful",description:"Do a simple useful task for 20 minutes without needing novelty or excitement.",emoji:"🪨",category:"Mindset",difficulty:"Medium",rarity:"Rare",durationMinutes:20,timeWindow:"Anytime",actionType:"Timer",xpReward:90,coinsReward:18,psychologicalProfile:{dopamineYield:"Low",flavorText:"Consistency survives boredom.",cognitiveLoad:3},theme:"Void"}),
 m(t,{id:"mindset-09",title:"Second Attempt",description:"Retry a problem or task that went poorly once, using what you learned from the first attempt.",emoji:"🔁",category:"Mindset",difficulty:"Hard",rarity:"Epic",durationMinutes:25,timeWindow:"Anytime",actionType:"Timer",xpReward:140,coinsReward:30,psychologicalProfile:{dopamineYield:"High",flavorText:"Iteration beats avoidance.",cognitiveLoad:4},theme:"Volcano"}),
 m(t,{id:"mindset-10",title:"Quiet Confidence",description:"Write one thing you can control today and spend fifteen minutes acting on it.",emoji:"🕯️",category:"Mindset",difficulty:"Medium",rarity:"Rare",durationMinutes:15,timeWindow:"Anytime",actionType:"Reflection",xpReward:80,coinsReward:16,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Control the controllable.",cognitiveLoad:3},theme:"Sunset"}),
 m(t,{id:"social-02",title:"Thank Someone",description:"Give one sincere thank-you to someone who helped you recently.",emoji:"🙏",category:"Social",difficulty:"Easy",rarity:"Common",durationMinutes:5,timeWindow:"Anytime",actionType:"Toggle",xpReward:35,coinsReward:6,psychologicalProfile:{dopamineYield:"High",flavorText:"Appreciation strengthens connection.",cognitiveLoad:1},theme:"Forest"}),
 m(t,{id:"social-03",title:"Ask Clearly",description:"Ask one clear question instead of guessing what someone else expects.",emoji:"❓",category:"Social",difficulty:"Medium",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:55,coinsReward:10,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Clarity is a social superpower.",cognitiveLoad:2},theme:"Ocean"}),
 m(t,{id:"social-04",title:"Listen First",description:"Have one conversation where your goal is to listen carefully before replying.",emoji:"👂",category:"Social",difficulty:"Medium",rarity:"Rare",durationMinutes:15,timeWindow:"Anytime",actionType:"Toggle",xpReward:80,coinsReward:16,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Attention is a gift.",cognitiveLoad:3},theme:"Galaxy"}),
 m(t,{id:"social-05",title:"Help Without Prompt",description:"Offer a small useful act of help to someone around you.",emoji:"🤲",category:"Social",difficulty:"Medium",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:60,coinsReward:12,psychologicalProfile:{dopamineYield:"High",flavorText:"Contribution creates confidence.",cognitiveLoad:2},theme:"Royal"}),
];
