import { OutstandChallenge, ChallengeTheme } from "./challenges.types";

/**
 * ---------------------------------------------------------------------------
 * THEME DICTIONARY (DRY Architecture)
 * ---------------------------------------------------------------------------
 * We define the design tokens once. This keeps the data file clean and
 * makes global UI changes instantly affect all cards.
 */
export const THEMES: Record<string, ChallengeTheme> = {
  Void: {
    name: "Void",
    bgGradient: "from-black via-zinc-950 to-purple-950/20",
    borderGlow: "hover:shadow-[0_0_40px_rgba(168,85,247,0.3)]",
    iconContainer: "bg-purple-500/10 border-purple-500/30",
    badgeColor: "text-purple-300",
    particleColors: ["#a855f7", "#000000", "#ffffff"],
  },
  Volcano: {
    name: "Volcano",
    bgGradient: "from-black via-red-950/20 to-orange-900/10",
    borderGlow: "hover:shadow-[0_0_40px_rgba(239,68,68,0.3)]",
    iconContainer: "bg-red-500/10 border-red-500/30",
    badgeColor: "text-red-400",
    particleColors: ["#ef4444", "#f97316", "#fde047"],
  },
  Royal: {
    name: "Royal",
    bgGradient: "from-black via-amber-900/20 to-yellow-900/10",
    borderGlow: "hover:shadow-[0_0_40px_rgba(251,191,36,0.3)]",
    iconContainer: "bg-amber-500/10 border-amber-500/30",
    badgeColor: "text-amber-400",
    particleColors: ["#fbbf24", "#f59e0b", "#ffffff"],
  },
  Ice: {
    name: "Ice",
    bgGradient: "from-black via-cyan-950/20 to-blue-900/10",
    borderGlow: "hover:shadow-[0_0_40px_rgba(6,182,212,0.3)]",
    iconContainer: "bg-cyan-500/10 border-cyan-500/30",
    badgeColor: "text-cyan-300",
    particleColors: ["#06b6d4", "#38bdf8", "#ffffff"],
  },
  Galaxy: {
    name: "Galaxy",
    bgGradient: "from-black via-indigo-950/30 to-fuchsia-900/10",
    borderGlow: "hover:shadow-[0_0_40px_rgba(99,102,241,0.3)]",
    iconContainer: "bg-indigo-500/10 border-indigo-500/30",
    badgeColor: "text-indigo-300",
    particleColors: ["#6366f1", "#d946ef", "#e0e7ff"],
  },
  Neon: {
    name: "Neon",
    bgGradient: "from-black via-pink-950/20 to-rose-900/10",
    borderGlow: "hover:shadow-[0_0_40px_rgba(244,63,94,0.3)]",
    iconContainer: "bg-rose-500/10 border-rose-500/30",
    badgeColor: "text-rose-400",
    particleColors: ["#f43f5e", "#fb7185", "#ffe4e6"],
  },
  Forest: {
    name: "Forest",
    bgGradient: "from-black via-emerald-950/20 to-green-900/10",
    borderGlow: "hover:shadow-[0_0_40px_rgba(16,185,129,0.3)]",
    iconContainer: "bg-emerald-500/10 border-emerald-500/30",
    badgeColor: "text-emerald-400",
    particleColors: ["#10b981", "#34d399", "#d1fae5"],
  },
  Ocean: {
    name: "Ocean",
    bgGradient: "from-black via-blue-950/20 to-sky-900/10",
    borderGlow: "hover:shadow-[0_0_40px_rgba(14,165,233,0.3)]",
    iconContainer: "bg-blue-500/10 border-blue-500/30",
    badgeColor: "text-blue-400",
    particleColors: ["#0ea5e9", "#7dd3fc", "#e0f2fe"],
  },
  Sunset: {
    name: "Sunset",
    bgGradient: "from-black via-orange-950/20 to-red-900/10",
    borderGlow: "hover:shadow-[0_0_40px_rgba(249,115,22,0.3)]",
    iconContainer: "bg-orange-500/10 border-orange-500/30",
    badgeColor: "text-orange-400",
    particleColors: ["#f97316", "#fb923c", "#ffedd5"],
  }
};

/**
 * ---------------------------------------------------------------------------
 * CHALLENGE VAULT: PART 1 (Tiers: Divine, Mythic, Legendary, Epic, Rare)
 * ---------------------------------------------------------------------------
 */
export const CHALLENGES: OutstandChallenge[] = [
  
  // --- DIVINE & MYTHIC (The Ultimate Tests of Willpower) ---

  {
    id: "div_ghost_protocol_01",
    title: "The Ghost Protocol",
    description: "Delete every social media app from your phone. Turn off all non-human notifications. You do not exist online for the next 24 hours.",
    emoji: "👻",
    durationMinutes: 1440,
    category: "Phone Detox",
    difficulty: "Master",
    rarity: "Divine",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 5000,
    coinsReward: 1000,
    dopamineYield: "Reset",
    flavorText: "To find yourself, you must first disappear.",
    theme: THEMES.Void,
    audio: { onStart: "digital_boot", onComplete: "ethereal_ping" },
    requirements: { minLevel: 10 }
  },
  {
    id: "div_iron_mind_01",
    title: "The Crucible",
    description: "Write down the absolute worst truth about your current life—the thing you are hiding from. Then, write the exact, brutal 3-step plan to fix it.",
    emoji: "⚔️",
    durationMinutes: 30,
    category: "Mindset",
    difficulty: "Master",
    rarity: "Divine",
    timeWindow: "Evening",
    actionType: "Reflection",
    xpReward: 4500,
    coinsReward: 800,
    dopamineYield: "Low",
    flavorText: "Pain is just weakness leaving the mind.",
    theme: THEMES.Royal,
    audio: { onComplete: "heavy_bass_drop" },
    requirements: { minStreak: 7 }
  },
  {
    id: "myth_spartan_300",
    title: "The Spartan 300",
    description: "Complete 100 Push-ups, 100 Squats, and 100 Sit-ups before the timer runs out. No excuses. Scale variations if necessary, but do not stop.",
    emoji: "🛡️",
    durationMinutes: 45,
    category: "Fitness",
    difficulty: "Extreme",
    rarity: "Mythic",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 3000,
    coinsReward: 500,
    dopamineYield: "High",
    flavorText: "Your body is capable of 100x what your mind allows.",
    theme: THEMES.Volcano,
    audio: { onStart: "whoosh", onComplete: "level_up" }
  },
  {
    id: "myth_deep_work_01",
    title: "Monk Mode Sprint",
    description: "90 uninterrupted minutes. One screen. One task. Phone in a different room. If you break focus for even one second, you fail.",
    emoji: "🧘‍♂️",
    durationMinutes: 90,
    category: "Focus",
    difficulty: "Extreme",
    rarity: "Mythic",
    timeWindow: "Morning",
    actionType: "Timer",
    xpReward: 3000,
    coinsReward: 500,
    dopamineYield: "Medium",
    flavorText: "Distraction is the death of greatness.",
    theme: THEMES.Galaxy,
    audio: { onStart: "chime", onComplete: "ethereal_ping" }
  },
  {
    id: "myth_financial_audit",
    title: "The Reckoning",
    description: "Log into all your bank accounts. Calculate exactly how much money you wasted on useless things in the last 30 days. Cancel two subscriptions.",
    emoji: "⚖️",
    durationMinutes: 30,
    category: "Discipline",
    difficulty: "Extreme",
    rarity: "Mythic",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 2500,
    coinsReward: 600,
    dopamineYield: "Reset",
    flavorText: "Numbers do not lie. Only people do.",
    theme: THEMES.Royal,
    audio: { onComplete: "heavy_bass_drop" }
  },

  // --- LEGENDARY (Highly Demanding, Huge Impact) ---

  {
    id: "leg_cold_forge",
    title: "The Cold Forge",
    description: "Turn the shower to the coldest possible setting. Stand under it for 3 unbroken minutes. Control your breathing. Do not flinch.",
    emoji: "🧊",
    durationMinutes: 3,
    category: "Mindset",
    difficulty: "Hard",
    rarity: "Legendary",
    timeWindow: "Morning",
    actionType: "Timer",
    xpReward: 1500,
    coinsReward: 250,
    dopamineYield: "High",
    flavorText: "Comfort is a slow poison.",
    theme: THEMES.Ice,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "leg_dopamine_starve",
    title: "Absolute Zero",
    description: "Sit in a room with zero electronics, zero books, and zero music. Do nothing but stare at the wall. Let your brain reset its baseline.",
    emoji: "🕳️",
    durationMinutes: 30,
    category: "Discipline",
    difficulty: "Hard",
    rarity: "Legendary",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 1800,
    coinsReward: 300,
    dopamineYield: "Reset",
    flavorText: "Boredom is the birthplace of genius.",
    theme: THEMES.Void,
    audio: { onStart: "chime", onComplete: "ethereal_ping" }
  },
  {
    id: "leg_burn_boats",
    title: "Burn the Boats",
    description: "Send a message to a mentor, friend, or rival committing to a massive goal by a specific date. If you fail, you owe them $100.",
    emoji: "🔥",
    durationMinutes: 10,
    category: "Social",
    difficulty: "Hard",
    rarity: "Legendary",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 1500,
    coinsReward: 250,
    dopamineYield: "High",
    flavorText: "Commitment isn't real until there are consequences.",
    theme: THEMES.Volcano,
    audio: { onComplete: "level_up" }
  },
  {
    id: "leg_knowledge_devour",
    title: "The Marathon Mind",
    description: "Read a dense, highly educational book or paper. No skimming. No music. Absorb every single word until the timer sounds.",
    emoji: "🧠",
    durationMinutes: 60,
    category: "Knowledge",
    difficulty: "Hard",
    rarity: "Legendary",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 1400,
    coinsReward: 200,
    dopamineYield: "Medium",
    flavorText: "Read what others won't, to know what others don't.",
    theme: THEMES.Galaxy,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "leg_core_collapse",
    title: "Core Collapse",
    description: "Hold a plank until absolute muscular failure. Rest for 30 seconds. Repeat 3 times. Write down your total time.",
    emoji: "🏗️",
    durationMinutes: 15,
    category: "Fitness",
    difficulty: "Hard",
    rarity: "Legendary",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 1600,
    coinsReward: 250,
    dopamineYield: "High",
    flavorText: "Gravity is a harsh teacher. Learn from it.",
    theme: THEMES.Volcano,
    audio: { onComplete: "heavy_bass_drop" }
  },

  // --- EPIC (Tough but highly achievable day-to-day drivers) ---

  {
    id: "epic_inbox_nuke",
    title: "Nuclear Inbox",
    description: "Delete, archive, or reply to every single email in your inbox. Do not stop until it reads: '0 Unread'.",
    emoji: "☢️",
    durationMinutes: 25,
    category: "Productivity",
    difficulty: "Medium",
    rarity: "Epic",
    timeWindow: "Afternoon",
    actionType: "Timer",
    xpReward: 800,
    coinsReward: 100,
    dopamineYield: "High",
    flavorText: "Cluttered inbox, cluttered mind.",
    theme: THEMES.Neon,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "epic_grayscale",
    title: "Grayscale Vision",
    description: "Go into your phone's accessibility settings and turn the color filters to Grayscale. Leave it like this until tomorrow.",
    emoji: "🔲",
    durationMinutes: 5,
    category: "Phone Detox",
    difficulty: "Medium",
    rarity: "Epic",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 750,
    coinsReward: 100,
    dopamineYield: "Reset",
    flavorText: "Take the color away, and the addiction fades.",
    theme: THEMES.Ice,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "epic_future_self",
    title: "Temporal Shift",
    description: "Open a blank document. Write a letter from yourself 5 years in the future, explaining exactly how you achieved your dream.",
    emoji: "📜",
    durationMinutes: 20,
    category: "Mindset",
    difficulty: "Medium",
    rarity: "Epic",
    timeWindow: "Evening",
    actionType: "Reflection",
    xpReward: 900,
    coinsReward: 120,
    dopamineYield: "Medium",
    flavorText: "Design your future, or someone else will.",
    theme: THEMES.Royal,
    audio: { onStart: "chime", onComplete: "level_up" }
  },
  {
    id: "epic_chaos_control",
    title: "Chaos Control",
    description: "Pick the messiest room, desk, or closet you own. Clean it with absolute aggression and speed. Leave no trace of clutter.",
    emoji: "🌪️",
    durationMinutes: 20,
    category: "Discipline",
    difficulty: "Medium",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 850,
    coinsReward: 110,
    dopamineYield: "High",
    flavorText: "Order your environment to order your mind.",
    theme: THEMES.Forest,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "epic_bold_ask",
    title: "The Bold Ask",
    description: "Find someone who is 3 steps ahead of you in your career. Send them a concise, respectful DM asking for one piece of advice.",
    emoji: "🚀",
    durationMinutes: 10,
    category: "Social",
    difficulty: "Hard",
    rarity: "Epic",
    timeWindow: "Afternoon",
    actionType: "Toggle",
    xpReward: 1000,
    coinsReward: 150,
    dopamineYield: "Medium",
    flavorText: "The universe rewards the brave.",
    theme: THEMES.Ocean,
    audio: { onComplete: "level_up" }
  },
  {
    id: "epic_burpee_burn",
    title: "Oxygen Debt",
    description: "Complete 50 burpees as fast as humanly possible. Focus on form, but do not stop for more than 5 seconds at a time.",
    emoji: "🫁",
    durationMinutes: 15,
    category: "Fitness",
    difficulty: "Hard",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 950,
    coinsReward: 120,
    dopamineYield: "High",
    flavorText: "Lungs burning. Heart pounding. You are alive.",
    theme: THEMES.Volcano,
    audio: { onComplete: "heavy_bass_drop" }
  },
  {
    id: "epic_value_create",
    title: "The Creator Swap",
    description: "Stop consuming. Spend the next 30 minutes creating something—a blog post, a sketch, a piece of code, or a business idea.",
    emoji: "🛠️",
    durationMinutes: 30,
    category: "Productivity",
    difficulty: "Medium",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 800,
    coinsReward: 100,
    dopamineYield: "Medium",
    flavorText: "Consumers pay. Creators get paid.",
    theme: THEMES.Neon,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "epic_zero_spend",
    title: "Wallet Lockdown",
    description: "Remove your credit cards from your digital wallet. Commit to spending exactly $0 on non-essentials for the next 48 hours.",
    emoji: "🔒",
    durationMinutes: 5,
    category: "Discipline",
    difficulty: "Medium",
    rarity: "Epic",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 850,
    coinsReward: 150,
    dopamineYield: "Low",
    flavorText: "Wealth is what you don't spend.",
    theme: THEMES.Forest,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "epic_fear_setting",
    title: "Fear Setting",
    description: "Write down the biggest risk you are afraid to take. Next to it, write exactly how you would recover if the absolute worst happened.",
    emoji: "⛈️",
    durationMinutes: 20,
    category: "Mindset",
    difficulty: "Medium",
    rarity: "Epic",
    timeWindow: "Evening",
    actionType: "Reflection",
    xpReward: 900,
    coinsReward: 100,
    dopamineYield: "Reset",
    flavorText: "We suffer more in imagination than in reality.",
    theme: THEMES.Sunset,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "epic_micro_skill",
    title: "The 20-Minute Master",
    description: "Pick a software shortcut, a typing technique, or a physical trick. Practice it obsessively for 20 minutes until it becomes muscle memory.",
    emoji: "⚙️",
    durationMinutes: 20,
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 750,
    coinsReward: 90,
    dopamineYield: "High",
    flavorText: "Micro-skills compound into macro-success.",
    theme: THEMES.Galaxy,
    audio: { onComplete: "level_up" }
  },

  // --- RARE (Quick hits, great for maintaining momentum) ---

  {
    id: "rare_brain_dump",
    title: "Cognitive Offload",
    description: "Grab a pen and paper. Write down every single task, anxiety, and idea floating in your head. Empty the RAM of your brain.",
    emoji: "🧠",
    durationMinutes: 10,
    category: "Focus",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Morning",
    actionType: "Reflection",
    xpReward: 400,
    coinsReward: 50,
    dopamineYield: "Medium",
    flavorText: "Your mind is for having ideas, not holding them.",
    theme: THEMES.Ocean,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "rare_hydrate_spike",
    title: "The Flush",
    description: "Go to the kitchen. Drink 2 large glasses (approx 1 liter) of water immediately. Rehydrate your brain cells.",
    emoji: "🌊",
    durationMinutes: 2,
    category: "Fitness",
    difficulty: "Easy",
    rarity: "Rare",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 300,
    coinsReward: 30,
    dopamineYield: "Low",
    flavorText: "Fatigue is often just dehydration in disguise.",
    theme: THEMES.Ocean,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "rare_unfollow_purge",
    title: "Algorithm Edit",
    description: "Open your most-used social app. Unfollow 10 accounts that make you feel jealous, angry, or unproductive. Curate your reality.",
    emoji: "✂️",
    durationMinutes: 5,
    category: "Phone Detox",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 450,
    coinsReward: 60,
    dopamineYield: "Medium",
    flavorText: "You are the average of the content you consume.",
    theme: THEMES.Ice,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "rare_mirror_talk",
    title: "The Vow",
    description: "Look yourself directly in the eyes in a mirror. Out loud, state your main goal and promise yourself you will not quit today.",
    emoji: "🪞",
    durationMinutes: 3,
    category: "Mindset",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 400,
    coinsReward: 50,
    dopamineYield: "High",
    flavorText: "The only person you need to convince is in the glass.",
    theme: THEMES.Sunset,
    audio: { onComplete: "level_up" }
  },
  {
    id: "rare_posture_fix",
    title: "Spine Alignment",
    description: "Stand against a wall. Heels, butt, shoulders, and head touching. Raise your arms up and down slowly for 3 minutes.",
    emoji: "🧍‍♂️",
    durationMinutes: 3,
    category: "Fitness",
    difficulty: "Easy",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 350,
    coinsReward: 40,
    dopamineYield: "Medium",
    flavorText: "Carry yourself like someone who has already won.",
    theme: THEMES.Forest,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "rare_pomodoro_one",
    title: "First Strike",
    description: "Start a 25-minute Pomodoro timer. Work on your ugliest, most annoying task. Do not stop until the timer rings.",
    emoji: "🍅",
    durationMinutes: 25,
    category: "Productivity",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Morning",
    actionType: "Timer",
    xpReward: 500,
    coinsReward: 75,
    dopamineYield: "High",
    flavorText: "Action precedes motivation, not the other way around.",
    theme: THEMES.Neon,
    audio: { onStart: "digital_boot", onComplete: "level_up" }
  },
  {
    id: "rare_apology_tour",
    title: "Clear the Air",
    description: "Text or call someone you reacted poorly to recently. Take 100% of the blame. Offer a genuine apology with no excuses.",
    emoji: "🕊️",
    durationMinutes: 10,
    category: "Social",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Afternoon",
    actionType: "Toggle",
    xpReward: 600,
    coinsReward: 80,
    dopamineYield: "Reset",
    flavorText: "Ego is heavy. Drop it and walk lighter.",
    theme: THEMES.Royal,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "rare_shadow_box",
    title: "Kinetic Flow",
    description: "Stand up and shadow box or dance aggressively for 3 minutes. Move your feet, keep your hands up, and spike your heart rate.",
    emoji: "🥊",
    durationMinutes: 3,
    category: "Fitness",
    difficulty: "Easy",
    rarity: "Rare",
    timeWindow: "Afternoon",
    actionType: "Timer",
    xpReward: 350,
    coinsReward: 40,
    dopamineYield: "High",
    flavorText: "Stagnant body, stagnant mind.",
    theme: THEMES.Volcano,
    audio: { onStart: "whoosh", onComplete: "success_chime" }
    },
  {
    id: "rare_concept_map",
    title: "The Feynman Technique",
    description: "Take a blank sheet of paper. Explain a complex concept you are trying to learn as if you were teaching it to a 5-year-old.",
    emoji: "📝",
    durationMinutes: 15,
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 450,
    coinsReward: 60,
    dopamineYield: "Medium",
    flavorText: "If you can't explain it simply, you don't understand it.",
    theme: THEMES.Galaxy,
    audio: { onComplete: "level_up" }
  },
  {
    id: "rare_airplane_mode",
    title: "Signal Blackout",
    description: "Switch your phone to Airplane Mode. Leave it there for exactly 60 minutes while you read, write, or plan.",
    emoji: "✈️",
    durationMinutes: 60,
    category: "Phone Detox",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 500,
    coinsReward: 70,
    dopamineYield: "Reset",
    flavorText: "Peace is found when the signal is lost.",
    theme: THEMES.Ice,
    audio: { onStart: "chime", onComplete: "ethereal_ping" }
  },
  {
    id: "rare_gratitude_spike",
    title: "Three Pillars",
    description: "Write down 3 highly specific things you are grateful for today. Not 'my family'—write 'the way the coffee tasted this morning'.",
    emoji: "🙏",
    durationMinutes: 5,
    category: "Mindset",
    difficulty: "Easy",
    rarity: "Rare",
    timeWindow: "Evening",
    actionType: "Reflection",
    xpReward: 400,
    coinsReward: 50,
    dopamineYield: "Medium",
    flavorText: "Appreciation is the antidote to anxiety.",
    theme: THEMES.Sunset,
    audio: { onComplete: "success_chime" }
  },
];
