import type { ChallengeTheme, OutstandChallenge, ThemeName, ChallengeId } from "./challenges.types";
type I=Omit<OutstandChallenge,"id"|"theme"|"audio"|"haptics">&{id:string;theme:ThemeName};
const id=(v:string)=>v as ChallengeId;
const m=(t:Record<ThemeName,ChallengeTheme>,d:I):OutstandChallenge=>({...d,id:id(d.id),theme:t[d.theme],audio:{onComplete:"success_chime"},haptics:{onComplete:"success"}});
export const createChallengeBatch04=(t:Record<ThemeName,ChallengeTheme>):OutstandChallenge[]=>[
 m(t,{id:"social-06",title:"Speak Up",description:"Share one useful thought or question clearly instead of keeping it to yourself.",emoji:"🎙️",category:"Social",difficulty:"Medium",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:55,coinsReward:10,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Clear expression builds confidence.",cognitiveLoad:2},theme:"Neon"}),
 m(t,{id:"social-07",title:"Real Compliment",description:"Give someone a specific, sincere compliment about an action or quality you appreciate.",emoji:"🌟",category:"Social",difficulty:"Easy",rarity:"Common",durationMinutes:5,timeWindow:"Anytime",actionType:"Toggle",xpReward:35,coinsReward:6,psychologicalProfile:{dopamineYield:"High",flavorText:"Notice the good.",cognitiveLoad:1},theme:"Royal"}),
 m(t,{id:"social-08",title:"Ask for Feedback",description:"Ask someone you trust for one practical suggestion on something you are learning.",emoji:"🗣️",category:"Social",difficulty:"Medium",rarity:"Rare",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:75,coinsReward:15,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Feedback accelerates learning.",cognitiveLoad:3},theme:"Ocean"}),
 m(t,{id:"social-09",title:"Patient Reply",description:"In one conversation, pause and think before replying instead of reacting instantly.",emoji:"🧘",category:"Social",difficulty:"Medium",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:60,coinsReward:12,psychologicalProfile:{dopamineYield:"Low",flavorText:"Calm creates better conversations.",cognitiveLoad:3},theme:"Ice"}),
 m(t,{id:"social-10",title:"Reconnect",description:"Send a thoughtful check-in to someone you genuinely care about.",emoji:"💬",category:"Social",difficulty:"Easy",rarity:"Uncommon",durationMinutes:5,timeWindow:"Anytime",actionType:"Toggle",xpReward:45,coinsReward:8,psychologicalProfile:{dopamineYield:"High",flavorText:"Connection needs small actions.",cognitiveLoad:1},theme:"Sunset"}),
 m(t,{id:"fitness-09",title:"Stretch Break",description:"Take a gentle stretch break after a long sitting period, then return to your work.",emoji:"🤸",category:"Fitness",difficulty:"Easy",rarity:"Common",durationMinutes:8,timeWindow:"Anytime",actionType:"Timer",xpReward:35,coinsReward:6,psychologicalProfile:{dopamineYield:"Low",flavorText:"Reset the body, reset the session.",cognitiveLoad:1},theme:"Ice"}),
 m(t,{id:"fitness-10",title:"Sunlight Reset",description:"Spend a short comfortable break outside or near natural light before returning to work.",emoji:"☀️",category:"Fitness",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Morning",actionType:"Toggle",xpReward:40,coinsReward:7,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Change the scene.",cognitiveLoad:1},theme:"Ocean"}),
 m(t,{id:"fitness-11",title:"Walk the Block",description:"Take a short walk at a comfortable pace and come back ready for your next task.",emoji:"👟",category:"Fitness",difficulty:"Easy",rarity:"Uncommon",durationMinutes:15,timeWindow:"Anytime",actionType:"Timer",xpReward:65,coinsReward:12,psychologicalProfile:{dopamineYield:"Low",flavorText:"Movement restores momentum.",cognitiveLoad:1},theme:"Forest"}),
 m(t,{id:"fitness-12",title:"Balance Break",description:"Step away from your desk and spend a few minutes moving in a way that feels comfortable and controlled.",emoji:"⚖️",category:"Fitness",difficulty:"Medium",rarity:"Rare",durationMinutes:10,timeWindow:"Anytime",actionType:"Timer",xpReward:55,coinsReward:10,psychologicalProfile:{dopamineYield:"Low",flavorText:"Control beats intensity.",cognitiveLoad:1},theme:"Galaxy"}),
 m(t,{id:"fitness-13",title:"Movement Habit",description:"Complete a short movement session you can realistically repeat tomorrow.",emoji:"🔁",category:"Fitness",difficulty:"Medium",rarity:"Rare",durationMinutes:20,timeWindow:"Anytime",actionType:"Timer",xpReward:100,coinsReward:20,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Repeatable wins compound.",cognitiveLoad:2},theme:"Forest"}),
 m(t,{id:"mindset-11",title:"Tomorrow Me",description:"Choose one action today that will make tomorrow easier.",emoji:"🌱",category:"Mindset",difficulty:"Easy",rarity:"Uncommon",durationMinutes:10,timeWindow:"Evening",actionType:"Reflection",xpReward:55,coinsReward:10,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Future progress starts now.",cognitiveLoad:2},theme:"Forest"}),
 m(t,{id:"mindset-12",title:"Control Circle",description:"Separate what you can control from what you cannot, then act on one controllable item.",emoji:"⭕",category:"Mindset",difficulty:"Medium",rarity:"Rare",durationMinutes:15,timeWindow:"Anytime",actionType:"Reflection",xpReward:85,coinsReward:16,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Attention belongs on action.",cognitiveLoad:3},theme:"Void"}),
 m(t,{id:"mindset-13",title:"Make It Smaller",description:"Take an intimidating task and reduce it to the smallest useful next step.",emoji:"🧱",category:"Mindset",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Anytime",actionType:"Reflection",xpReward:45,coinsReward:8,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Small enough to start.",cognitiveLoad:2},theme:"Ice"}),
 m(t,{id:"mindset-14",title:"Celebrate Completion",description:"Pause after finishing something meaningful and acknowledge the progress before moving on.",emoji:"🎉",category:"Mindset",difficulty:"Easy",rarity:"Uncommon",durationMinutes:5,timeWindow:"Anytime",actionType:"Toggle",xpReward:35,coinsReward:6,psychologicalProfile:{dopamineYield:"High",flavorText:"Completion deserves recognition.",cognitiveLoad:1},theme:"Royal"}),
 m(t,{id:"mindset-15",title:"Calm Restart",description:"After an unproductive stretch, reset your workspace and begin one clean ten-minute block.",emoji:"🧊",category:"Mindset",difficulty:"Medium",rarity:"Rare",durationMinutes:15,timeWindow:"Anytime",actionType:"Timer",xpReward:75,coinsReward:14,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Restart without drama.",cognitiveLoad:2},theme:"Ice"}),
 m(t,{id:"productivity-11",title:"Define Done",description:"Write the exact finish line for one task before you begin working on it.",emoji:"📌",category:"Productivity",difficulty:"Easy",rarity:"Common",durationMinutes:5,timeWindow:"Anytime",actionType:"Reflection",xpReward:30,coinsReward:5,psychologicalProfile:{dopamineYield:"Low",flavorText:"Clear endings create clear starts.",cognitiveLoad:2},theme:"Ocean"}),
 m(t,{id:"productivity-12",title:"Study Setup",description:"Prepare your book, notes, water, and workspace before starting a focused study block.",emoji:"📚",category:"Productivity",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Morning",actionType:"Timer",xpReward:45,coinsReward:8,psychologicalProfile:{dopamineYield:"Low",flavorText:"Remove friction before focus.",cognitiveLoad:1},theme:"Forest"}),
 m(t,{id:"productivity-13",title:"One Page Better",description:"Improve one page of notes, a draft, or a project instead of trying to perfect everything.",emoji:"📄",category:"Productivity",difficulty:"Medium",rarity:"Uncommon",durationMinutes:20,timeWindow:"Anytime",actionType:"Timer",xpReward:90,coinsReward:18,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Progress loves small surfaces.",cognitiveLoad:3},theme:"Neon"}),
 m(t,{id:"productivity-14",title:"Close Five Loops",description:"Complete five tiny pending actions that each take only a few minutes.",emoji:"5️⃣",category:"Productivity",difficulty:"Medium",rarity:"Rare",durationMinutes:30,timeWindow:"Anytime",actionType:"Timer",xpReward:150,coinsReward:30,psychologicalProfile:{dopamineYield:"High",flavorText:"Clear the mental cache.",cognitiveLoad:2},theme:"Galaxy"}),
 m(t,{id:"productivity-15",title:"Deep Planning",description:"Map one important project into the next three concrete actions.",emoji:"🗺️",category:"Productivity",difficulty:"Hard",rarity:"Epic",durationMinutes:25,timeWindow:"Anytime",actionType:"Reflection",xpReward:140,coinsReward:30,psychologicalProfile:{dopamineYield:"High",flavorText:"Plans turn uncertainty into motion.",cognitiveLoad:5},theme:"Royal"}),
 m(t,{id:"discipline-10",title:"Device Parking",description:"Park your phone outside your immediate workspace during one focused block.",emoji:"🅿️",category:"Discipline",difficulty:"Medium",rarity:"Rare",durationMinutes:30,timeWindow:"Anytime",actionType:"ZenMode",xpReward:140,coinsReward:28,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Distance makes the choice easier.",cognitiveLoad:2},theme:"Void"}),
 m(t,{id:"discipline-11",title:"Finish the Block",description:"Stay with the planned session until its timer ends, even if motivation drops.",emoji:"⏳",category:"Discipline",difficulty:"Hard",rarity:"Epic",durationMinutes:45,timeWindow:"Anytime",actionType:"Timer",xpReward:220,coinsReward:50,psychologicalProfile:{dopamineYield:"Low",flavorText:"Finish without needing perfect motivation.",cognitiveLoad:4},theme:"Volcano"}),
 m(t,{id:"discipline-12",title:"Keep It Simple",description:"Remove one unnecessary step from your routine and follow the simpler version.",emoji:"➖",category:"Discipline",difficulty:"Easy",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:50,coinsReward:9,psychologicalProfile:{dopamineYield:"Low",flavorText:"Simple systems are easier to repeat.",cognitiveLoad:1},theme:"Ice"}),
 m(t,{id:"discipline-13",title:"Earn the Scroll",description:"Complete a useful planned action before choosing entertainment time.",emoji:"🎟️",category:"Discipline",difficulty:"Medium",rarity:"Rare",durationMinutes:25,timeWindow:"Anytime",actionType:"Timer",xpReward:120,coinsReward:24,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Put rewards after effort.",cognitiveLoad:3},theme:"Sunset"}),
 m(t,{id:"discipline-14",title:"Master the Start",description:"Begin your highest-priority task within five minutes of deciding to do it.",emoji:"🚀",category:"Discipline",difficulty:"Hard",rarity:"Legendary",durationMinutes:15,timeWindow:"Anytime",actionType:"Timer",xpReward:180,coinsReward:40,psychologicalProfile:{dopamineYield:"High",flavorText:"Speed up the first move.",cognitiveLoad:3},theme:"Galaxy"}),
];
