// src/lib/challenges.data.ts

import type { OutstandChallenge, ChallengeTheme } from "./challenges.types";

/**
 * ---------------------------------------------------------------------------
 * THEME DICTIONARY
 * Pre-configured design tokens for canvas particles and Tailwind CSS.
 * ---------------------------------------------------------------------------
 */
export const CHALLENGE_THEMES: Record<string, ChallengeTheme> = {
  Ocean: {
    name: "Ocean",
    bgGradient: "from-blue-950 via-slate-900 to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(56,189,248,0.15)]",
    iconContainer: "bg-sky-500/10 border-sky-500/20",
    badgeColor: "text-sky-400",
    particleColors: ["#38bdf8", "#0ea5e9", "#ffffff"],
  },
  Forest: {
    name: "Forest",
    bgGradient: "from-emerald-950 via-slate-900 to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(52,211,153,0.15)]",
    iconContainer: "bg-emerald-500/10 border-emerald-500/20",
    badgeColor: "text-emerald-400",
    particleColors: ["#34d399", "#10b981", "#ffffff"],
  },
  Galaxy: {
    name: "Galaxy",
    bgGradient: "from-indigo-950 via-purple-900/20 to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(129,140,248,0.15)]",
    iconContainer: "bg-indigo-500/10 border-indigo-500/20",
    badgeColor: "text-indigo-400",
    particleColors: ["#818cf8", "#c084fc", "#ffffff"],
  },
  Sunset: {
    name: "Sunset",
    bgGradient: "from-rose-950 via-orange-900/20 to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(251,146,60,0.15)]",
    iconContainer: "bg-orange-500/10 border-orange-500/20",
    badgeColor: "text-orange-400",
    particleColors: ["#fb923c", "#f43f5e", "#ffffff"],
  },
  Volcano: {
    name: "Volcano",
    bgGradient: "from-red-950 via-stone-900 to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(248,113,113,0.15)]",
    iconContainer: "bg-red-500/10 border-red-500/20",
    badgeColor: "text-red-400",
    particleColors: ["#f87171", "#dc2626", "#ffffff"],
  },
  Royal: {
    name: "Royal",
    bgGradient: "from-amber-950/50 via-slate-900 to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(251,191,36,0.15)]",
    iconContainer: "bg-amber-500/10 border-amber-500/20",
    badgeColor: "text-amber-400",
    particleColors: ["#fbbf24", "#f59e0b", "#ffffff"],
  },
  Ice: {
    name: "Ice",
    bgGradient: "from-cyan-950 via-slate-900 to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(34,211,238,0.15)]",
    iconContainer: "bg-cyan-500/10 border-cyan-500/20",
    badgeColor: "text-cyan-400",
    particleColors: ["#22d3ee", "#06b6d4", "#ffffff"],
  },
  Neon: {
    name: "Neon",
    bgGradient: "from-fuchsia-950 via-slate-900 to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(232,121,249,0.15)]",
    iconContainer: "bg-fuchsia-500/10 border-fuchsia-500/20",
    badgeColor: "text-fuchsia-400",
    particleColors: ["#e879f9", "#d946ef", "#ffffff"],
  },
  Void: {
    name: "Void",
    bgGradient: "from-zinc-900/50 via-black to-[#050505]",
    borderGlow: "hover:shadow-[0_0_30px_rgba(255,255,255,0.05)]",
    iconContainer: "bg-zinc-800/50 border-zinc-700/50",
    badgeColor: "text-zinc-400",
    particleColors: ["#a1a1aa", "#71717a", "#ffffff"],
  }
};

/**
 * ---------------------------------------------------------------------------
 * THE MASTER CHALLENGE MATRIX (V1)
 * ---------------------------------------------------------------------------
 */
export const OUTSTAND_CHALLENGES: OutstandChallenge[] = [
  {
    id: "focus_deep_work_01",
    title: "The Deep Trench",
    description: "Execute a continuous deep work session. Zero interruptions, tab switching, or screen wakes.",
    emoji: "🧠",
    durationMinutes: 120,
    category: "Focus",
    difficulty: "Hard",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 400,
    coinsReward: 100,
    dopamineYield: "Low",
    flavorText: "Depth is a superpower in a shallow world.",
    theme: CHALLENGE_THEMES.Ocean,
    audio: {
      onStart: "whoosh",
      onComplete: "ethereal_ping",
    }
  },
  {
    id: "detox_morning_monk_01",
    title: "Monk Mode Morning",
    description: "Do not unlock your phone for the first 60 minutes after waking up. Reclaim your baseline.",
    emoji: "🌅",
    durationMinutes: 60,
    category: "Phone Detox",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 150,
    coinsReward: 25,
    dopamineYield: "Reset",
    flavorText: "Win the morning, win the war.",
    theme: CHALLENGE_THEMES.Volcano,
    audio: {
      onStart: "digital_boot",
      onComplete: "heavy_bass_drop",
    }
  },
  {
    id: "discipline_gray_area_01",
    title: "The Gray Area",
    description: "Switch your phone's display to Grayscale mode for the entire day. Watch the urge to scroll fade.",
    emoji: "👁️",
    durationMinutes: 1440,
    category: "Discipline",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 200,
    coinsReward: 50,
    dopamineYield: "Reset",
    flavorText: "Starve the algorithm of its colors.",
    theme: CHALLENGE_THEMES.Void,
    audio: {
      onComplete: "success_chime",
    }
  },
  {
    id: "mindset_unplugged_wander_01",
    title: "Unplugged Wander",
    description: "Go for a 30-minute walk outside without your phone. Listen to the environment, not a podcast.",
    emoji: "🌲",
    durationMinutes: 30,
    category: "Mindset",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 100,
    coinsReward: 15,
    dopamineYield: "Medium",
    flavorText: "Silence is where you hear yourself think.",
    theme: CHALLENGE_THEMES.Forest,
    audio: {
      onComplete: "ethereal_ping",
    }
  },
  {
    id: "detox_digital_fast_01",
    title: "The 24H Reset",
    description: "A complete digital fast. No social media, no endless scrolling. Just you and reality.",
    emoji: "🛡️",
    durationMinutes: 1440,
    category: "Phone Detox",
    difficulty: "Master",
    rarity: "Legendary",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 1500,
    coinsReward: 500,
    dopamineYield: "Reset",
    flavorText: "The ultimate test of digital sovereignty.",
    theme: CHALLENGE_THEMES.Neon,
    audio: {
      onStart: "digital_boot",
      onComplete: "level_up",
    },
    requirements: {
      minLevel: 5,
      completedChallengeIds: ["detox_morning_monk_01"],
    }
  },
    // ---------------------------------------------------------------------------
  // BATCH 1 - PART 1: Focus, Phone Detox, Mindset
  // ---------------------------------------------------------------------------
  
  // -- FOCUS CATEGORY --
  {
    id: "focus_pomodoro_01",
    title: "The Classic Pomodoro",
    description: "Complete one standard 25-minute Pomodoro block of pure focus.",
    emoji: "🍅",
    durationMinutes: 25,
    category: "Focus",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    dopamineYield: "Low",
    flavorText: "Small blocks build big empires.",
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onStart: "chime", onComplete: "success_chime" }
  },
  {
    id: "focus_single_task_01",
    title: "The Monotasker",
    description: "Work on exactly ONE task for 45 minutes. Close all other tabs and applications.",
    emoji: "🎯",
    durationMinutes: 45,
    category: "Focus",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 80,
    coinsReward: 20,
    dopamineYield: "Low",
    flavorText: "Attention is your most valuable currency.",
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "focus_flow_state_01",
    title: "Flow State Entry",
    description: "Sustain uninterrupted focus for 90 minutes. Do not break eye contact with your work.",
    emoji: "🌊",
    durationMinutes: 90,
    category: "Focus",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 150,
    coinsReward: 40,
    dopamineYield: "Medium",
    flavorText: "Enter the current. Let the world fade.",
    theme: CHALLENGE_THEMES.Ice,
    audio: { onStart: "whoosh", onComplete: "heavy_bass_drop" }
  },
  {
    id: "focus_no_music_01",
    title: "Silent Grind",
    description: "Work for 60 minutes with no music, no podcasts, no background noise. Just raw focus.",
    emoji: "🤫",
    durationMinutes: 60,
    category: "Focus",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 100,
    coinsReward: 25,
    dopamineYield: "Reset",
    flavorText: "Find comfort in the silence.",
    theme: CHALLENGE_THEMES.Void,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "focus_reading_sprint_01",
    title: "Deep Reading Sprint",
    description: "Read a physical book or e-reader (no phone) for 30 uninterrupted minutes.",
    emoji: "📖",
    durationMinutes: 30,
    category: "Focus",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 15,
    dopamineYield: "Medium",
    flavorText: "Download knowledge directly to your brain.",
    theme: CHALLENGE_THEMES.Royal,
    audio: { onComplete: "success_chime" }
  },

  // -- PHONE DETOX CATEGORY --
  {
    id: "detox_airplane_mode_01",
    title: "Radio Silence",
    description: "Keep your phone on Airplane Mode for 2 straight hours while awake.",
    emoji: "✈️",
    durationMinutes: 120,
    category: "Phone Detox",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 100,
    coinsReward: 30,
    dopamineYield: "Reset",
    flavorText: "Disconnect to reconnect.",
    theme: CHALLENGE_THEMES.Ocean, 
    audio: { onStart: "digital_boot", onComplete: "ethereal_ping" }
  },
  {
    id: "detox_dnd_dinner_01",
    title: "Sacred Meal",
    description: "Eat dinner without your phone in the room. Be present with your food or company.",
    emoji: "🍽️",
    durationMinutes: 45,
    category: "Phone Detox",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Evening",
    actionType: "Toggle",
    xpReward: 50,
    coinsReward: 10,
    dopamineYield: "Low",
    flavorText: "Taste your food, not your feed.",
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "detox_app_purge_01",
    title: "The Purge",
    description: "Delete one app from your phone that drains your time but offers no real value.",
    emoji: "🗑️",
    durationMinutes: 5,
    category: "Phone Detox",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 150,
    coinsReward: 50,
    dopamineYield: "High",
    flavorText: "Cut the dead weight.",
    theme: CHALLENGE_THEMES.Volcano,
    audio: { onComplete: "heavy_bass_drop" }
  },
  {
    id: "detox_no_scrolling_01",
    title: "Scroll Strike",
    description: "Zero short-form video content (TikTok, Reels, Shorts) for the entire day.",
    emoji: "🚫",
    durationMinutes: 1440,
    category: "Phone Detox",
    difficulty: "Hard",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 300,
    coinsReward: 75,
    dopamineYield: "Reset",
    flavorText: "Reclaim your attention span.",
    theme: CHALLENGE_THEMES.Neon,
    audio: { onStart: "digital_boot", onComplete: "level_up" }
  },
  {
    id: "detox_leave_it_behind_01",
    title: "Leave It Behind",
    description: "Go to the grocery store or run an errand completely without your phone.",
    emoji: "🚶",
    durationMinutes: 45,
    category: "Phone Detox",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 120,
    coinsReward: 25,
    dopamineYield: "Medium",
    flavorText: "The world still exists offline.",
    theme: CHALLENGE_THEMES.Forest,
    audio: { onComplete: "success_chime" }
  },

  // -- MINDSET CATEGORY --
  {
    id: "mindset_morning_pages_01",
    title: "Morning Pages",
    description: "Write 3 pages of stream-of-consciousness journaling first thing in the morning.",
    emoji: "📝",
    durationMinutes: 20,
    category: "Mindset",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Morning",
    actionType: "Reflection",
    xpReward: 90,
    coinsReward: 20,
    dopamineYield: "Low",
    flavorText: "Clear the mental cache.",
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "mindset_gratitude_01",
    title: "Three Blessings",
    description: "Write down three specific things you are genuinely grateful for today.",
    emoji: "🙏",
    durationMinutes: 5,
    category: "Mindset",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 40,
    coinsReward: 10,
    dopamineYield: "High",
    flavorText: "Abundance is a state of mind.",
    theme: CHALLENGE_THEMES.Royal,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "mindset_meditation_01",
    title: "Still Waters",
    description: "Sit completely still and focus on your breath for 10 minutes. No guided audio.",
    emoji: "🧘",
    durationMinutes: 10,
    category: "Mindset",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 80,
    coinsReward: 15,
    dopamineYield: "Low",
    flavorText: "Observe the mind, do not engage.",
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onStart: "chime", onComplete: "ethereal_ping" }
  },
  {
    id: "mindset_boredom_01",
    title: "Embrace Boredom",
    description: "Stare at a wall for 15 minutes. No inputs. Let your mind wander naturally.",
    emoji: "🧱",
    durationMinutes: 15,
    category: "Mindset",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 120,
    coinsReward: 30,
    dopamineYield: "Reset",
    flavorText: "Boredom is the birthplace of creativity.",
    theme: CHALLENGE_THEMES.Void,
    audio: { onComplete: "heavy_bass_drop" }
  },
  {
    id: "mindset_fear_conquest_01",
    title: "Micro-Courage",
    description: "Do one small thing today that scares you or makes you socially uncomfortable.",
    emoji: "🦁",
    durationMinutes: 10,
    category: "Mindset",
    difficulty: "Extreme",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 250,
    coinsReward: 50,
    dopamineYield: "High",
    flavorText: "Growth lives outside the comfort zone.",
    theme: CHALLENGE_THEMES.Volcano,
    audio: { onComplete: "level_up" }
  },
   // ---------------------------------------------------------------------------
  // BATCH 1 - PART 2: Fitness, Discipline, Productivity
  // ---------------------------------------------------------------------------

  // -- FITNESS CATEGORY --
  {
    id: "fitness_morning_stretch_01",
    title: "Morning Limber",
    description: "Complete a 10-minute full-body stretching routine right after getting out of bed.",
    emoji: "🤸",
    durationMinutes: 10,
    category: "Fitness",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Morning",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    dopamineYield: "Low",
    flavorText: "Wake up your nervous system.",
    theme: CHALLENGE_THEMES.Forest,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "fitness_10k_steps_01",
    title: "The Wanderer",
    description: "Hit 10,000 steps before the end of the day.",
    emoji: "🚶‍♂️",
    durationMinutes: 90,
    category: "Fitness",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 100,
    coinsReward: 25,
    dopamineYield: "Medium",
    flavorText: "Humans were built to move.",
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "fitness_pushup_max_01",
    title: "Gravity Check",
    description: "Do 3 sets of pushups to absolute failure. Rest 60 seconds between sets.",
    emoji: "💪",
    durationMinutes: 10,
    category: "Fitness",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 120,
    coinsReward: 30,
    dopamineYield: "High",
    flavorText: "Push the Earth away.",
    theme: CHALLENGE_THEMES.Volcano,
    audio: { onComplete: "heavy_bass_drop" }
  },
  {
    id: "fitness_hydration_01",
    title: "Hydro Core",
    description: "Drink a full gallon (or 3.5 liters) of water today.",
    emoji: "💧",
    durationMinutes: 1440,
    category: "Fitness",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 80,
    coinsReward: 20,
    dopamineYield: "Low",
    flavorText: "You are mostly water. Refresh the system.",
    theme: CHALLENGE_THEMES.Ice,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "fitness_sprint_01",
    title: "Lung Burner",
    description: "Run 5 all-out sprints (100m each) with walk-back recovery.",
    emoji: "⚡",
    durationMinutes: 20,
    category: "Fitness",
    difficulty: "Extreme",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 200,
    coinsReward: 40,
    dopamineYield: "High",
    flavorText: "Maximum velocity.",
    theme: CHALLENGE_THEMES.Neon,
    audio: { onComplete: "level_up" }
  },

  // -- DISCIPLINE CATEGORY --
  {
    id: "discipline_cold_shower_01",
    title: "The Ice Forge",
    description: "Take a 3-minute shower on the coldest possible setting.",
    emoji: "🧊",
    durationMinutes: 3,
    category: "Discipline",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Morning",
    actionType: "Timer",
    xpReward: 150,
    coinsReward: 35,
    dopamineYield: "High",
    flavorText: "Conquer the flinch.",
    theme: CHALLENGE_THEMES.Ice,
    audio: { onStart: "whoosh", onComplete: "heavy_bass_drop" }
  },
  {
    id: "discipline_make_bed_01",
    title: "First Victory",
    description: "Make your bed perfectly within 5 minutes of waking up.",
    emoji: "🛏️",
    durationMinutes: 5,
    category: "Discipline",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 40,
    coinsReward: 10,
    dopamineYield: "Low",
    flavorText: "Start the day with a win.",
    theme: CHALLENGE_THEMES.Royal,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "discipline_no_sugar_01",
    title: "Sugar Fast",
    description: "Consume zero added sugars or sweet treats for the entire day.",
    emoji: "🍩",
    durationMinutes: 1440,
    category: "Discipline",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 120,
    coinsReward: 30,
    dopamineYield: "Reset",
    flavorText: "Break the chemical hook.",
    theme: CHALLENGE_THEMES.Void,
    audio: { onComplete: "level_up" }
  },
  {
    id: "discipline_early_riser_01",
    title: "Beat the Sun",
    description: "Wake up at 5:00 AM and do not go back to sleep.",
    emoji: "⏰",
    durationMinutes: 0,
    category: "Discipline",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 150,
    coinsReward: 40,
    dopamineYield: "Medium",
    flavorText: "Own the hours others waste.",
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onComplete: "heavy_bass_drop" }
  },
  {
    id: "discipline_posture_01",
    title: "The Stoic Spine",
    description: "Maintain perfect posture for 30 minutes while working or sitting.",
    emoji: "🦴",
    durationMinutes: 30,
    category: "Discipline",
    difficulty: "Easy",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 15,
    dopamineYield: "Low",
    flavorText: "Stand tall. Command space.",
    theme: CHALLENGE_THEMES.Galaxy,
    audio: { onComplete: "ethereal_ping" }
  },

  // -- PRODUCTIVITY CATEGORY --
  {
    id: "prod_daily_plan_01",
    title: "The Architect",
    description: "Write down your top 3 priorities for the day before doing anything else.",
    emoji: "📋",
    durationMinutes: 10,
    category: "Productivity",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 50,
    coinsReward: 10,
    dopamineYield: "Low",
    flavorText: "Design your day, or someone else will.",
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "prod_inbox_zero_01",
    title: "Inbox Zero",
    description: "Process all emails in your primary inbox until it is completely empty.",
    emoji: "📬",
    durationMinutes: 30,
    category: "Productivity",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 90,
    coinsReward: 25,
    dopamineYield: "High",
    flavorText: "Clear the digital clutter.",
    theme: CHALLENGE_THEMES.Neon,
    audio: { onComplete: "level_up" }
  },
  {
    id: "prod_declutter_desk_01",
    title: "Clean Slate",
    description: "Completely clear your physical workspace of all non-essential items.",
    emoji: "🧹",
    durationMinutes: 15,
    category: "Productivity",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 60,
    coinsReward: 15,
    dopamineYield: "Medium",
    flavorText: "A clear desk equals a clear mind.",
    theme: CHALLENGE_THEMES.Void,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "prod_two_minute_rule_01",
    title: "Rapid Fire",
    description: "Find and immediately complete 5 tasks that take less than 2 minutes each.",
    emoji: "⚡",
    durationMinutes: 10,
    category: "Productivity",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 80,
    coinsReward: 20,
    dopamineYield: "High",
    flavorText: "Momentum is everything.",
    theme: CHALLENGE_THEMES.Volcano,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "prod_eat_the_frog_01",
    title: "Eat The Frog",
    description: "Complete the hardest, most dreaded task on your list first thing today.",
    emoji: "🐸",
    durationMinutes: 60,
    category: "Productivity",
    difficulty: "Hard",
    rarity: "Epic",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 200,
    coinsReward: 50,
    dopamineYield: "High",
    flavorText: "Slay the dragon early.",
    theme: CHALLENGE_THEMES.Forest,
    audio: { onComplete: "heavy_bass_drop" }
  },
    // ---------------------------------------------------------------------------
  // BATCH 1 - PART 3: Knowledge, Social, Mixed/Extreme
  // ---------------------------------------------------------------------------

  // -- KNOWLEDGE CATEGORY --
  {
    id: "know_read_10_pages_01",
    title: "The Student",
    description: "Read 10 pages of a non-fiction, educational book.",
    emoji: "📚",
    durationMinutes: 20,
    category: "Knowledge",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 50,
    coinsReward: 10,
    dopamineYield: "Low",
    flavorText: "Compound interest for your brain.",
    theme: CHALLENGE_THEMES.Royal,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "know_new_concept_01",
    title: "Mental Expansion",
    description: "Spend 20 minutes learning about a concept you currently know nothing about.",
    emoji: "💡",
    durationMinutes: 20,
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 80,
    coinsReward: 20,
    dopamineYield: "Medium",
    flavorText: "Map the unknown territory.",
    theme: CHALLENGE_THEMES.Galaxy,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "know_podcast_focus_01",
    title: "Active Listener",
    description: "Listen to an educational podcast for 30 minutes while doing nothing else. Take notes.",
    emoji: "🎧",
    durationMinutes: 30,
    category: "Knowledge",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 120,
    coinsReward: 30,
    dopamineYield: "Low",
    flavorText: "Stop background listening. Start absorbing.",
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onStart: "chime", onComplete: "success_chime" }
  },
  {
    id: "know_teach_someone_01",
    title: "The Professor",
    description: "Explain a complex topic you recently learned to someone else (or write it out simply).",
    emoji: "🗣️",
    durationMinutes: 15,
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 90,
    coinsReward: 25,
    dopamineYield: "Medium",
    flavorText: "To teach is to learn twice.",
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "know_documentary_01",
    title: "Deep Dive",
    description: "Watch a full documentary without touching your phone once.",
    emoji: "🎞️",
    durationMinutes: 90,
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Evening",
    actionType: "Toggle",
    xpReward: 110,
    coinsReward: 30,
    dopamineYield: "Low",
    flavorText: "Swap entertainment for enlightenment.",
    theme: CHALLENGE_THEMES.Void,
    audio: { onComplete: "level_up" }
  },

  // -- SOCIAL CATEGORY --
  {
    id: "social_call_family_01",
    title: "Roots",
    description: "Call a family member or close friend you haven't spoken to in a while. No texting.",
    emoji: "📞",
    durationMinutes: 15,
    category: "Social",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 100,
    coinsReward: 25,
    dopamineYield: "High",
    flavorText: "A voice carries more weight than a text.",
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "social_compliment_01",
    title: "Uplifter",
    description: "Give a genuine, unprompted compliment to a stranger today.",
    emoji: "🤝",
    durationMinutes: 5,
    category: "Social",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 120,
    coinsReward: 30,
    dopamineYield: "High",
    flavorText: "Make someone else's day.",
    theme: CHALLENGE_THEMES.Neon,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "social_eye_contact_01",
    title: "Presence",
    description: "Maintain strong eye contact in every conversation you have today. Do not look at your phone while someone is speaking.",
    emoji: "👁️",
    durationMinutes: 1440,
    category: "Social",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 90,
    coinsReward: 20,
    dopamineYield: "Low",
    flavorText: "Show them they matter.",
    theme: CHALLENGE_THEMES.Royal,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "social_no_gossip_01",
    title: "Golden Tongue",
    description: "Go the entire day without speaking negatively about anyone behind their back.",
    emoji: "🤐",
    durationMinutes: 1440,
    category: "Social",
    difficulty: "Hard",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 150,
    coinsReward: 40,
    dopamineYield: "Reset",
    flavorText: "Great minds discuss ideas, not people.",
    theme: CHALLENGE_THEMES.Ice,
    audio: { onComplete: "level_up" }
  },
  {
    id: "social_deep_question_01",
    title: "Beyond the Surface",
    description: "Ask someone a deep, meaningful question today instead of small talk.",
    emoji: "❓",
    durationMinutes: 10,
    category: "Social",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 80,
    coinsReward: 20,
    dopamineYield: "Medium",
    flavorText: "Skip the weather. Ask about their soul.",
    theme: CHALLENGE_THEMES.Galaxy,
    audio: { onComplete: "success_chime" }
  },
  
  // -- MIXED / EXTREME / MULTI-DAY --
  {
    id: "mixed_weekend_monk_01",
    title: "The Weekend Retreat",
    description: "No screens for 48 hours. Completely analog weekend.",
    emoji: "🏔️",
    durationMinutes: 2880,
    category: "Phone Detox",
    difficulty: "Master",
    rarity: "Divine",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 3000,
    coinsReward: 1000,
    dopamineYield: "Reset",
    flavorText: "Return to your natural state.",
    theme: CHALLENGE_THEMES.Forest,
    audio: { onStart: "digital_boot", onComplete: "level_up" },
    requirements: { minLevel: 10 }
  },
  {
    id: "mixed_100_pushups_01",
    title: "The Century Mark",
    description: "Accumulate 100 pushups by the end of the day.",
    emoji: "💯",
    durationMinutes: 1440,
    category: "Fitness",
    difficulty: "Hard",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 250,
    coinsReward: 50,
    dopamineYield: "High",
    flavorText: "Brick by brick.",
    theme: CHALLENGE_THEMES.Volcano,
    audio: { onComplete: "heavy_bass_drop" }
  },
  {
    id: "mixed_zero_complaints_01",
    title: "Iron Mind",
    description: "Go 24 hours without uttering a single complaint.",
    emoji: "🛡️",
    durationMinutes: 1440,
    category: "Mindset",
    difficulty: "Extreme",
    rarity: "Legendary",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 500,
    coinsReward: 100,
    dopamineYield: "Reset",
    flavorText: "Take extreme ownership.",
    theme: CHALLENGE_THEMES.Void,
    audio: { onComplete: "level_up" },
    requirements: { minStreak: 7 }
  },
  {
    id: "mixed_deep_clean_01",
    title: "The Purifier",
    description: "Spend 60 minutes deep cleaning your living space without background entertainment.",
    emoji: "✨",
    durationMinutes: 60,
    category: "Productivity",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 180,
    coinsReward: 40,
    dopamineYield: "Low",
    flavorText: "Organize your space, organize your mind.",
    theme: CHALLENGE_THEMES.Ice,
    audio: { onStart: "whoosh", onComplete: "ethereal_ping" }
  },
  {
    id: "mixed_fasting_01",
    title: "The Empty Vessel",
    description: "Complete a 16-hour intermittent fast (water and black coffee only).",
    emoji: "⏳",
    durationMinutes: 960,
    category: "Discipline",
    difficulty: "Hard",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 300,
    coinsReward: 60,
    dopamineYield: "Reset",
    flavorText: "Hunger is just a sensation.",
    theme: CHALLENGE_THEMES.Galaxy,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "focus_no_tabs_01",
    title: "Tab Minimalist",
    description: "Keep a maximum of 3 browser tabs open for your entire workday.",
    emoji: "📑",
    durationMinutes: 480,
    category: "Focus",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 100,
    coinsReward: 20,
    dopamineYield: "Low",
    flavorText: "Context switching kills momentum.",
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onComplete: "success_chime" }
  },
  {
    id: "detox_no_youtube_01",
    title: "The Algorithm Fast",
    description: "Zero YouTube for 24 hours. No exceptions.",
    emoji: "📺",
    durationMinutes: 1440,
    category: "Phone Detox",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Toggle",
    xpReward: 200,
    coinsReward: 45,
    dopamineYield: "Reset",
    flavorText: "Stop watching others live.",
    theme: CHALLENGE_THEMES.Neon,
    audio: { onComplete: "level_up" }
  },
  {
    id: "mindset_forgiveness_01",
    title: "Letting Go",
    description: "Write a letter of forgiveness to someone who wronged you (you don't have to send it).",
    emoji: "🕊️",
    durationMinutes: 20,
    category: "Mindset",
    difficulty: "Extreme",
    rarity: "Epic",
    timeWindow: "Anytime",
    actionType: "Reflection",
    xpReward: 350,
    coinsReward: 80,
    dopamineYield: "Reset",
    flavorText: "Anger is poison you drink yourself.",
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onComplete: "ethereal_ping" }
  },
  {
    id: "fitness_yoga_01",
    title: "The Flow",
    description: "Complete a 30-minute yoga or mobility session.",
    emoji: "🧘‍♂️",
    durationMinutes: 30,
    category: "Fitness",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 90,
    coinsReward: 20,
    dopamineYield: "Low",
    flavorText: "Strength requires flexibility.",
    theme: CHALLENGE_THEMES.Forest,
    audio: { onStart: "chime", onComplete: "success_chime" }
  },
  {
    id: "discipline_no_snooze_01",
    title: "One Alarm",
    description: "Wake up on your very first alarm. No snoozing.",
    emoji: "🔔",
    durationMinutes: 0,
    category: "Discipline",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Morning",
    actionType: "Toggle",
    xpReward: 120,
    coinsReward: 25,
    dopamineYield: "Medium",
    flavorText: "Don't negotiate with your weaknesses.",
    theme: CHALLENGE_THEMES.Volcano,
    audio: { onComplete: "heavy_bass_drop" }
  } 
];
      
