import type { ChallengeId, ChallengeTheme, OutstandChallenge, ThemeName } from "./challenges.types";

const id = (value: string) => value as ChallengeId;

export const CHALLENGE_THEMES: Record<ThemeName, ChallengeTheme> = {
  Ocean: { name: "Ocean", bgGradient: "bg-gradient-to-br from-cyan-950 via-slate-950 to-black", borderGlow: "hover:shadow-[0_0_45px_rgba(34,211,238,.18)]", iconContainer: "bg-cyan-400/10 border-cyan-300/20", badgeColor: "text-cyan-300", particleColors: ["#22d3ee", "#38bdf8", "#fff"], cinematicVFX: "none" },
  Forest: { name: "Forest", bgGradient: "bg-gradient-to-br from-emerald-950 via-slate-950 to-black", borderGlow: "hover:shadow-[0_0_45px_rgba(52,211,153,.18)]", iconContainer: "bg-emerald-400/10 border-emerald-300/20", badgeColor: "text-emerald-300", particleColors: ["#34d399", "#10b981", "#fff"], cinematicVFX: "none" },
  Galaxy: { name: "Galaxy", bgGradient: "bg-gradient-to-br from-indigo-950 via-purple-950 to-black", borderGlow: "hover:shadow-[0_0_55px_rgba(129,140,248,.22)]", iconContainer: "bg-indigo-400/10 border-indigo-300/20", badgeColor: "text-indigo-300", particleColors: ["#818cf8", "#c084fc", "#fff"], cinematicVFX: "aurora_burst" },
  Sunset: { name: "Sunset", bgGradient: "bg-gradient-to-br from-orange-950 via-rose-950 to-black", borderGlow: "hover:shadow-[0_0_45px_rgba(251,146,60,.18)]", iconContainer: "bg-orange-400/10 border-orange-300/20", badgeColor: "text-orange-300", particleColors: ["#fb923c", "#f43f5e", "#fff"], cinematicVFX: "none" },
  Volcano: { name: "Volcano", bgGradient: "bg-gradient-to-br from-red-950 via-zinc-950 to-black", borderGlow: "hover:shadow-[0_0_55px_rgba(248,113,113,.22)]", iconContainer: "bg-red-400/10 border-red-300/20", badgeColor: "text-red-300", particleColors: ["#f87171", "#ef4444", "#fff"], cinematicVFX: "cosmic_shockwave" },
  Royal: { name: "Royal", bgGradient: "bg-gradient-to-br from-amber-950 via-zinc-950 to-black", borderGlow: "hover:shadow-[0_0_60px_rgba(251,191,36,.25)]", iconContainer: "bg-amber-400/10 border-amber-300/20", badgeColor: "text-amber-300", particleColors: ["#fbbf24", "#f59e0b", "#fff"], cinematicVFX: "divine_light" },
  Ice: { name: "Ice", bgGradient: "bg-gradient-to-br from-sky-950 via-cyan-950 to-black", borderGlow: "hover:shadow-[0_0_45px_rgba(56,189,248,.18)]", iconContainer: "bg-sky-400/10 border-sky-300/20", badgeColor: "text-sky-300", particleColors: ["#38bdf8", "#67e8f9", "#fff"], cinematicVFX: "none" },
  Neon: { name: "Neon", bgGradient: "bg-gradient-to-br from-fuchsia-950 via-violet-950 to-black", borderGlow: "hover:shadow-[0_0_55px_rgba(232,121,249,.22)]", iconContainer: "bg-fuchsia-400/10 border-fuchsia-300/20", badgeColor: "text-fuchsia-300", particleColors: ["#e879f9", "#c084fc", "#fff"], cinematicVFX: "aurora_burst" },
  Void: { name: "Void", bgGradient: "bg-gradient-to-br from-zinc-900 via-black to-black", borderGlow: "hover:shadow-[0_0_45px_rgba(255,255,255,.10)]", iconContainer: "bg-white/5 border-white/10", badgeColor: "text-zinc-200", particleColors: ["#d4d4d8", "#71717a", "#fff"], cinematicVFX: "none" },
};

const challenge = (data: Omit<OutstandChallenge, "id"> & { id: string }): OutstandChallenge => ({ ...data, id: id(data.id) });

export const CHALLENGES: OutstandChallenge[] = [
  challenge({ id: "deep-work-45", title: "Deep Work 45", description: "Pick one meaningful task. One tab. One objective. Stay with it for 45 uninterrupted minutes.", emoji: "🎯", category: "Focus", difficulty: "Hard", rarity: "Epic", durationMinutes: 45, timeWindow: "Anytime", actionType: "Timer", xpReward: 250, coinsReward: 60, psychologicalProfile: { dopamineYield: "Low", flavorText: "Attention compounds when you stop resetting it.", cognitiveLoad: 5 }, theme: CHALLENGE_THEMES.Ocean, audio: { onStart: "deep_hum", onComplete: "heavy_bass_drop" }, haptics: { onStart: "medium", onComplete: "cinematic_rumble" } }),
  challenge({ id: "phone-free-30", title: "Phone-Free 30", description: "Put your phone out of reach and give the next 30 minutes to the task in front of you.", emoji: "📵", category: "Phone Detox", difficulty: "Medium", rarity: "Rare", durationMinutes: 30, timeWindow: "Anytime", actionType: "ZenMode", xpReward: 120, coinsReward: 25, psychologicalProfile: { dopamineYield: "Reset", flavorText: "Distance creates discipline.", cognitiveLoad: 2 }, theme: CHALLENGE_THEMES.Forest, audio: { onStart: "chime", onComplete: "success_chime" }, haptics: { onStart: "light", onComplete: "success" } }),
  challenge({ id: "study-sprint-25", title: "Study Sprint", description: "Complete a focused 25-minute sprint on the hardest chapter you are avoiding.", emoji: "⚡", category: "Knowledge", difficulty: "Medium", rarity: "Common", durationMinutes: 25, timeWindow: "Anytime", actionType: "Timer", xpReward: 100, coinsReward: 20, psychologicalProfile: { dopamineYield: "Medium", flavorText: "Start before you feel ready.", cognitiveLoad: 4 }, theme: CHALLENGE_THEMES.Galaxy, audio: { onStart: "digital_boot", onComplete: "level_up" }, haptics: { onStart: "light", onComplete: "success" } }),
  challenge({ id: "reset-room-15", title: "Reset Your Space", description: "Clear the surface around you, remove distractions, and create a clean launchpad for the next task.", emoji: "✨", category: "Productivity", difficulty: "Easy", rarity: "Common", durationMinutes: 15, timeWindow: "Anytime", actionType: "Timer", xpReward: 60, coinsReward: 10, psychologicalProfile: { dopamineYield: "Low", flavorText: "Make the right action the easy action.", cognitiveLoad: 1 }, theme: CHALLENGE_THEMES.Ice, audio: { onComplete: "success_chime" }, haptics: { onComplete: "success" } }),
  challenge({ id: "mindful-breath-10", title: "Clear Signal", description: "Step away from the screen and spend ten quiet minutes breathing slowly and resetting your attention.", emoji: "🌊", category: "Mindset", difficulty: "Easy", rarity: "Uncommon", durationMinutes: 10, timeWindow: "Anytime", actionType: "Timer", xpReward: 50, coinsReward: 10, psychologicalProfile: { dopamineYield: "Reset", flavorText: "Calm is a performance advantage.", cognitiveLoad: 2 }, theme: CHALLENGE_THEMES.Ocean, audio: { onStart: "deep_hum", onComplete: "ethereal_ping" }, haptics: { onComplete: "light" } }),
  challenge({ id: "pomodoro-pair", title: "Two-Sprint Stack", description: "Complete two focused 25-minute blocks. Use the break to move, drink water, and return immediately.", emoji: "⏱️", category: "Productivity", difficulty: "Hard", rarity: "Rare", durationMinutes: 60, timeWindow: "Anytime", actionType: "Timer", xpReward: 280, coinsReward: 70, psychologicalProfile: { dopamineYield: "High", flavorText: "Consistency beats intensity when repeated.", cognitiveLoad: 4 }, theme: CHALLENGE_THEMES.Galaxy, audio: { onStart: "digital_boot", onComplete: "level_up" }, haptics: { onStart: "medium", onTick: "light", onComplete: "heavy" } }),
  challenge({ id: "movement-reset", title: "Body Reset", description: "Take a short movement break: walk, stretch, or loosen your shoulders before your next work block.", emoji: "🧘", category: "Fitness", difficulty: "Easy", rarity: "Common", durationMinutes: 10, timeWindow: "Anytime", actionType: "Timer", xpReward: 45, coinsReward: 8, psychologicalProfile: { dopamineYield: "Low", flavorText: "A better body supports a better session.", cognitiveLoad: 1 }, theme: CHALLENGE_THEMES.Forest, audio: { onComplete: "success_chime" }, haptics: { onComplete: "light" } }),
  challenge({ id: "zero-notifications", title: "Zero Notifications", description: "Silence non-essential notifications and protect one uninterrupted study or creation block.", emoji: "🔕", category: "Discipline", difficulty: "Medium", rarity: "Epic", durationMinutes: 60, timeWindow: "Anytime", actionType: "ZenMode", xpReward: 220, coinsReward: 50, psychologicalProfile: { dopamineYield: "Reset", flavorText: "Your attention deserves a firewall.", cognitiveLoad: 2 }, theme: CHALLENGE_THEMES.Sunset, audio: { onStart: "chime", onComplete: "heavy_bass_drop" }, haptics: { onStart: "medium", onComplete: "heavy" } }),
  challenge({ id: "reflection-three", title: "Three-Line Review", description: "Write three lines: what worked today, what distracted you, and the one change you will make tomorrow.", emoji: "📝", category: "Mindset", difficulty: "Medium", rarity: "Rare", durationMinutes: 15, timeWindow: "Evening", actionType: "Reflection", xpReward: 110, coinsReward: 25, psychologicalProfile: { dopamineYield: "Medium", flavorText: "Reflection turns experience into progress.", cognitiveLoad: 3 }, theme: CHALLENGE_THEMES.Neon, audio: { onStart: "whoosh", onComplete: "ethereal_ping" }, haptics: { onStart: "light", onComplete: "success" } }),
  challenge({ id: "exam-simulation", title: "Exam Mode", description: "Run a serious timed practice block. No checking answers, messages, or entertainment until the block ends.", emoji: "🏛️", category: "Knowledge", difficulty: "Extreme", rarity: "Legendary", durationMinutes: 90, timeWindow: "Anytime", actionType: "Timer", xpReward: 500, coinsReward: 130, psychologicalProfile: { dopamineYield: "Surge", flavorText: "Train under pressure. Perform with clarity.", cognitiveLoad: 5 }, requirements: { minLevel: 3 }, theme: CHALLENGE_THEMES.Royal, audio: { onStart: "chime", onComplete: "mythic_choir" }, haptics: { onStart: "heavy", onTick: "light", onComplete: "cinematic_rumble" } }),
  challenge({ id: "four-hour-blackout", title: "The Blackout", description: "Create a protected offline block. Remove entertainment apps from the session and work from your chosen offline material.", emoji: "🌑", category: "Phone Detox", difficulty: "Extreme", rarity: "Mythic", durationMinutes: 120, timeWindow: "Anytime", actionType: "ZenMode", xpReward: 700, coinsReward: 180, psychologicalProfile: { dopamineYield: "Surge", flavorText: "Silence the feed. Hear your own priorities.", cognitiveLoad: 4 }, requirements: { minStreak: 3 }, theme: CHALLENGE_THEMES.Void, audio: { onStart: "deep_hum", onComplete: "mythic_choir" }, haptics: { onStart: "heavy", onComplete: "cinematic_rumble" } }),
  challenge({ id: "morning-first-win", title: "First Win", description: "Start your day with one useful action before opening entertainment: study, movement, planning, or reading.", emoji: "🌅", category: "Discipline", difficulty: "Medium", rarity: "Rare", durationMinutes: 20, timeWindow: "Morning", actionType: "Timer", xpReward: 100, coinsReward: 20, psychologicalProfile: { dopamineYield: "Reset", flavorText: "Own the first decision of the day.", cognitiveLoad: 2 }, theme: CHALLENGE_THEMES.Sunset, audio: { onStart: "chime", onComplete: "success_chime" }, haptics: { onStart: "light", onComplete: "success" } }),
  challenge({ id: "social-courage", title: "Courage Rep", description: "Do one small positive social action you have been putting off: ask, thank, explain, or start a conversation.", emoji: "🤝", category: "Social", difficulty: "Medium", rarity: "Rare", durationMinutes: 10, timeWindow: "Anytime", actionType: "Toggle", xpReward: 90, coinsReward: 20, psychologicalProfile: { dopamineYield: "High", flavorText: "Confidence grows through reps, not waiting.", cognitiveLoad: 3 }, theme: CHALLENGE_THEMES.Neon, audio: { onComplete: "success_chime" }, haptics: { onComplete: "success" } }),
  challenge({ id: "mastery-block", title: "Mastery Block", description: "Choose the skill that matters most this week and give it a protected 60-minute session with a measurable outcome.", emoji: "💎", category: "Focus", difficulty: "Master", rarity: "Divine", durationMinutes: 60, timeWindow: "Anytime", actionType: "Timer", xpReward: 800, coinsReward: 220, psychologicalProfile: { dopamineYield: "Surge", flavorText: "Do less. Go deeper. Finish stronger.", cognitiveLoad: 5 }, requirements: { minLevel: 5 }, theme: CHALLENGE_THEMES.Royal, audio: { onStart: "deep_hum", onComplete: "mythic_choir" }, haptics: { onStart: "heavy", onComplete: "cinematic_rumble" } }),
];
