import type { ChallengeTheme, OutstandChallenge, ThemeName, ChallengeId } from "./challenges.types";

type BatchInput = Omit<OutstandChallenge, "id" | "theme" | "audio" | "haptics"> & { id: string; theme: ThemeName };
const id = (value: string) => value as ChallengeId;
const mission = (themes: Record<ThemeName, ChallengeTheme>, data: BatchInput): OutstandChallenge => ({
  ...data,
  id: id(data.id),
  theme: themes[data.theme],
  audio: { onComplete: "success_chime" },
  haptics: { onComplete: "success" },
});

export const createChallengeBatch01 = (themes: Record<ThemeName, ChallengeTheme>): OutstandChallenge[] => [
  mission(themes, { id:"focus-01", title:"Single-Task Lock", description:"Choose one task and stay with it until the timer ends.", emoji:"🎯", category:"Focus", difficulty:"Medium", rarity:"Uncommon", durationMinutes:20, timeWindow:"Anytime", actionType:"Timer", xpReward:80, coinsReward:15, psychologicalProfile:{dopamineYield:"Low", flavorText:"One target. No drift.", cognitiveLoad:3}, theme:"Ocean" }),
  mission(themes, { id:"focus-02", title:"Deep Desk", description:"Complete a quiet 30-minute work block with notifications silenced.", emoji:"🧠", category:"Focus", difficulty:"Hard", rarity:"Rare", durationMinutes:30, timeWindow:"Anytime", actionType:"Timer", xpReward:140, coinsReward:30, psychologicalProfile:{dopamineYield:"Low", flavorText:"Depth compounds.", cognitiveLoad:4}, theme:"Galaxy" }),
  mission(themes, { id:"focus-03", title:"Distraction Shield", description:"Write your task on paper, then finish it without switching apps.", emoji:"🛡️", category:"Focus", difficulty:"Medium", rarity:"Rare", durationMinutes:25, timeWindow:"Anytime", actionType:"ZenMode", xpReward:120, coinsReward:25, psychologicalProfile:{dopamineYield:"Reset", flavorText:"Protect the signal.", cognitiveLoad:3}, theme:"Forest" }),
  mission(themes, { id:"focus-04", title:"Finish Line", description:"Return to one unfinished task and bring it to a clear stopping point.", emoji:"🏁", category:"Focus", difficulty:"Hard", rarity:"Epic", durationMinutes:45, timeWindow:"Anytime", actionType:"Timer", xpReward:240, coinsReward:55, psychologicalProfile:{dopamineYield:"High", flavorText:"Finish what you start.", cognitiveLoad:4}, theme:"Royal" }),
  mission(themes, { id:"focus-05", title:"Silent Hour", description:"Give one full hour to study, practice, or creation without entertainment.", emoji:"🤫", category:"Focus", difficulty:"Hard", rarity:"Legendary", durationMinutes:60, timeWindow:"Anytime", actionType:"ZenMode", xpReward:360, coinsReward:90, psychologicalProfile:{dopamineYield:"Low", flavorText:"Silence creates space.", cognitiveLoad:5}, theme:"Void" }),
  mission(themes, { id:"study-01", title:"Formula Forge", description:"Review one set of formulas and solve a few problems using them.", emoji:"📐", category:"Knowledge", difficulty:"Medium", rarity:"Uncommon", durationMinutes:25, timeWindow:"Anytime", actionType:"Timer", xpReward:100, coinsReward:20, psychologicalProfile:{dopamineYield:"Medium", flavorText:"Recall beats rereading.", cognitiveLoad:4}, theme:"Ice" }),
  mission(themes, { id:"study-02", title:"Recall Run", description:"Close your notes and write everything you remember about one topic.", emoji:"🧩", category:"Knowledge", difficulty:"Hard", rarity:"Rare", durationMinutes:20, timeWindow:"Anytime", actionType:"Reflection", xpReward:130, coinsReward:28, psychologicalProfile:{dopamineYield:"Medium", flavorText:"Make memory work.", cognitiveLoad:4}, theme:"Neon" }),
  mission(themes, { id:"study-03", title:"Chapter Closeout", description:"Finish the final exercises or questions from one chapter.", emoji:"📚", category:"Knowledge", difficulty:"Medium", rarity:"Rare", durationMinutes:40, timeWindow:"Anytime", actionType:"Timer", xpReward:180, coinsReward:40, psychologicalProfile:{dopamineYield:"High", flavorText:"Completion is a skill.", cognitiveLoad:4}, theme:"Ocean" }),
  mission(themes, { id:"study-04", title:"Teach It Back", description:"Explain a topic aloud as if you were teaching it to a beginner.", emoji:"🎓", category:"Knowledge", difficulty:"Hard", rarity:"Epic", durationMinutes:20, timeWindow:"Anytime", actionType:"Reflection", xpReward:170, coinsReward:38, psychologicalProfile:{dopamineYield:"High", flavorText:"If you can teach it, you own it.", cognitiveLoad:5}, theme:"Royal" }),
  mission(themes, { id:"study-05", title:"Question Hunter", description:"Find and solve five questions that target your weakest area.", emoji:"🔎", category:"Knowledge", difficulty:"Hard", rarity:"Epic", durationMinutes:35, timeWindow:"Anytime", actionType:"Timer", xpReward:210, coinsReward:48, psychologicalProfile:{dopamineYield:"High", flavorText:"Attack the gap.", cognitiveLoad:5}, theme:"Galaxy" }),
  mission(themes, { id:"study-06", title:"Error Notebook", description:"Review recent mistakes and record the lesson behind each one.", emoji:"✍️", category:"Knowledge", difficulty:"Medium", rarity:"Uncommon", durationMinutes:15, timeWindow:"Evening", actionType:"Reflection", xpReward:90, coinsReward:18, psychologicalProfile:{dopamineYield:"Medium", flavorText:"Mistakes become assets when studied.", cognitiveLoad:3}, theme:"Sunset" }),
  mission(themes, { id:"detox-01", title:"No Scroll Start", description:"Begin your next work block without opening short-form entertainment.", emoji:"📵", category:"Phone Detox", difficulty:"Easy", rarity:"Common", durationMinutes:15, timeWindow:"Morning", actionType:"ZenMode", xpReward:50, coinsReward:8, psychologicalProfile:{dopamineYield:"Reset", flavorText:"Choose before the feed chooses for you.", cognitiveLoad:1}, theme:"Forest" }),
  mission(themes, { id:"detox-02", title:"Pocket Down", description:"Keep your phone out of your hands for the next focused block.", emoji:"📱", category:"Phone Detox", difficulty:"Medium", rarity:"Uncommon", durationMinutes:30, timeWindow:"Anytime", actionType:"ZenMode", xpReward:120, coinsReward:24, psychologicalProfile:{dopamineYield:"Reset", flavorText:"Attention is yours.", cognitiveLoad:2}, theme:"Void" }),
  mission(themes, { id:"detox-03", title:"Notification Fast", description:"Turn off non-essential notifications for a protected work session.", emoji:"🔕", category:"Phone Detox", difficulty:"Medium", rarity:"Rare", durationMinutes:45, timeWindow:"Anytime", actionType:"Toggle", xpReward:150, coinsReward:30, psychologicalProfile:{dopamineYield:"Reset", flavorText:"Silence the interruptions.", cognitiveLoad:2}, theme:"Sunset" }),
  mission(themes, { id:"detox-04", title:"Offline Block", description:"Work from offline materials for one uninterrupted study block.", emoji:"🌿", category:"Phone Detox", difficulty:"Hard", rarity:"Epic", durationMinutes:60, timeWindow:"Anytime", actionType:"ZenMode", xpReward:300, coinsReward:70, psychologicalProfile:{dopamineYield:"Low", flavorText:"Less input. More output.", cognitiveLoad:4}, theme:"Forest" }),
  mission(themes, { id:"detox-05", title:"Evening Unplug", description:"Finish your evening task before opening entertainment apps again.", emoji:"🌙", category:"Phone Detox", difficulty:"Medium", rarity:"Rare", durationMinutes:30, timeWindow:"Evening", actionType:"Toggle", xpReward:120, coinsReward:25, psychologicalProfile:{dopamineYield:"Reset", flavorText:"End the day intentionally.", cognitiveLoad:2}, theme:"Galaxy" }),
  mission(themes, { id:"mindset-01", title:"Start Anyway", description:"Spend ten minutes on a task you have been avoiding.", emoji:"🚀", category:"Mindset", difficulty:"Easy", rarity:"Common", durationMinutes:10, timeWindow:"Anytime", actionType:"Timer", xpReward:45, coinsReward:8, psychologicalProfile:{dopamineYield:"Medium", flavorText:"Action creates motivation.", cognitiveLoad:2}, theme:"Volcano" }),
  mission(themes, { id:"mindset-02", title:"Reset the Miss", description:"After a distraction, restart calmly instead of abandoning the session.", emoji:"🔄", category:"Mindset", difficulty:"Medium", rarity:"Uncommon", durationMinutes:15, timeWindow:"Anytime", actionType:"Timer", xpReward:70, coinsReward:12, psychologicalProfile:{dopamineYield:"Reset", flavorText:"A reset is not a failure.", cognitiveLoad:2}, theme:"Ice" }),
  mission(themes, { id:"mindset-03", title:"Win the Next Ten", description:"Forget the lost time and make the next ten minutes count.", emoji:"⏩", category:"Mindset", difficulty:"Easy", rarity:"Common", durationMinutes:10, timeWindow:"Anytime", actionType:"Timer", xpReward:40, coinsReward:7, psychologicalProfile:{dopamineYield:"Medium", flavorText:"The next decision still matters.", cognitiveLoad:1}, theme:"Ocean" }),
  mission(themes, { id:"mindset-04", title:"Evidence Log", description:"Write three things you did well today and one thing to improve.", emoji:"📈", category:"Mindset", difficulty:"Easy", rarity:"Uncommon", durationMinutes:10, timeWindow:"Evening", actionType:"Reflection", xpReward:60, coinsReward:10, psychologicalProfile:{dopamineYield:"Medium", flavorText:"Track reality, not mood.", cognitiveLoad:2}, theme:"Neon" }),
  mission(themes, { id:"mindset-05", title:"Pressure Practice", description:"Do one useful task while keeping the timer visible and distractions away.", emoji:"🔥", category:"Mindset", difficulty:"Hard", rarity:"Epic", durationMinutes:40, timeWindow:"Anytime", actionType:"Timer", xpReward:220, coinsReward:50, psychologicalProfile:{dopamineYield:"High", flavorText:"Pressure becomes familiar through practice.", cognitiveLoad:4}, theme:"Volcano" }),
  mission(themes, { id:"fitness-01", title:"Movement Minute", description:"Take a short movement break before your next sitting block.", emoji:"🚶", category:"Fitness", difficulty:"Easy", rarity:"Common", durationMinutes:5, timeWindow:"Anytime", actionType:"Toggle", xpReward:25, coinsReward:5, psychologicalProfile:{dopamineYield:"Low", flavorText:"Move, then return.", cognitiveLoad:1}, theme:"Forest" }),
  mission(themes, { id:"fitness-02", title:"Posture Reset", description:"Reset your sitting position and spend a few minutes moving gently.", emoji:"🧘", category:"Fitness", difficulty:"Easy", rarity:"Common", durationMinutes:10, timeWindow:"Anytime", actionType:"Timer", xpReward:45, coinsReward:8, psychologicalProfile:{dopamineYield:"Low", flavorText:"Comfort supports consistency.", cognitiveLoad:1}, theme:"Ice" }),
  mission(themes, { id:"fitness-03", title:"Walk & Think", description:"Take a short walk and mentally rehearse your next important task.", emoji:"👟", category:"Fitness", difficulty:"Easy", rarity:"Uncommon", durationMinutes:15, timeWindow:"Anytime", actionType:"Timer", xpReward:65, coinsReward:12, psychologicalProfile:{dopamineYield:"Medium", flavorText:"Movement clears the runway.", cognitiveLoad:2}, theme:"Ocean" }),
];
