import type { ChallengeTheme, OutstandChallenge, ThemeName, ChallengeId } from "./challenges.types";
type I=Omit<OutstandChallenge,"id"|"theme"|"audio"|"haptics">&{id:string;theme:ThemeName};
const id=(v:string)=>v as ChallengeId;
const m=(t:Record<ThemeName,ChallengeTheme>,d:I):OutstandChallenge=>({...d,id:id(d.id),theme:t[d.theme],audio:{onComplete:"success_chime"},haptics:{onComplete:"success"}});
export const createChallengeBatch03=(t:Record<ThemeName,ChallengeTheme>):OutstandChallenge[]=>[
 m(t,{id:"focus-06",title:"First 15",description:"Start with fifteen uninterrupted minutes on the task that matters most.",emoji:"▶️",category:"Focus",difficulty:"Easy",rarity:"Common",durationMinutes:15,timeWindow:"Anytime",actionType:"Timer",xpReward:55,coinsReward:10,psychologicalProfile:{dopamineYield:"Low",flavorText:"Starting is the first win.",cognitiveLoad:2},theme:"Ocean"}),
 m(t,{id:"focus-07",title:"No Tab Drift",description:"Keep only the resources required for your current task open.",emoji:"🗂️",category:"Focus",difficulty:"Medium",rarity:"Uncommon",durationMinutes:25,timeWindow:"Anytime",actionType:"ZenMode",xpReward:110,coinsReward:22,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Less switching, more depth.",cognitiveLoad:3},theme:"Galaxy"}),
 m(t,{id:"focus-08",title:"Hardest First",description:"Spend one focused block on the hardest useful task on your list.",emoji:"🥇",category:"Focus",difficulty:"Hard",rarity:"Rare",durationMinutes:35,timeWindow:"Morning",actionType:"Timer",xpReward:180,coinsReward:40,psychologicalProfile:{dopamineYield:"High",flavorText:"Use your best attention wisely.",cognitiveLoad:5},theme:"Royal"}),
 m(t,{id:"focus-09",title:"Clean Finish",description:"Take a nearly finished task and close the final meaningful gap.",emoji:"🏆",category:"Focus",difficulty:"Medium",rarity:"Epic",durationMinutes:30,timeWindow:"Anytime",actionType:"Timer",xpReward:170,coinsReward:38,psychologicalProfile:{dopamineYield:"High",flavorText:"Finish creates freedom.",cognitiveLoad:4},theme:"Sunset"}),
 m(t,{id:"focus-10",title:"Deep Six",description:"Stay with one meaningful task for a full six-minute warm-up, then continue if ready.",emoji:"🌊",category:"Focus",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Anytime",actionType:"Timer",xpReward:35,coinsReward:6,psychologicalProfile:{dopamineYield:"Low",flavorText:"Ease into depth.",cognitiveLoad:2},theme:"Ice"}),
 m(t,{id:"knowledge-07",title:"Flashcard Forge",description:"Review one small set of flashcards using active recall instead of rereading.",emoji:"🃏",category:"Knowledge",difficulty:"Medium",rarity:"Uncommon",durationMinutes:20,timeWindow:"Anytime",actionType:"Timer",xpReward:85,coinsReward:16,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Retrieve, don't just recognize.",cognitiveLoad:4},theme:"Neon"}),
 m(t,{id:"knowledge-08",title:"Explain the Why",description:"Pick one fact or formula and explain why it works in your own words.",emoji:"💡",category:"Knowledge",difficulty:"Hard",rarity:"Rare",durationMinutes:15,timeWindow:"Anytime",actionType:"Reflection",xpReward:105,coinsReward:22,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Understanding has structure.",cognitiveLoad:5},theme:"Ocean"}),
 m(t,{id:"knowledge-09",title:"Five-Minute Quiz",description:"Test yourself on one topic without looking at notes until the quiz is complete.",emoji:"🧪",category:"Knowledge",difficulty:"Medium",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Timer",xpReward:60,coinsReward:12,psychologicalProfile:{dopamineYield:"High",flavorText:"Measure before you review.",cognitiveLoad:4},theme:"Galaxy"}),
 m(t,{id:"knowledge-10",title:"Weak Link",description:"Identify one topic you consistently miss and practice only that gap.",emoji:"🔗",category:"Knowledge",difficulty:"Hard",rarity:"Epic",durationMinutes:30,timeWindow:"Anytime",actionType:"Timer",xpReward:180,coinsReward:40,psychologicalProfile:{dopamineYield:"High",flavorText:"Targeted work moves faster.",cognitiveLoad:5},theme:"Volcano"}),
 m(t,{id:"knowledge-11",title:"Summary Card",description:"Compress one lesson into a single page of essential ideas, formulas, and examples.",emoji:"📄",category:"Knowledge",difficulty:"Medium",rarity:"Rare",durationMinutes:25,timeWindow:"Anytime",actionType:"Reflection",xpReward:120,coinsReward:25,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Compression reveals structure.",cognitiveLoad:4},theme:"Royal"}),
 m(t,{id:"knowledge-12",title:"Question Ladder",description:"Solve one easy, one medium, and one hard question from the same topic.",emoji:"🪜",category:"Knowledge",difficulty:"Hard",rarity:"Epic",durationMinutes:35,timeWindow:"Anytime",actionType:"Timer",xpReward:200,coinsReward:45,psychologicalProfile:{dopamineYield:"High",flavorText:"Build difficulty gradually.",cognitiveLoad:5},theme:"Ice"}),
 m(t,{id:"detox-06",title:"Feed-Free Break",description:"Take your break without social feeds; move, breathe, or simply rest instead.",emoji:"🌿",category:"Phone Detox",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:40,coinsReward:7,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Rest without stimulation.",cognitiveLoad:1},theme:"Forest"}),
 m(t,{id:"detox-07",title:"Home Screen Clean",description:"Remove one distracting shortcut from your home screen and make your next action obvious.",emoji:"🧹",category:"Phone Detox",difficulty:"Easy",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:50,coinsReward:9,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Design your environment.",cognitiveLoad:1},theme:"Ice"}),
 m(t,{id:"detox-08",title:"One Hour Offline",description:"Spend an hour with your chosen work while keeping entertainment apps closed.",emoji:"⏳",category:"Phone Detox",difficulty:"Hard",rarity:"Epic",durationMinutes:60,timeWindow:"Anytime",actionType:"ZenMode",xpReward:300,coinsReward:70,psychologicalProfile:{dopamineYield:"Low",flavorText:"Attention grows when protected.",cognitiveLoad:4},theme:"Void"}),
 m(t,{id:"detox-09",title:"No-Phone Meal",description:"Have one meal without scrolling or watching entertainment on a screen.",emoji:"🍽️",category:"Phone Detox",difficulty:"Medium",rarity:"Rare",durationMinutes:20,timeWindow:"Anytime",actionType:"Toggle",xpReward:90,coinsReward:18,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Be where you are.",cognitiveLoad:2},theme:"Sunset"}),
 m(t,{id:"detox-10",title:"Notification Audit",description:"Review your notifications and keep only the alerts that genuinely matter.",emoji:"🔔",category:"Phone Detox",difficulty:"Medium",rarity:"Uncommon",durationMinutes:15,timeWindow:"Anytime",actionType:"Toggle",xpReward:65,coinsReward:12,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Not every ping deserves attention.",cognitiveLoad:2},theme:"Neon"}),
 m(t,{id:"productivity-06",title:"Two-Minute Sort",description:"Sort your task list into now, later, and ignore so the next action is obvious.",emoji:"🗃️",category:"Productivity",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Morning",actionType:"Reflection",xpReward:45,coinsReward:8,psychologicalProfile:{dopamineYield:"Low",flavorText:"Order creates speed.",cognitiveLoad:2},theme:"Ocean"}),
 m(t,{id:"productivity-07",title:"Batch Similar",description:"Group similar small tasks together and finish them in one focused pass.",emoji:"📦",category:"Productivity",difficulty:"Medium",rarity:"Uncommon",durationMinutes:25,timeWindow:"Anytime",actionType:"Timer",xpReward:100,coinsReward:20,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Reduce context switching.",cognitiveLoad:3},theme:"Galaxy"}),
 m(t,{id:"productivity-08",title:"Start With Output",description:"Define what finished looks like before beginning the task.",emoji:"🏁",category:"Productivity",difficulty:"Easy",rarity:"Uncommon",durationMinutes:10,timeWindow:"Anytime",actionType:"Reflection",xpReward:50,coinsReward:9,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Outputs create direction.",cognitiveLoad:2},theme:"Royal"}),
 m(t,{id:"productivity-09",title:"Clean Queue",description:"Remove one stale task from your list that no longer deserves attention.",emoji:"🧽",category:"Productivity",difficulty:"Easy",rarity:"Common",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:35,coinsReward:6,psychologicalProfile:{dopamineYield:"Low",flavorText:"Less clutter, more capacity.",cognitiveLoad:1},theme:"Ice"}),
 m(t,{id:"productivity-10",title:"Power Block",description:"Reserve one uninterrupted block for the highest-value project you have this week.",emoji:"⚙️",category:"Productivity",difficulty:"Hard",rarity:"Legendary",durationMinutes:60,timeWindow:"Anytime",actionType:"Timer",xpReward:400,coinsReward:100,psychologicalProfile:{dopamineYield:"High",flavorText:"Protect the work that matters.",cognitiveLoad:5},theme:"Volcano",requirements:{minLevel:2}}),
 m(t,{id:"discipline-06",title:"No Negotiation",description:"Choose a tiny useful action and do it immediately without debating whether to start.",emoji:"⚔️",category:"Discipline",difficulty:"Medium",rarity:"Rare",durationMinutes:10,timeWindow:"Anytime",actionType:"Toggle",xpReward:65,coinsReward:12,psychologicalProfile:{dopamineYield:"Medium",flavorText:"Decide once.",cognitiveLoad:2},theme:"Royal"}),
 m(t,{id:"discipline-07",title:"Break Boundary",description:"Take the planned break, then return when it ends instead of extending it.",emoji:"⏸️",category:"Discipline",difficulty:"Medium",rarity:"Uncommon",durationMinutes:20,timeWindow:"Anytime",actionType:"Timer",xpReward:80,coinsReward:15,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Rest with boundaries.",cognitiveLoad:2},theme:"Forest"}),
 m(t,{id:"discipline-08",title:"Finish Before Feed",description:"Complete your chosen task before opening entertainment for the first time today.",emoji:"🚧",category:"Discipline",difficulty:"Hard",rarity:"Epic",durationMinutes:45,timeWindow:"Morning",actionType:"ZenMode",xpReward:230,coinsReward:50,psychologicalProfile:{dopamineYield:"Reset",flavorText:"Earn the reward.",cognitiveLoad:4},theme:"Void"}),
 m(t,{id:"discipline-09",title:"Daily Standard",description:"Complete one small action that matches the standard you want to keep every day.",emoji:"📏",category:"Discipline",difficulty:"Medium",rarity:"Rare",durationMinutes:15,timeWindow:"Anytime",actionType:"Timer",xpReward:90,coinsReward:18,psychologicalProfile:{dopamineYield:"Low",flavorText:"Standards beat moods.",cognitiveLoad:3},theme:"Neon"}),
];
