import type { OutstandChallenge, ChallengeId } from "./challenges.types";
import { CHALLENGE_THEMES } from "./challenges.data";

const id = (value: string) => value as ChallengeId;

const tenMinute = (
  data: Omit<OutstandChallenge, "id" | "durationMinutes"> & { id: string },
): OutstandChallenge => ({
  ...data,
  id: id(data.id),
  durationMinutes: 10,
});

/**
 * Outcome-driven 10-minute missions.
 * Each mission has one observable action, a clear finish line and a useful
 * transfer into the user's next hour. Avoids vague motivation-only tasks.
 */
export const OUTSTAND_10M_CHALLENGES: OutstandChallenge[] = [
  // MINDSET — emotional reset, confidence through evidence, and clarity.
  tenMinute({
    id: "10m-reset-and-restart",
    title: "Reset & Restart",
    description: "Leave the screen for a moment. Take a comfortable walk, slow your breathing, drink some water, then return and choose one useful next action.",
    emoji: "🌊",
    category: "Mindset",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 45,
    coinsReward: 8,
    psychologicalProfile: { dopamineYield: "Reset", flavorText: "Change your state before demanding more from your brain.", cognitiveLoad: 1 },
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onStart: "chime", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-evidence-of-progress",
    title: "Evidence of Progress",
    description: "Write three things you handled well recently, one thing you learned, and one tiny action that would make tomorrow easier. Finish by doing that action if it takes less than two minutes.",
    emoji: "🏆",
    category: "Mindset",
    difficulty: "Easy",
    rarity: "Uncommon",
    timeWindow: "Evening",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Build confidence from evidence, not empty hype.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onStart: "chime", onComplete: "ethereal_ping" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-control-the-next-step",
    title: "Control the Next Step",
    description: "Write the problem currently bothering you. Split it into: what I can control, what I cannot control, and one action I can take today. Spend the remaining time on that action.",
    emoji: "🧭",
    category: "Mindset",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 12,
    psychologicalProfile: { dopamineYield: "Reset", flavorText: "Turn vague pressure into a concrete next move.", cognitiveLoad: 3 },
    theme: CHALLENGE_THEMES.Ice,
    audio: { onStart: "deep_hum", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),

  // SOCIAL — real-world confidence reps, not performative dares.
  tenMinute({
    id: "10m-confidence-conversation",
    title: "Confidence Conversation",
    description: "Have one genuine 5–10 minute conversation. Ask one open question, listen fully, and contribute one thought of your own. The goal is participation, not impressing anyone.",
    emoji: "🤝",
    category: "Social",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 65,
    coinsReward: 14,
    psychologicalProfile: { dopamineYield: "High", flavorText: "Confidence grows through small, repeatable social reps.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Neon,
    audio: { onStart: "chime", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-speak-your-idea",
    title: "Speak Your Idea",
    description: "Pick one idea you understand and explain it out loud for three minutes. Then repeat it in one clear sentence. Notice one place where you hesitated and try it again.",
    emoji: "🗣️",
    category: "Social",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 12,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Clear communication is a skill you can rehearse.", cognitiveLoad: 3 },
    theme: CHALLENGE_THEMES.Royal,
    audio: { onStart: "chime", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-appreciation-rep",
    title: "Appreciation Rep",
    description: "Give one sincere, specific thank-you to someone who helped you. Say what they did and why it mattered. No generic compliment—make it real.",
    emoji: "✨",
    category: "Social",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 45,
    coinsReward: 8,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Positive social action can be small and still meaningful.", cognitiveLoad: 1 },
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onStart: "chime", onComplete: "ethereal_ping" },
    haptics: { onStart: "light", onComplete: "success" },
  }),

  // FITNESS — short, sustainable movement; never an exhaustion contest.
  tenMinute({
    id: "10m-brisk-walk",
    title: "Brisk Walk Reset",
    description: "Take a comfortable brisk walk for ten minutes. Keep it sustainable—finish feeling more awake, not exhausted. Return and notice how your energy changed.",
    emoji: "🚶",
    category: "Fitness",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Movement can be a fast state change without becoming a workout battle.", cognitiveLoad: 1 },
    theme: CHALLENGE_THEMES.Forest,
    audio: { onStart: "chime", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-mobility-reset",
    title: "Mobility Reset",
    description: "Spend ten minutes moving comfortably through your shoulders, neck, hips and ankles. Use gentle range of motion and stop if anything hurts.",
    emoji: "🧘",
    category: "Fitness",
    difficulty: "Easy",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "Move to feel better, not to prove something.", cognitiveLoad: 1 },
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onStart: "deep_hum", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-energy-circuit",
    title: "Energy Circuit",
    description: "For ten minutes, alternate comfortable movement with short rests: easy squats or sit-to-stands, marching, and light stretching. Keep the effort moderate and controlled.",
    emoji: "⚡",
    category: "Fitness",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 12,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "A short movement break can support energy and attention.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Forest,
    audio: { onStart: "chime", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),

  // KNOWLEDGE — retrieval and explanation, not passive rereading.
  tenMinute({
    id: "10m-active-recall",
    title: "Active Recall Sprint",
    description: "Choose one topic. Close your notes and write everything you can remember for five minutes. Open your notes, mark the gaps, then recall those gaps once more.",
    emoji: "🧠",
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 70,
    coinsReward: 15,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Retrieval makes learning active instead of familiar-looking.", cognitiveLoad: 4 },
    theme: CHALLENGE_THEMES.Galaxy,
    audio: { onStart: "digital_boot", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-feynman-explain",
    title: "Teach It Simply",
    description: "Pick one concept and explain it aloud as if teaching a younger student. Whenever you use a vague phrase, stop, check the concept, and explain that part more clearly.",
    emoji: "🔎",
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 70,
    coinsReward: 15,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Explanation exposes gaps that rereading can hide.", cognitiveLoad: 4 },
    theme: CHALLENGE_THEMES.Royal,
    audio: { onStart: "chime", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-error-correction",
    title: "Fix One Mistake",
    description: "Take one question you previously got wrong. Solve it again without looking at the answer, identify the exact mistake, then write the rule or idea that prevents it next time.",
    emoji: "🛠️",
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 65,
    coinsReward: 14,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Turn an error into a reusable rule.", cognitiveLoad: 4 },
    theme: CHALLENGE_THEMES.Ice,
    audio: { onStart: "digital_boot", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),

  // FOCUS — create a clean start, then do real work.
  tenMinute({
    id: "10m-single-task-start",
    title: "Single-Task Start",
    description: "Choose the most useful task available. Put the phone away, close unrelated tabs, and work on only the first meaningful step for ten uninterrupted minutes.",
    emoji: "🎯",
    category: "Focus",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 65,
    coinsReward: 14,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "The win is starting without switching.", cognitiveLoad: 4 },
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onStart: "deep_hum", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-distraction-free-read",
    title: "Deep Read",
    description: "Read one page or short section of something that matters to your current goal. No music switching, messages, or multitasking. Finish by stating the main idea in one sentence.",
    emoji: "📖",
    category: "Focus",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "Train attention by staying with one thing.", cognitiveLoad: 3 },
    theme: CHALLENGE_THEMES.Ice,
    audio: { onStart: "deep_hum", onComplete: "ethereal_ping" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-start-the-hard-part",
    title: "Start the Hard Part",
    description: "Find the part of today's important task you have been avoiding. Spend ten minutes making the first concrete attempt—one problem, one paragraph, one example, or one draft.",
    emoji: "🚀",
    category: "Focus",
    difficulty: "Hard",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 75,
    coinsReward: 16,
    psychologicalProfile: { dopamineYield: "Surge", flavorText: "Momentum often appears after the first uncomfortable step.", cognitiveLoad: 5 },
    theme: CHALLENGE_THEMES.Neon,
    audio: { onStart: "digital_boot", onComplete: "level_up" },
    haptics: { onStart: "medium", onComplete: "success" },
  }),

  // DISCIPLINE — reduce automatic behavior and increase intentional choice.
  tenMinute({
    id: "10m-phone-out-of-reach",
    title: "Phone Out of Reach",
    description: "Put the phone somewhere you cannot casually grab it. For ten minutes, do the activity you intended to do before opening an entertainment app.",
    emoji: "📵",
    category: "Discipline",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 65,
    coinsReward: 14,
    psychologicalProfile: { dopamineYield: "Reset", flavorText: "Make the good choice easier by changing the environment.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Forest,
    audio: { onStart: "chime", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-delay-the-scroll",
    title: "Delay the Scroll",
    description: "When you feel the urge to open a distracting app, pause for ten minutes and do a chosen alternative first: walk, read, stretch, tidy, or work on one task.",
    emoji: "⏳",
    category: "Discipline",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 12,
    psychologicalProfile: { dopamineYield: "Reset", flavorText: "A pause creates room for a deliberate choice.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Void,
    audio: { onStart: "deep_hum", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-one-rule",
    title: "One Rule, Ten Minutes",
    description: "Choose one rule for the next ten minutes: no phone, no switching tabs, no unnecessary snacking, or no procrastination. Follow only that one rule until the timer ends.",
    emoji: "🛡️",
    category: "Discipline",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "Practice consistency with one clear boundary, not ten rules.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Royal,
    audio: { onStart: "chime", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),

  // PRODUCTIVITY — concrete outputs that reduce friction for the next action.
  tenMinute({
    id: "10m-next-action",
    title: "Define the Next Action",
    description: "Choose one goal and turn it into a physical action that can be started immediately. Write it as a verb + object, then spend the rest of the timer starting it.",
    emoji: "➡️",
    category: "Productivity",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 55,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "Vague goals become easier when the next action is visible.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onStart: "chime", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-environment-reset",
    title: "Build Your Launchpad",
    description: "Prepare the space for the next important activity: clear the working surface, collect what you need, remove one distraction, and leave the first item ready to use.",
    emoji: "🧩",
    category: "Productivity",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 45,
    coinsReward: 8,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "Lower tomorrow's friction today.", cognitiveLoad: 1 },
    theme: CHALLENGE_THEMES.Ice,
    audio: { onStart: "chime", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-plan-tomorrow",
    title: "Tomorrow in Three Moves",
    description: "Write the three most important actions for tomorrow in order. Put the first one at a realistic time or trigger, then prepare anything needed to start it.",
    emoji: "🗺️",
    category: "Productivity",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Evening",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 12,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "A simple first move beats a perfect schedule.", cognitiveLoad: 3 },
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onStart: "digital_boot", onComplete: "ethereal_ping" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
];

export const OUTSTAND_10M_CATEGORIES = [
  { key: "Mindset", label: "Mood & mindset", icon: "◌", description: "Reset your state, build self-trust, and turn pressure into a next step." },
  { key: "Social", label: "Confidence", icon: "↗", description: "Real-world conversation and communication reps that build confidence." },
  { key: "Fitness", label: "Physical", icon: "＋", description: "Short, sustainable movement that can improve energy and attention." },
  { key: "Knowledge", label: "Thinking", icon: "◇", description: "Recall, explain, correct mistakes, and make learning active." },
  { key: "Focus", label: "Focus", icon: "◎", description: "Start meaningful work without switching or waiting for motivation." },
  { key: "Discipline", label: "Self-control", icon: "—", description: "Practice one deliberate boundary instead of fighting every distraction." },
  { key: "Productivity", label: "Execution", icon: "□", description: "Turn vague intentions into concrete actions and lower future friction." },
] as const;
