import type { OutstandChallenge, ChallengeId } from "./challenges.types";
import { CHALLENGE_THEMES } from "./challenges.data";

const id = (value: string) => value as ChallengeId;

const tenMinute = (
  data: Omit<OutstandChallenge, "id" | "durationMinutes"> & { id: string },
): OutstandChallenge => ({
  ...data,
  id: id(data.id),
  durationMinutes: 10,
});

export const OUTSTAND_10M_CHALLENGES: OutstandChallenge[] = [
  tenMinute({
    id: "10m-mood-reset",
    title: "Mood Reset",
    description: "Step away from the screen, breathe slowly, drink some water, and give your mind ten quiet minutes before your next decision.",
    emoji: "🌊",
    category: "Mindset",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 45,
    coinsReward: 8,
    psychologicalProfile: { dopamineYield: "Reset", flavorText: "Create a little space before you act.", cognitiveLoad: 1 },
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onStart: "chime", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-confidence-rep",
    title: "Confidence Rep",
    description: "Do one small positive social action: ask a useful question, thank someone, explain an idea, or start a friendly conversation.",
    emoji: "🤝",
    category: "Social",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 12,
    psychologicalProfile: { dopamineYield: "High", flavorText: "Confidence is built through small reps.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Neon,
    audio: { onStart: "chime", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-movement-reset",
    title: "Move & Reset",
    description: "Spend ten minutes walking, stretching, or doing comfortable bodyweight movement. Finish feeling more awake, not exhausted.",
    emoji: "⚡",
    category: "Fitness",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "A short movement break can restart the session.", cognitiveLoad: 1 },
    theme: CHALLENGE_THEMES.Forest,
    audio: { onStart: "chime", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-thought-dump",
    title: "Clear the Noise",
    description: "Write everything currently competing for your attention. Circle one thing that actually deserves action today.",
    emoji: "🧠",
    category: "Mindset",
    difficulty: "Easy",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 55,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Reset", flavorText: "Clarity starts by getting the noise out of your head.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Ice,
    audio: { onStart: "deep_hum", onComplete: "ethereal_ping" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-recall-sprint",
    title: "Recall Sprint",
    description: "Close your notes and recall one topic from memory. Then check your notes and write down the two gaps you missed.",
    emoji: "🔎",
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 65,
    coinsReward: 14,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Retrieval turns information into usable knowledge.", cognitiveLoad: 4 },
    theme: CHALLENGE_THEMES.Galaxy,
    audio: { onStart: "digital_boot", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-deep-start",
    title: "Deep Start",
    description: "Pick one important task and work on only the first meaningful step for ten uninterrupted minutes. No switching.",
    emoji: "🎯",
    category: "Focus",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 60,
    coinsReward: 12,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "Starting clean is often the hardest part.", cognitiveLoad: 4 },
    theme: CHALLENGE_THEMES.Ocean,
    audio: { onStart: "deep_hum", onComplete: "success_chime" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-screen-boundary",
    title: "Screen Boundary",
    description: "Put entertainment apps and notifications out of reach. Use the ten minutes for something you chose before opening your phone.",
    emoji: "📵",
    category: "Discipline",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 65,
    coinsReward: 14,
    psychologicalProfile: { dopamineYield: "Reset", flavorText: "Protect the next ten minutes from automatic scrolling.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Forest,
    audio: { onStart: "chime", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-space-reset",
    title: "Reset Your Space",
    description: "Clear the surface around you, put away obvious distractions, and prepare one clean place for your next task.",
    emoji: "✨",
    category: "Productivity",
    difficulty: "Easy",
    rarity: "Common",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 45,
    coinsReward: 8,
    psychologicalProfile: { dopamineYield: "Low", flavorText: "Make the next useful action easier to start.", cognitiveLoad: 1 },
    theme: CHALLENGE_THEMES.Ice,
    audio: { onComplete: "success_chime" },
    haptics: { onComplete: "success" },
  }),
  tenMinute({
    id: "10m-explain-it",
    title: "Explain It",
    description: "Teach one concept out loud as if you were helping a younger student. Notice where your explanation becomes unclear.",
    emoji: "🗣️",
    category: "Knowledge",
    difficulty: "Medium",
    rarity: "Rare",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 65,
    coinsReward: 14,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "If you can explain it simply, you probably understand it better.", cognitiveLoad: 4 },
    theme: CHALLENGE_THEMES.Royal,
    audio: { onStart: "chime", onComplete: "level_up" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-idea-burst",
    title: "Idea Burst",
    description: "Generate ten ideas for improving a project, solving a problem, or making tomorrow easier. Judge them only after minute ten.",
    emoji: "💡",
    category: "Focus",
    difficulty: "Medium",
    rarity: "Uncommon",
    timeWindow: "Anytime",
    actionType: "Timer",
    xpReward: 55,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Quantity first. Better ideas often appear after the obvious ones.", cognitiveLoad: 3 },
    theme: CHALLENGE_THEMES.Neon,
    audio: { onStart: "digital_boot", onComplete: "ethereal_ping" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
  tenMinute({
    id: "10m-three-wins",
    title: "Three Wins",
    description: "Write three things you handled well recently, one thing you learned, and one small action you want to repeat tomorrow.",
    emoji: "🏆",
    category: "Mindset",
    difficulty: "Easy",
    rarity: "Uncommon",
    timeWindow: "Evening",
    actionType: "Timer",
    xpReward: 50,
    coinsReward: 10,
    psychologicalProfile: { dopamineYield: "Medium", flavorText: "Notice progress without pretending everything is perfect.", cognitiveLoad: 2 },
    theme: CHALLENGE_THEMES.Sunset,
    audio: { onStart: "chime", onComplete: "ethereal_ping" },
    haptics: { onStart: "light", onComplete: "success" },
  }),
];

export const OUTSTAND_10M_CATEGORIES = [
  { key: "Mindset", label: "Mood & mindset", icon: "◌", description: "Reset attention and build a calmer next move." },
  { key: "Social", label: "Confidence", icon: "↗", description: "Small real-world reps that make action easier." },
  { key: "Fitness", label: "Physical", icon: "＋", description: "Short movement breaks for energy and momentum." },
  { key: "Knowledge", label: "Thinking", icon: "◇", description: "Recall, explain, solve, and sharpen your thinking." },
  { key: "Focus", label: "Focus", icon: "◎", description: "Start one meaningful task without switching." },
  { key: "Discipline", label: "Self-control", icon: "—", description: "Protect ten minutes from automatic distractions." },
  { key: "Productivity", label: "Environment", icon: "□", description: "Make your next useful action easier to begin." },
] as const;
