import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";

export const Route = createFileRoute("/comeback")({ component: ComebackPage });

const days = ["Reset your desk and prepare tomorrow's books.","Use calm posture: shoulders relaxed, chin neutral.","Give one genuine compliment or thank-you.","Take a 10-minute screen-free walk.","Clean your shoes and school bag.","Practice listening without interrupting.","Do a complete room reset.","Review your week and remove one unnecessary distraction.","Speak slightly slower and more clearly today.","Keep hair and grooming simple and consistent.","Prepare tomorrow's clothes and school materials.","Practice 2 minutes of calm breathing.","Declutter your phone home screen.","Do one helpful thing without announcing it.","Reset your study space for tomorrow.","Have a screen-free wind-down before bed.","Notice one habit that makes you more confident.","Take a relaxed walk and check your posture.","Prepare exam and chess materials tonight.","Full hygiene + room reset; protect bedtime.","Write the 3 habits you will keep after Day 21."];
const timetable = [["6:00","Wake","Water, wash, make bed. No scrolling."],["6:20","Movement","Walk/stretch and get ready."],["7:00","Breakfast","Eat, pack, leave on time."],["School","School","Listen actively; use spare time for light recall."],["After school","Recovery","Lunch + 25 minutes. Don't fall into a scrolling spiral."],["3:00","Study A","Hardest subject: 50/10 × 2."],["5:00","Reset","Snack, water, short walk."],["5:20","Study B","Second subject: 50/10 × 2."],["7:20","Exercise","20–30 minutes, then shower."],["8:00","Dinner","Family time; phone away from table."],["8:45","Chess","15 tactics + 25 game + 20 analysis."],["9:50","Study C","Practice/recall: 50 minutes."],["10:45","Shutdown","Journal, prep tomorrow, phone away."],["11:00","Sleep","Protect an 8–10 hour sleep window."]];
const focus = [["Start tiny","Commit to 5 minutes. Starting is the hardest part."],["One screen, one task","Keep only the material needed for the current task."],["Park distractions","Write distracting thoughts on paper and return to work."],["Break without scrolling","Stand, stretch, walk, breathe, or drink water."],["Restart cue","Before stopping, write the exact first action for next time."]];
const study = [["Blurting","Close the book and write what you remember before checking."],["Feynman","Explain the idea simply, then find the gap in your explanation."],["Interleave","Mix question types so you learn when to use each method."],["Error log","Record the mistake, cause, correction, and prevention rule."],["Timed recall","Practice retrieving under a short timer instead of rereading."]];
const influence = [["Listen first","People feel respected when you genuinely understand them. Ask thoughtful questions."],["Be reliable","Do what you said you would do. Consistency builds more influence than trying to look powerful."],["Speak clearly","Use short sentences, calm volume, and purposeful pauses. Don't rush."],["Respect boundaries","Influence is not control. Never pressure, manipulate, threaten, or exploit someone."],["Create value","Help, teach, encourage, organize, or solve problems. Useful people naturally gain trust."],["Stay composed","When someone disagrees, pause and respond to the idea rather than reacting emotionally."]];
const presence = [["Sit","Feet supported, back comfortably upright, shoulders relaxed, head balanced. Don't force a rigid pose."],["Stand","Feet roughly hip-width, weight balanced, shoulders relaxed, eyes level."],["Walk","Look where you're going, take natural steps, arms relaxed, steady pace."],["Eye contact","Look at the person naturally, then look away normally. Don't stare."],["Conversation","Face the speaker, listen, don't constantly check your phone, and let others finish."],["Confidence","Aim for calm and comfortable, not intimidating. Confidence grows from competence and kindness."]];
const exercise = { A:["5 min warm-up","Squats 2×10–15","Push-ups 2×5–12","Lunges 2×8/side","Plank 2×20–40 sec"], B:["5 min warm-up","Easy walk 15–20 min","Calf raises 2×12–15","Gentle mobility 5 min"], C:["5 min warm-up","Squats 2×10–15","Push-ups 2×5–12","Safe backpack rows 2×10–15","Plank 2×20–40 sec"] };
const checklist = [["study","Focused study"],["chess","Chess training"],["move","Exercise / movement"],["phone","Phone stayed near target"],["sleep","Protected sleep"],["glow","Completed today's 1% upgrade"],["presence","Practiced calm presence / communication"]];
function Section({title,eyebrow,children}:{title:string;eyebrow?:string;children:ReactNode}){return <section className="rounded-[2rem] border border-white/10 bg-[#07101d]/90 p-5 shadow-[0_24px_80px_-55px_rgba(34,211,238,.18)] sm:p-7">{eyebrow&&<div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-200/70">{eyebrow}</div>}<h2 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">{title}</h2><div className="mt-5">{children}</div></section>}
function ComebackPage(){
 const [day,setDay]=useState(1); const [checks,setChecks]=useState<Record<string,boolean>>({}); const [notes,setNotes]=useState(""); const [focusMinutes,setFocusMinutes]=useState(0);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("outstand-comeback-v4")||"{}");setDay(s.day||1);setChecks(s.checks||{});setNotes(s.notes||"");setFocusMinutes(s.focusMinutes||0)}catch{}},[]);
 useEffect(()=>{localStorage.setItem("outstand-comeback-v4",JSON.stringify({day,checks,notes,focusMinutes}))},[day,checks,notes,focusMinutes]);
 const completed=useMemo(()=>Object.values(checks).filter(Boolean).length,[checks]); const progress=Math.round(completed/checklist.length*100); const glow=days[day-1]; const workout=exercise[day%3===1?"A":day%3===2?"B":"C"]; const phoneTarget=day<=3?"≤ 8 h":day<=7?"≤ 6 h":day<=14?"≤ 4.5–5 h":"~3–4 h"; const toggle=(id:string)=>setChecks(x=>({...x,[id]:!x[id]}));
 return <main className="min-h-screen bg-[#050812] px-4 pb-24 pt-6 text-slate-100 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl space-y-5 sm:space-y-7">
 <header className="overflow-hidden rounded-[2rem] border border-cyan-300/15 bg-gradient-to-br from-[#0a1a2a] via-[#07101d] to-[#0b0b19] p-6 shadow-[0_30px_100px_-60px_rgba(34,211,238,.35)] sm:p-10"><div className="flex flex-wrap justify-between gap-3"><span className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-[10px] font-black uppercase tracking-[.18em] text-cyan-100">OUTSTAND / COMEBACK</span><span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">Direct route · /comeback</span></div><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_300px] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200/60">DAY {day} / 21</p><h1 className="mt-3 text-4xl font-black tracking-[-.06em] sm:text-6xl">THE COMEBACK<br/><span className="bg-gradient-to-r from-cyan-200 via-sky-300 to-violet-300 bg-clip-text text-transparent">STARTS NOW.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">A practical 21-day operating system for exams, chess, health, focus, confidence, communication, presence and daily self-respect.</p></div><div className="rounded-3xl border border-white/10 bg-black/20 p-5"><div className="flex items-end justify-between"><span className="text-xs font-black uppercase tracking-[.14em] text-slate-500">Today's execution</span><span className="text-3xl font-black text-cyan-100">{completed}/{checklist.length}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-300 transition-all" style={{width:`${progress}%`}}/></div><div className="mt-4 flex justify-between text-xs text-slate-500"><span>Focus trained</span><span className="font-black text-slate-300">{focusMinutes} min</span></div></div></div></header>
 <section className="rounded-[2rem] border border-cyan-300/10 bg-[#07101d]/90 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-200/70">Today's mission</div><h2 className="mt-2 text-2xl font-black">Day {day}: {glow}</h2><p className="mt-2 text-sm text-slate-500">Phone target: {phoneTarget}. Focus on execution, not perfection.</p></div><div className="flex gap-2"><button onClick={()=>setDay(d=>Math.max(1,d-1))} className="rounded-xl border border-white/10 px-4 py-2 text-xs font-black">←</button><button onClick={()=>setDay(d=>Math.min(21,d+1))} className="rounded-xl bg-gradient-to-r from-cyan-300 to-violet-300 px-4 py-2 text-xs font-black text-slate-950">Next day →</button></div></div></section>
 <Section eyebrow="Your actual routine" title="School-day timetable"><div className="grid gap-2">{timetable.map(([time,title,body])=><div key={time+title} className="grid gap-2 rounded-2xl border border-white/10 bg-white/[.02] p-4 sm:grid-cols-[90px_180px_1fr] sm:items-center"><span className="text-xs font-black text-cyan-200/70">{time}</span><span className="text-sm font-black">{title}</span><span className="text-sm leading-6 text-slate-500">{body}</span></div>)}</div></Section>
 <div className="grid gap-5 lg:grid-cols-2"><Section eyebrow="Study" title="Study tricks that actually work"><div className="grid gap-3">{study.map(([title,body])=><div key={title} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="font-black">{title}</div><p className="mt-1 text-sm leading-6 text-slate-500">{body}</p></div>)}</div><div className="mt-5 rounded-2xl border border-cyan-300/10 bg-cyan-300/[.035] p-4 text-sm text-slate-400"><b className="text-slate-200">Rule:</b> Learn → Recall → Practice → Test → Repair mistakes.</div></Section><Section eyebrow="Focus lab" title="Train your attention"><div className="grid gap-3">{focus.map(([title,body])=><div key={title} className="flex gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-4"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-cyan-200"/><div><div className="font-black">{title}</div><p className="mt-1 text-sm leading-6 text-slate-500">{body}</p></div></div>)}</div><div className="mt-5 flex flex-wrap items-center gap-2 rounded-2xl border border-cyan-300/10 p-4"><span className="mr-auto text-xs font-black uppercase tracking-[.14em] text-slate-500">Log focus</span><button onClick={()=>setFocusMinutes(m=>m+25)} className="rounded-xl bg-white/[.06] px-3 py-2 text-xs font-black">+25</button><button onClick={()=>setFocusMinutes(m=>m+50)} className="rounded-xl bg-white/[.06] px-3 py-2 text-xs font-black">+50</button><button onClick={()=>setFocusMinutes(0)} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-black text-slate-500">Reset</button></div></Section></div>
 <Section eyebrow="Daily guidance" title="Small things → big impact"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Make your bed immediately.","Carry water and drink regularly.","Keep your study desk ready before sleep.","Put the phone away when someone is speaking to you.","Say thank you specifically, not automatically.","Return things to their place after using them.","Do one useful task before entertainment.","Walk for a few minutes after long sitting.","Prepare tomorrow tonight.","Keep your room and school bag clean.","Speak kindly about people who aren't present.","When angry, pause before replying."].map(x=><div key={x} className="rounded-2xl border border-white/10 bg-white/[.025] p-4 text-sm font-bold text-slate-300">{x}</div>)}</div></Section>
 <div className="grid gap-5 lg:grid-cols-2"><Section eyebrow="Social intelligence" title="Influence without manipulation"><p className="mb-4 text-sm leading-6 text-slate-500">Skip “dark psychology” tricks. Real influence comes from trust, competence, emotional control, communication and respect for other people's choices.</p><div className="grid gap-3">{influence.map(([title,body])=><div key={title} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="font-black">{title}</div><p className="mt-1 text-sm leading-6 text-slate-500">{body}</p></div>)}</div></Section><Section eyebrow="Presence" title="How to sit, stand, walk & speak"><div className="grid gap-3">{presence.map(([title,body])=><div key={title} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="font-black">{title}</div><p className="mt-1 text-sm leading-6 text-slate-500">{body}</p></div>)}</div></Section></div>
 <div className="grid gap-5 lg:grid-cols-2"><Section eyebrow="Health" title="Today's movement"><div className="grid gap-2">{workout.map(x=><div key={x} className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-sm font-bold">{x}</div>)}</div><p className="mt-4 text-xs leading-5 text-slate-600">Keep exercise moderate and consistent. No crash diets or extreme training.</p></Section><Section eyebrow="Appearance" title="Healthy glow-up"><div className="grid gap-3 sm:grid-cols-2">{["Sleep consistently.","Shower and maintain basic hygiene.","Keep nails clean and tidy.","Wear clean, comfortable clothes.","Keep hair care simple and consistent.","Practice relaxed posture.","Eat balanced meals rather than crash dieting.","Keep your study and living space clean."].map(x=><div key={x} className="rounded-2xl border border-white/10 bg-white/[.025] p-4 text-sm font-bold">{x}</div>)}</div></Section></div>
 <Section eyebrow="Nightly journal" title="Close the day properly"><div className="grid gap-3 sm:grid-cols-3">{["What did I accomplish?","Where did I slip?","What is tomorrow's first move?"].map(x=><div key={x} className="rounded-2xl border border-white/10 bg-white/[.025] p-4 text-sm font-black">{x}</div>)}</div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write your honest 3-line review…" className="mt-4 min-h-32 w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-sm leading-6 outline-none placeholder:text-slate-700 focus:border-cyan-300/25"/><p className="mt-2 text-xs text-slate-600">Saved locally in this browser.</p></Section>
 <Section eyebrow="Command center" title="Today's seven promises"><div className="grid gap-3 sm:grid-cols-2">{checklist.map(([id,label])=><label key={id} className="flex cursor-pointer items-center gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-4"><input type="checkbox" checked={Boolean(checks[id])} onChange={()=>toggle(id)} className="h-5 w-5"/><span className={`text-sm font-bold ${checks[id]?"text-cyan-100 line-through opacity-60":"text-slate-300"}`}>{label}</span></label>)}</div><div className="mt-5 rounded-2xl border border-cyan-300/10 bg-cyan-300/[.04] p-4 text-sm text-slate-500">{progress===100?"DAY COMPLETE. You kept the promise. 🔥":"Don't chase a perfect day. Complete the next promise."}</div></Section>
 <footer className="rounded-[2rem] border border-cyan-300/15 bg-gradient-to-r from-cyan-300/[.08] via-sky-300/[.05] to-violet-300/[.08] p-7 text-center sm:p-10"><p className="text-2xl font-black sm:text-3xl">Build presence. Build competence. Build character.</p><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-slate-400">The goal isn't to control other people. It's to control your attention, actions and reactions — and become someone people can trust.</p></footer>
 </div></main>;
}
