import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";

export const Route = createFileRoute("/comeback")({ component: ComebackPage });

const phases = [
  { days: "Days 1–3", study: "4 h", chess: "45–60 min", exercise: "20–25 min", focus: "Restart gently. Build consistency." },
  { days: "Days 4–7", study: "5 h", chess: "60 min", exercise: "25–30 min", focus: "Increase focused work." },
  { days: "Days 8–14", study: "6 h", chess: "60–75 min", exercise: "30 min", focus: "Practice and sharpen weak areas." },
  { days: "Days 15–21", study: "6–7 h", chess: "60–90 min", exercise: "30 min", focus: "Test, revise, and perform." },
];
const checklist = [["study", "Focused study completed"], ["chess", "Chess training completed"], ["move", "Moved / exercised today"], ["phone", "Phone stayed under today's target"], ["sleep", "Protected sleep"], ["glow", "Completed today's 1% glow-up"]];
const focusRules = [["1", "Make starting tiny", "Commit to just 5 minutes. Once started, continue the block."], ["2", "One task only", "Keep only the exact book, notes, questions, or chess board needed."], ["3", "Park distractions", "Write distracting thoughts on paper instead of following them."], ["4", "Break without scrolling", "Stand, stretch, walk, or drink water during breaks."], ["5", "Leave a restart cue", "Write the exact first action for your next block before stopping."]];
const studyTricks = [["Blurting", "Close the book and write everything you can remember for 2–3 minutes."], ["Feynman", "Explain the concept in simple language as if teaching someone younger."], ["Interleaving", "Mix related question types instead of repeating one pattern."], ["Error log", "Record the mistake, why it happened, and the rule that prevents it next time."], ["Timed recall", "Set a short timer before checking notes to train retrieval under pressure."]];
const glowUpByDay = ["Reset your study desk and prepare tomorrow's books.", "Take a proper shower and wear clean, comfortable clothes.", "Clean your shoes and school bag.", "Take a 10-minute easy walk and practice relaxed posture.", "Trim and clean your nails; tidy grooming essentials.", "Wash/change your pillowcase and make your bed.", "Do a room reset: floor, desk, bag, laundry.", "Drink water regularly and eat balanced meals.", "Take a 15-minute screen-free walk outside.", "Keep your hair routine simple and consistent.", "Prepare tomorrow's school clothes tonight.", "Spend 10 minutes on calm breathing and posture awareness.", "Clean your phone screen and declutter the home screen.", "Prepare a healthy snack before a study block.", "Do a 20-minute room + study-space reset.", "Have an early screen-free wind-down.", "Review your grooming routine and simplify it.", "Take a relaxed walk and notice energy and mood.", "Prepare exam materials and chess gear for tomorrow.", "Do a full hygiene + room reset, then protect bedtime.", "Write three habits from the 21 days worth keeping."];
const timetable = [["6:00", "Wake + water + wash", "No phone. Make bed."], ["6:20", "Light movement", "Walk/stretch + get ready."], ["7:00", "Breakfast + school prep", "Pack bag and leave on time."], ["School", "School", "Use free periods for light recall when practical."], ["After school", "Lunch + 25 min recovery", "Eat, change, breathe. Avoid a scrolling spiral."], ["3:00", "Study A", "Hardest subject · 50/10 · 50/10."], ["5:00", "Break + snack", "Walk, water, reset."], ["5:20", "Study B", "Second subject · 50/10 · 50/10."], ["7:20", "Exercise + shower", "20–30 min movement, then freshen up."], ["8:00", "Dinner + family", "Keep the phone away from the table."], ["8:45", "Chess", "15 tactics + 25 serious game + 20 analysis."], ["9:50", "Study C", "Practice / recall · 50 min."], ["10:45", "Night review", "Journal, prep tomorrow, phone away."], ["11:00", "Sleep", "Protect a consistent 8–10 hour sleep window."]];
const exercises = { A: ["Warm-up 5 min", "Squats 2×10–15", "Push-ups 2×5–12", "Lunges 2×8/side", "Plank 2×20–40 sec"], B: ["Warm-up 5 min", "Easy walk 15–20 min", "Calf raises 2×12–15", "Gentle mobility 5 min"], C: ["Warm-up 5 min", "Squats 2×10–15", "Push-ups 2×5–12", "Safe backpack rows 2×10–15", "Plank 2×20–40 sec"] };
const chessRoutine = [["15 min", "Tactics", "Calculate before moving."], ["25 min", "Serious game", "Choose a meaningful time control."], ["20 min", "Analysis", "Find the first turning point and missed candidates."]];
const studyBlocks = [["Block 1", "Hardest subject", "50 min study · 10 min break · 50 min study"], ["Block 2", "Second subject", "50 min study · 10 min break · 50 min study"], ["Block 3", "Practice", "50 min study · 10 min break · 50 min study"], ["Block 4", "Revision", "30–50 min active recall + mistake repair"]];

function Section({ title, eyebrow, children }: { title: string; eyebrow?: string; children: React.ReactNode }) { return <section className="rounded-[2rem] border border-white/10 bg-[#07101d]/90 p-5 shadow-[0_24px_80px_-55px_rgba(34,211,238,.18)] sm:p-7">{eyebrow && <div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-200/70">{eyebrow}</div>}<h2 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">{title}</h2><div className="mt-5">{children}</div></section>; }

function ComebackPage() {
  const [checks, setChecks] = useState<Record<string, boolean>>({});
  const [notes, setNotes] = useState("");
  const [day, setDay] = useState(1);
  const [focusMinutes, setFocusMinutes] = useState(0);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("outstand-comeback-v2") || "{}"); setChecks(saved.checks || {}); setNotes(saved.notes || ""); setDay(saved.day || 1); setFocusMinutes(saved.focusMinutes || 0); } catch {} }, []);
  useEffect(() => { localStorage.setItem("outstand-comeback-v2", JSON.stringify({ checks, notes, day, focusMinutes })); }, [checks, notes, day, focusMinutes]);
  const completed = useMemo(() => Object.values(checks).filter(Boolean).length, [checks]);
  const progress = Math.round((completed / checklist.length) * 100);
  const phase = day <= 3 ? phases[0] : day <= 7 ? phases[1] : day <= 14 ? phases[2] : phases[3];
  const glow = glowUpByDay[day - 1] || glowUpByDay[0];
  const workout = exercises[day % 3 === 1 ? "A" : day % 3 === 2 ? "B" : "C"];
  const toggle = (id: string) => setChecks((current) => ({ ...current, [id]: !current[id] }));
  return <main className="min-h-screen overflow-hidden bg-[#050812] px-4 pb-24 pt-6 text-slate-100 sm:px-6 lg:px-8"><div aria-hidden="true" className="pointer-events-none fixed inset-0 -z-10 overflow-hidden bg-[#050812]"><div className="absolute left-[3%] top-[4%] h-80 w-80 rounded-full bg-cyan-300/[.05] blur-3xl" /><div className="absolute right-[4%] top-[18%] h-96 w-96 rounded-full bg-violet-400/[.045] blur-3xl" /><div className="absolute bottom-[5%] left-[35%] h-72 w-72 rounded-full bg-sky-400/[.025] blur-3xl" /></div><div className="relative mx-auto max-w-6xl space-y-5 sm:space-y-7">
    <header className="relative overflow-hidden rounded-[2rem] border border-cyan-300/15 bg-gradient-to-br from-[#0a1a2a] via-[#07101d] to-[#0b0b19] p-6 shadow-[0_30px_100px_-60px_rgba(34,211,238,.35)] sm:p-10"><div className="relative"><div className="flex flex-wrap items-center justify-between gap-3"><div className="inline-flex rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-[10px] font-black uppercase tracking-[.18em] text-cyan-100">OUTSTAND / COMEBACK</div><div className="rounded-full border border-white/10 bg-white/[.03] px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-slate-500">Direct route · /comeback</div></div><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_300px] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200/60">DAY {day} / 21</p><h1 className="mt-3 text-4xl font-black tracking-[-.06em] sm:text-6xl">THE COMEBACK<br /><span className="bg-gradient-to-r from-cyan-200 via-sky-300 to-violet-300 bg-clip-text text-transparent">STARTS NOW.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">A personal operating system for exams, chess, health, attention, confidence, and the small habits that make the bigger change sustainable.</p></div><div className="rounded-3xl border border-white/10 bg-black/20 p-5 backdrop-blur"><div className="flex items-end justify-between"><span className="text-xs font-black uppercase tracking-[.14em] text-slate-500">Today's execution</span><span className="text-3xl font-black text-cyan-100">{completed}/6</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-300 transition-all" style={{ width: `${progress}%` }} /></div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>Focus trained</span><span className="font-black text-slate-300">{focusMinutes} min</span></div></div></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{[["01", "No zero days"], ["02", "Never miss twice"], ["03", "Win the next block"]].map(([n, text]) => <div key={n} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><span className="text-[10px] font-black text-cyan-200/60">{n}</span><p className="mt-2 text-sm font-black">{text}</p></div>)}</div></div></header>
    <section className="rounded-[2rem] border border-cyan-300/10 bg-[#07101d]/90 p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-cyan-200/70">Today's load</div><h2 className="mt-2 text-2xl font-black">Day {day} · {phase.days}</h2><p className="mt-1 text-sm text-slate-500">{phase.focus}</p></div><div className="grid grid-cols-3 gap-2"><div className="rounded-2xl border border-white/10 bg-white/[.025] px-4 py-3 text-center"><div className="text-lg font-black">{phase.study}</div><div className="text-[9px] font-black uppercase tracking-[.12em] text-slate-600">Study</div></div><div className="rounded-2xl border border-white/10 bg-white/[.025] px-4 py-3 text-center"><div className="text-lg font-black">{phase.chess}</div><div className="text-[9px] font-black uppercase tracking-[.12em] text-slate-600">Chess</div></div><div className="rounded-2xl border border-white/10 bg-white/[.025] px-4 py-3 text-center"><div className="text-lg font-black">{phase.exercise}</div><div className="text-[9px] font-black uppercase tracking-[.12em] text-slate-600">Health</div></div></div></div><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={() => setDay((d) => Math.min(21, d + 1))} className="rounded-xl bg-gradient-to-r from-cyan-300 to-violet-300 px-4 py-2.5 text-xs font-black text-slate-950">Next day →</button><button type="button" onClick={() => setDay((d) => Math.max(1, d - 1))} className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-2.5 text-xs font-black text-slate-300">← Previous</button><button type="button" onClick={() => setChecks({})} className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-2.5 text-xs font-black text-slate-500">Reset checklist</button></div></section>
    <Section eyebrow="Your actual timetable" title="School-day schedule"><div className="grid gap-2">{timetable.map(([time, title, body]) => <div key={`${time}-${title}`} className="grid gap-2 rounded-2xl border border-white/10 bg-white/[.02] p-4 sm:grid-cols-[90px_180px_1fr] sm:items-center"><span className="text-xs font-black text-cyan-200/70">{time}</span><span className="text-sm font-black">{title}</span><span className="text-sm leading-6 text-slate-500">{body}</span></div>)}</div><p className="mt-4 text-xs leading-5 text-slate-600">Move the blocks around your actual school timing when needed, but protect sleep and keep the sequence intact.</p></Section>
    <div className="grid gap-5 lg:grid-cols-2"><Section eyebrow="Focus lab" title="How to increase focus"><div className="grid gap-3">{focusRules.map(([n, title, body]) => <div key={n} className="flex gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-4"><span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-cyan-300/15 bg-cyan-300/[.06] text-[10px] font-black text-cyan-100">{n}</span><div><div className="text-sm font-black">{title}</div><p className="mt-1 text-sm leading-6 text-slate-500">{body}</p></div></div>)}</div><div className="mt-5 rounded-2xl border border-cyan-300/10 bg-cyan-300/[.035] p-4"><div className="text-[10px] font-black uppercase tracking-[.14em] text-cyan-200/70">Focus log</div><div className="mt-2 flex flex-wrap items-center gap-2"><button type="button" onClick={() => setFocusMinutes((m) => m + 25)} className="rounded-xl bg-white/[.06] px-3 py-2 text-xs font-black">+25 min</button><button type="button" onClick={() => setFocusMinutes((m) => m + 50)} className="rounded-xl bg-white/[.06] px-3 py-2 text-xs font-black">+50 min</button><button type="button" onClick={() => setFocusMinutes(0)} className="rounded-xl bg-white/[.03] px-3 py-2 text-xs font-black text-slate-500">Reset</button><span className="ml-1 text-xs text-slate-500">Total: <strong className="text-slate-300">{focusMinutes} min</strong></span></div></div></Section><Section eyebrow="Study tricks" title="Make each hour count"><div className="grid gap-3">{studyTricks.map(([title, body]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="text-sm font-black">{title}</div><p className="mt-1 text-sm leading-6 text-slate-500">{body}</p></div>)}</div></Section></div>
    <Section eyebrow="Academics" title="Exam engine"><div className="rounded-2xl border border-cyan-300/10 bg-cyan-300/[.035] p-4 text-sm leading-6 text-slate-400"><span className="font-black text-slate-200">Learn → Recall → Practice → Test.</span> A chapter is not finished because you read it. It is finished when you can retrieve and apply it without the book.</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{studyBlocks.map(([name, focus, body]) => <div key={name} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="text-[10px] font-black uppercase tracking-[.14em] text-cyan-200/70">{name}</div><div className="mt-2 font-black">{focus}</div><p className="mt-2 text-sm text-slate-400">{body}</p></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Days 1–7: COVER", "Days 8–14: PRACTICE", "Days 15–21: TEST + REVISE"].map((item) => <div key={item} className="rounded-2xl border border-white/10 bg-white/[.02] p-4 text-sm font-black">{item}</div>)}</div></Section>
    <div className="grid gap-5 lg:grid-cols-2"><Section eyebrow="Chess" title="Chess training"><div className="grid gap-3">{chessRoutine.map(([time, title, body]) => <div key={time} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="text-[10px] font-black uppercase tracking-[.14em] text-violet-200/70">{time}</div><div className="mt-2 font-black">{title}</div><p className="mt-2 text-sm leading-6 text-slate-400">{body}</p></div>)}</div></Section><Section eyebrow="Exercise" title="Today's workout"><div className="rounded-2xl border border-cyan-300/10 bg-cyan-300/[.035] p-4"><ul className="space-y-2">{workout.map((item) => <li key={item} className="text-sm text-slate-400">• {item}</li>)}</ul></div><p className="mt-4 text-xs leading-5 text-slate-600">Keep effort moderate and technique controlled. No extreme training. Stop if an exercise causes pain.</p></Section></div>
    <Section eyebrow="Glow-up" title="Healthy 1% appearance upgrade"><div className="rounded-2xl border border-cyan-300/10 bg-cyan-300/[.035] p-5"><div className="text-[10px] font-black uppercase tracking-[.15em] text-cyan-200/70">DAY {day} MISSION</div><p className="mt-2 text-base font-black leading-7">{glow}</p><p className="mt-2 text-xs leading-5 text-slate-600">The goal is a healthier, cleaner, more confident version of you — not an extreme body or appearance change.</p></div></Section>
    <Section eyebrow="Daily journal" title="2-minute nightly review"><div className="grid gap-3 sm:grid-cols-3">{[["WIN", "What did I accomplish?"], ["LESSON", "Where did I slip, and why?"], ["NEXT", "What is tomorrow's first move?"]].map(([label, question]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="text-[10px] font-black uppercase tracking-[.12em] text-cyan-200/70">{label}</div><p className="mt-2 text-sm text-slate-400">{question}</p></div>)}</div><textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Write honestly. No essay needed…" className="mt-4 min-h-32 w-full resize-y rounded-2xl border border-white/10 bg-black/20 p-4 text-sm leading-6 text-slate-200 outline-none placeholder:text-slate-700 focus:border-cyan-300/25" /><p className="mt-3 text-xs text-slate-600">Saved locally in this browser.</p></Section>
    <Section eyebrow="Daily command center" title="Today's six promises"><div className="grid gap-3 sm:grid-cols-2">{checklist.map(([id, label]) => <label key={id} className="flex cursor-pointer items-center gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-4 transition hover:border-cyan-300/20"><input type="checkbox" checked={Boolean(checks[id])} onChange={() => toggle(id)} className="h-5 w-5 rounded border-white/20 bg-black/20" /><span className={`text-sm font-bold ${checks[id] ? "text-cyan-100 line-through opacity-70" : "text-slate-300"}`}>{label}</span></label>)}</div><div className="mt-5 rounded-2xl border border-cyan-300/10 bg-cyan-300/[.04] p-4"><div className="flex items-center justify-between gap-4"><span className="text-sm font-black">Today's execution</span><span className="text-sm font-black text-cyan-100">{completed}/6</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-300 transition-all" style={{ width: `${progress}%` }} /></div></div></Section>
    <footer className="rounded-[2rem] border border-cyan-300/15 bg-gradient-to-r from-cyan-300/[.08] via-sky-300/[.05] to-violet-300/[.08] p-6 text-center sm:p-10"><p className="text-2xl font-black tracking-tight sm:text-3xl">Don't chase a perfect day. Build a repeatable one.</p><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-400">One focused block. One solved position. One workout. One clean-space or grooming upgrade. One honest journal entry. Then sleep.</p></footer>
  </div></main>;
}
