// @ts-nocheck
import { useCallback, useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

export type Profile = {
  id: string;
  display_name?: string | null;
  full_name?: string | null;
  username?: string | null;
  bio?: string | null;
  avatar_url?: string | null;
  has_completed_onboarding?: boolean;
  screen_time?: number | null;
};

const fallbackProfile = (id: string): Profile => ({
  id,
  display_name: null,
  full_name: null,
  username: null,
  bio: null,
  avatar_url: null,
  has_completed_onboarding: false,
});

export function useAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetchProfile = useCallback(async (currentUser: User | null) => {
    setError(null);
    if (!currentUser?.id) {
      setUser(null);
      setProfile(null);
      setLoading(false);
      return;
    }

    setUser(currentUser);
    try {
      const { data, error: fetchError } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", currentUser.id)
        .maybeSingle();

      if (fetchError) {
        console.error("Error fetching profile:", fetchError);
        setError(fetchError as unknown as Error);
        setProfile(fallbackProfile(currentUser.id));
      } else {
        setProfile(data ? (data as Profile) : fallbackProfile(currentUser.id));
      }
    } catch (err) {
      console.error("Unhandled profile fetch error:", err);
      setError(err instanceof Error ? err : new Error(String(err)));
      setProfile(fallbackProfile(currentUser.id));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    let mounted = true;

    supabase.auth
      .getSession()
      .then(({ data }) => {
        if (mounted) void fetchProfile(data.session?.user ?? null);
      })
      .catch((err) => {
        console.error("Failed to get session:", err);
        if (mounted) {
          setError(err instanceof Error ? err : new Error(String(err)));
          setLoading(false);
        }
      });

    const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => {
      if (!mounted) return;
      setLoading(true);
      void fetchProfile(session?.user ?? null);
    });

    return () => {
      mounted = false;
      listener.subscription.unsubscribe();
    };
  }, [fetchProfile]);

  const updateProfile = useCallback(
    async (updates: Partial<Profile>) => {
      if (!user?.id) return { error: new Error("No authenticated user found.") };

      const previous = profile;
      setProfile((current) =>
        current ? { ...current, ...updates } : { ...fallbackProfile(user.id), ...updates },
      );

      // We omit the id property when passing it to update since we're using it to match
      const { id: _ignoredId, ...updatePayload } = updates;

      const { data, error } = await supabase
        .from("profiles")
        // @ts-expect-error Types generated by Supabase might not match exact generic parameter bounds sometimes
        .update(updatePayload)
        .eq("id", user.id)
        .select("*")
        .single();

      if (error) {
        setProfile(previous);
        console.error("Failed to sync profile update:", error);
        return { error };
      }

      setProfile(data as Profile);
      return { data: data as Profile };
    },
    [profile, user?.id],
  );

  return { user, profile, loading, error, updateProfile, refreshProfile: () => fetchProfile(user) };
}

export function displayNameOf(user: User | null, profile: Profile | null): string {
  return (
    profile?.full_name ||
    profile?.display_name ||
    profile?.username ||
    ((user?.user_metadata as Record<string, unknown> | undefined)?.full_name as string) ||
    ((user?.user_metadata as Record<string, unknown> | undefined)?.display_name as string) ||
    user?.email?.split("@")[0] ||
    "Friend"
  );
}
