import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, CheckCheck, MessageCircle, MoreVertical, Paperclip, Search, Send, Smile, UserRound, Users, X } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/chat")({ component: ChatPage });

type Profile={id:string;display_name:string|null;full_name:string|null;username:string|null;avatar_url:string|null;current_level:number|null;last_seen_at?:string|null};
type Friend={id:string;profile:Profile};
type Message={id:string;conversation_id:string;sender_id:string;content:string;created_at:string;read_at:string|null};
const nameOf=(p?:Profile)=>p?.display_name||p?.full_name||(p?.username?`@${p.username}`:"OUTSTAND user");
const initialOf=(p?:Profile)=>nameOf(p).slice(0,1).toUpperCase();
const online=(p?:Profile)=>Boolean(p?.last_seen_at&&Date.now()-new Date(p.last_seen_at).getTime()<120000);
const lastSeen=(p?:Profile)=>{if(!p?.last_seen_at)return "Offline";const s=Math.max(0,Math.floor((Date.now()-new Date(p.last_seen_at).getTime())/1000));if(s<120)return "online";const m=Math.floor(s/60);if(m<60)return `last seen ${m}m ago`;const h=Math.floor(m/60);if(h<24)return `last seen ${h}h ago`;return `last seen ${Math.floor(h/24)}d ago`};

function ChatPage(){
 const navigate=useNavigate(); const [userId,setUserId]=useState<string>(); const [friends,setFriends]=useState<Friend[]>([]); const [selected,setSelected]=useState<Profile>(); const [conversationId,setConversationId]=useState<string>(); const [messages,setMessages]=useState<Message[]>([]); const [draft,setDraft]=useState(""); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [typing,setTyping]=useState(false); const [friendTyping,setFriendTyping]=useState(false); const [mobileList,setMobileList]=useState(true); const bottomRef=useRef<HTMLDivElement>(null); const typingTimer=useRef<number>();
 const selectedId=selected?.id;
 const filteredFriends=useMemo(()=>friends.filter(f=>{const q=search.trim().toLowerCase();return !q||nameOf(f.profile).toLowerCase().includes(q)||(f.profile.username||"").toLowerCase().includes(q)}),[friends,search]);
 const loadFriends=async(uid:string)=>{const{data:rows,error}=await supabase.from("friendships").select("friend_id").eq("user_id",uid).order("created_at",{ascending:false});if(error){toast.error("Could not load your friends.");return}const ids=(rows||[]).map(r=>r.friend_id);if(!ids.length){setFriends([]);return}const{data:profiles}=await supabase.from("profiles").select("id,display_name,full_name,username,avatar_url,current_level,last_seen_at").in("id",ids);const map=new Map((profiles||[]).map(p=>[p.id,p as Profile]));setFriends((rows||[]).map(r=>({id:r.friend_id,profile:map.get(r.friend_id)})).filter((x):x is Friend=>Boolean(x.profile)))};
 const loadConversation=async(friendId:string)=>{setMessages([]);setConversationId(undefined);const{data,error}=await(supabase as any).rpc("get_or_create_direct_conversation",{target_user:friendId});if(error){toast.error(error.message||"Could not open this chat.");return}const id=data as string;setConversationId(id);const result=await(supabase as any).from("direct_messages").select("id,conversation_id,sender_id,content,created_at,read_at").eq("conversation_id",id).order("created_at",{ascending:true}).limit(500);if(result.error)toast.error("Could not load messages.");else setMessages(result.data||[]);await(supabase as any).from("direct_messages").update({read_at:new Date().toISOString()}).eq("conversation_id",id).neq("sender_id",userId||"").is("read_at",null)};
 useEffect(()=>{let active=true;supabase.auth.getUser().then(async({data})=>{if(!data.user){setLoading(false);return}setUserId(data.user.id);await loadFriends(data.user.id);const target=new URLSearchParams(window.location.search).get("friend");if(target&&target!==data.user.id){const{data:profile}=await supabase.from("profiles").select("id,display_name,full_name,username,avatar_url,current_level,last_seen_at").eq("id",target).maybeSingle();if(active&&profile){setSelected(profile as Profile);setMobileList(false);await loadConversation(target)}}if(active)setLoading(false)});return()=>{active=false}},[]);
 useEffect(()=>{if(!selectedId||!conversationId)return;const channel=supabase.channel(`direct-chat:${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"direct_messages",filter:`conversation_id=eq.${conversationId}`},payload=>{const incoming=payload.new as Message;setMessages(current=>current.some(m=>m.id===incoming.id)?current:[...current,incoming]);if(incoming.sender_id!==userId)void(supabase as any).from("direct_messages").update({read_at:new Date().toISOString()}).eq("id",incoming.id)}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"direct_messages",filter:`conversation_id=eq.${conversationId}`},payload=>{const updated=payload.new as Message;setMessages(current=>current.map(m=>m.id===updated.id?updated:m))}).on("presence",{event:"sync"},()=>{const state=channel.presenceState();setFriendTyping(Object.values(state).some((entries:any)=>entries.some((e:any)=>e.user_id===selectedId&&e.typing)))}).subscribe(async status=>{if(status==="SUBSCRIBED"&&userId)await channel.track({user_id:userId,typing:false})});return()=>{void supabase.removeChannel(channel);setFriendTyping(false)}},[conversationId,selectedId,userId]);
 useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"})},[messages.length]);
 const updateTyping=async(value:string)=>{setDraft(value);if(!conversationId||!userId)return;const channel=supabase.getChannels().find(c=>c.topic===`realtime:direct-chat:${conversationId}`);if(channel){await channel.track({user_id:userId,typing:Boolean(value.trim())})}window.clearTimeout(typingTimer.current);typingTimer.current=window.setTimeout(async()=>{if(channel)await channel.track({user_id:userId,typing:false})},1500)};
 const send=async()=>{const content=draft.trim();if(!content||!conversationId||!userId||sending)return;setSending(true);const{data,error}=await(supabase as any).from("direct_messages").insert({conversation_id:conversationId,sender_id:userId,content}).select("id,conversation_id,sender_id,content,created_at,read_at").single();if(error)toast.error("Message could not be sent.");else{setMessages(current=>current.some(m=>m.id===data.id)?current:[...current,data as Message]);setDraft("")}setSending(false)};
 const selectFriend=async(profile:Profile)=>{setSelected(profile);setMobileList(false);navigate({to:"/chat",search:{friend:profile.id} as any});await loadConversation(profile.id)};
 return <main className="mx-auto flex h-[calc(100vh-72px)] max-w-[1500px] flex-col overflow-hidden px-0 sm:px-3 lg:px-5"><div className="hidden items-center justify-between px-2 py-4 sm:flex"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.26em] text-cyan-300"><MessageCircle className="h-4 w-4"/> Messages</div><h1 className="mt-1 text-2xl font-black tracking-tight text-white">Chats</h1></div><button onClick={()=>navigate({to:"/friends"})} className="inline-flex items-center rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2 text-xs font-black text-slate-300 hover:text-white"><Users className="mr-2 h-4 w-4"/> Friends</button></div>
 <div className="grid min-h-0 flex-1 overflow-hidden border border-white/[0.08] bg-[#07101d] shadow-[0_30px_100px_-55px_rgba(34,211,238,.45)] sm:rounded-[2rem] lg:grid-cols-[340px_1fr]">
  <aside className={`${mobileList?"flex":"hidden"} min-h-0 flex-col border-r border-white/[0.06] bg-[#091522] lg:flex`}><div className="border-b border-white/[0.06] p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-lg font-black text-white">Chats</p><p className="text-[10px] text-slate-600">{friends.length} friends</p></div><button onClick={()=>navigate({to:"/friends"})} className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 text-slate-400 hover:text-white"><UserRound className="h-4 w-4"/></button></div><div className="relative mt-4"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search chats" className="w-full rounded-xl border border-white/[0.07] bg-black/20 py-3 pl-10 pr-8 text-xs font-semibold text-white outline-none placeholder:text-slate-700 focus:border-cyan-300/25"/>{search&&<button onClick={()=>setSearch("")} className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-600"><X className="h-4 w-4"/></button>}</div></div><div className="min-h-0 flex-1 overflow-y-auto">{loading?<div className="p-5 text-sm text-slate-600">Loading chats…</div>:filteredFriends.length===0?<div className="p-6 text-center text-sm leading-6 text-slate-600">{search?"No chats match your search.":"Add friends to start chatting."}</div>:filteredFriends.map(friend=><button key={friend.id} onClick={()=>void selectFriend(friend.profile)} className={`flex w-full items-center gap-3 border-b border-white/[0.035] px-4 py-3 text-left transition hover:bg-white/[0.035] ${selectedId===friend.id?"bg-cyan-300/[0.07]":""}`}><div className="relative"><Avatar profile={friend.profile}/><span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-[#091522] ${online(friend.profile)?"bg-emerald-400":"bg-slate-600"}`}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-black text-white">{nameOf(friend.profile)}</span><span className="text-[9px] text-slate-700">{online(friend.profile)?"online":""}</span></div><p className="truncate text-xs text-slate-600">{friend.profile.username?`@${friend.profile.username}`:"OUTSTAND friend"}</p></div></button>)}</div></aside>
  <section className={`${mobileList?"hidden":"flex"} min-h-0 flex-col lg:flex bg-[#07101d]`}>
   {selected?<><header className="flex items-center gap-3 border-b border-white/[0.06] bg-[#091522]/95 p-3 backdrop-blur-xl sm:p-4"><button onClick={()=>setMobileList(true)} className="grid h-9 w-9 place-items-center rounded-xl text-slate-400 hover:bg-white/5 lg:hidden" aria-label="Back to chats"><ArrowLeft className="h-4 w-4"/></button><button onClick={()=>navigate({to:"/user-profile",search:{id:selected.id} as any})} className="relative shrink-0"><Avatar profile={selected}/><span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-[#091522] ${online(selected)?"bg-emerald-400":"bg-slate-600"}`}/></button><button onClick={()=>navigate({to:"/user-profile",search:{id:selected.id} as any})} className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-black text-white">{nameOf(selected)}</p><p className={`truncate text-xs ${friendTyping?"text-cyan-300":"text-slate-600"}`}>{friendTyping?"typing…":lastSeen(selected)}</p></button><button className="grid h-9 w-9 place-items-center rounded-xl text-slate-500 hover:bg-white/5 hover:text-white" aria-label="Chat options"><MoreVertical className="h-5 w-5"/></button></header>
    <div className="relative min-h-0 flex-1 overflow-y-auto px-3 py-5 sm:px-6 sm:py-6"><div className="pointer-events-none absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_20%_20%,rgba(34,211,238,.07),transparent_30%),radial-gradient(circle_at_80%_80%,rgba(129,140,248,.06),transparent_35%)]"/><div className="relative mx-auto max-w-3xl space-y-1">{messages.length===0?<div className="grid min-h-64 place-items-center text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-cyan-300/10"><MessageCircle className="mx-auto h-7 w-7 text-cyan-300/50"/></div><p className="mt-4 text-sm font-black text-slate-500">No messages yet</p><p className="mt-1 text-xs text-slate-700">Say hello to {nameOf(selected)}.</p></div></div>:messages.map((message,index)=>{const mine=message.sender_id===userId;const previous=messages[index-1];const showTime=!previous||new Date(message.created_at).getTime()-new Date(previous.created_at).getTime()>30*60*1000;return <div key={message.id}>{showTime&&<div className="my-5 text-center text-[9px] font-black uppercase tracking-[.18em] text-slate-700">{new Date(message.created_at).toLocaleDateString([], {month:"short",day:"numeric"})}</div>}<div className={`flex ${mine?"justify-end":"justify-start"}`}><div className={`group relative max-w-[85%] rounded-2xl px-3.5 py-2.5 text-sm leading-6 shadow-sm sm:max-w-[70%] ${mine?"rounded-br-md bg-cyan-300 text-slate-950":"rounded-bl-md bg-[#162535] text-slate-100"}`}><p className="whitespace-pre-wrap break-words">{message.content}</p><div className={`mt-1 flex items-center justify-end gap-1 text-[9px] font-bold ${mine?"text-slate-800/55":"text-slate-500"}`}>{new Date(message.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}{mine&&(message.read_at?<CheckCheck className="h-3.5 w-3.5"/>:<Check className="h-3.5 w-3.5"/>)}</div></div></div></div>})}<div ref={bottomRef}/></div></div>
    <form onSubmit={e=>{e.preventDefault();void send()}} className="border-t border-white/[0.06] bg-[#091522] p-3 sm:p-4"><div className="mx-auto flex max-w-3xl items-end gap-2"><button type="button" className="hidden h-11 w-11 shrink-0 place-items-center rounded-xl text-slate-500 hover:bg-white/5 hover:text-cyan-300 sm:grid" aria-label="Attach file"><Paperclip className="h-5 w-5"/></button><div className="flex min-h-11 flex-1 items-end rounded-2xl border border-white/[0.08] bg-black/20 px-2 focus-within:border-cyan-300/25"><button type="button" className="grid h-9 w-9 shrink-0 place-items-center text-slate-600 hover:text-cyan-300" aria-label="Emoji"><Smile className="h-5 w-5"/></button><textarea value={draft} onChange={e=>void updateTyping(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} maxLength={4000} rows={1} placeholder={`Message ${nameOf(selected)}…`} className="max-h-32 min-h-10 flex-1 resize-none bg-transparent px-1 py-2.5 text-sm text-white outline-none placeholder:text-slate-700"/></div><button type="submit" disabled={!draft.trim()||sending} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-cyan-300 text-slate-950 hover:bg-cyan-200 disabled:opacity-40" aria-label="Send message"><Send className="h-4 w-4"/></button></div></form>
   </>:<div className="hidden flex-1 place-items-center text-center lg:grid"><div><MessageCircle className="mx-auto h-16 w-16 text-cyan-300/15"/><h2 className="mt-5 text-2xl font-black text-white">Your messages</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-600">Select a friend to start a private conversation.</p></div></div>}
  </section>
 </div></main>;
}
function Avatar({profile}:{profile?:Profile}){return <div className="grid h-11 w-11 place-items-center overflow-hidden rounded-full border border-white/10 bg-slate-950 text-sm font-black text-cyan-200">{profile?.avatar_url?<img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/>:initialOf(profile)}</div>}
