import { createFileRoute } from "@tanstack/react-router";
import { Bell, BellOff, Check, Clock3, Megaphone, Target, Trash2, Zap, RefreshCw, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";
import { createNotificationJob, deleteNotificationJob, disablePushNotifications, getNotificationHistory, getNotificationJobs, getNotificationPreferences, requestPushPermission, saveNotificationPreferences, type NotificationJob, type NotificationPreferences } from "@/lib/notification-engine";

export const Route=createFileRoute("/_authenticated/notifications")({component:NotificationsPage});
const categories=[{key:"coaching_enabled",title:"Contextual guidance",description:"Useful nudges based on your actual habits, focus and progress.",icon:Zap},{key:"habits_enabled",title:"Habit reminders",description:"Gentle reminders when today's habits still need attention.",icon:Check},{key:"goals_enabled",title:"Goal reminders",description:"Keep important goals visible without constant interruptions.",icon:Target},{key:"motivational_enabled",title:"Momentum messages",description:"Occasional encouragement when it genuinely helps.",icon:Bell},{key:"updates_enabled",title:"OUTSTAND updates",description:"New features, improvements and important product news.",icon:Megaphone}] as const;
type NotificationEvent={id:string;title:string;body:string;category:string};
function NotificationsPage(){
 const[preferences,setPreferences]=useState<NotificationPreferences|null>(null);const[history,setHistory]=useState<NotificationEvent[]>([]);const[jobs,setJobs]=useState<NotificationJob[]>([]);const[busy,setBusy]=useState(false);const[loadError,setLoadError]=useState<string|null>(null);const[title,setTitle]=useState("");const[body,setBody]=useState("");const[time,setTime]=useState("18:00");const[category,setCategory]=useState<"habit"|"goal"|"motivation"|"update"|"system">("habit");
 const load=async()=>{setLoadError(null);try{const[prefs,events,scheduled]=await Promise.all([getNotificationPreferences(),getNotificationHistory(),getNotificationJobs()]);setPreferences(prefs);setHistory(events as NotificationEvent[]);setJobs(scheduled);}catch(error){setLoadError(error instanceof Error?error.message:"Could not load notification settings.");}};
 useEffect(()=>{void load();},[]);
 const update=async(patch:Partial<NotificationPreferences>)=>{try{setPreferences(await saveNotificationPreferences(patch));}catch(error){toast.error(error instanceof Error?error.message:"Could not save notification settings.");}};
 const enable=async()=>{setBusy(true);try{await requestPushPermission();setPreferences(await getNotificationPreferences());toast.success("Notifications enabled.");}catch(error){toast.error(error instanceof Error?error.message:"Could not enable notifications.");}finally{setBusy(false);}};
 const disable=async()=>{setBusy(true);try{await disablePushNotifications();setPreferences(current=>current?{...current,push_enabled:false}:current);toast.success("Notifications paused.");}catch(error){toast.error(error instanceof Error?error.message:"Could not disable notifications.");}finally{setBusy(false);}};
 const addJob=async()=>{if(!title.trim()||!body.trim()){toast.error("Add a title and message first.");return;}setBusy(true);try{const job=await createNotificationJob({category,title:title.trim(),body:body.trim(),local_time:time});setJobs(current=>[...current,job].sort((a,b)=>a.local_time.localeCompare(b.local_time)));setTitle("");setBody("");toast.success(`Scheduled for ${time}.`);}catch(error){toast.error(error instanceof Error?error.message:"Could not schedule reminder.");}finally{setBusy(false);}};
 const removeJob=async(id:string)=>{try{await deleteNotificationJob(id);setJobs(current=>current.filter(job=>job.id!==id));toast.success("Reminder removed.");}catch(error){toast.error(error instanceof Error?error.message:"Could not remove reminder.");}};
 if(loadError)return <main className="mx-auto flex min-h-[70vh] max-w-4xl items-center justify-center px-4"><div className="w-full max-w-md rounded-3xl border border-red-400/15 bg-white/[0.03] p-7 text-center"><p className="text-xs font-black uppercase tracking-[0.2em] text-red-300">Couldn’t load settings</p><p className="mt-3 text-sm leading-6 text-white/55">{loadError}</p><Button className="mt-5" onClick={()=>void load()}><RefreshCw className="mr-2 size-4"/>Try again</Button></div></main>;
 if(!preferences)return <div className="mx-auto flex min-h-[70vh] max-w-4xl items-center justify-center text-sm text-muted-foreground">Loading notification controls…</div>;
 return <main className="mx-auto w-full max-w-5xl space-y-6 px-4 py-8 md:px-8">
  <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.025] p-6 md:p-8"><div className="relative z-10 flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-xs font-medium text-slate-300"><Bell className="size-3.5"/> Notifications</div><h1 className="text-3xl font-semibold tracking-tight text-white md:text-4xl">Useful reminders. Nothing noisy.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/55">Enable push once, then OUTSTAND can deliver scheduled reminders even when the app is closed.</p></div><Button size="lg" disabled={busy} onClick={()=>void(preferences.push_enabled?disable():enable())} className="shrink-0">{preferences.push_enabled?<><BellOff className="mr-2 size-4"/>Pause notifications</>:<><Bell className="mr-2 size-4"/>Enable notifications</>}</Button></div></section>
  <Card className="border-white/[0.08] bg-white/[0.025]"><CardHeader><CardTitle className="flex items-center gap-2"><Clock3 className="size-4 text-blue-300"/>Schedule a reminder</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs text-white/45">Category<select value={category} onChange={e=>setCategory(e.target.value as typeof category)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"><option value="habit">Habit</option><option value="goal">Goal</option><option value="motivation">Motivation</option><option value="update">Update</option></select></label><label className="text-xs text-white/45">Time<input type="time" value={time} onChange={e=>setTime(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/></label><label className="text-xs text-white/45">Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Study reminder" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/></label></div><label className="block text-xs text-white/45">Message<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Time to start your planned study session." rows={2} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/></label><Button onClick={()=>void addJob()} disabled={busy||!preferences.push_enabled}><Plus className="mr-2 size-4"/>Schedule every day</Button>{!preferences.push_enabled&&<p className="text-xs text-amber-200/70">Enable push notifications first. The schedule is stored in Supabase and runs independently of the app being open.</p>}</CardContent></Card>
  <Card className="border-white/[0.08] bg-white/[0.025]"><CardHeader><CardTitle>Scheduled reminders</CardTitle></CardHeader><CardContent>{jobs.length===0?<p className="text-sm text-white/35">No scheduled reminders yet.</p>:<div className="space-y-2">{jobs.map(job=><div key={job.id} className="flex items-center justify-between gap-3 rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4"><div><p className="font-medium text-white">{job.title}</p><p className="mt-1 text-xs text-white/45">{job.local_time.slice(0,5)} · {job.category} · {job.timezone}</p><p className="mt-1 text-sm text-white/50">{job.body}</p></div><Button variant="ghost" size="icon" onClick={()=>void removeJob(job.id)} aria-label="Remove reminder"><Trash2 className="size-4"/></Button></div>)}</div>}</CardContent></Card>
  <Card className="border-white/[0.08] bg-white/[0.025]"><CardHeader><CardTitle className="flex items-center gap-2"><Zap className="size-4 text-blue-300"/>What OUTSTAND can send</CardTitle></CardHeader><CardContent className="space-y-1">{categories.map(({key,title:label,description,icon:Icon})=><div key={key} className="flex items-center justify-between gap-4 rounded-2xl px-3 py-4"><div className="flex items-start gap-3"><div className="mt-0.5 rounded-xl bg-blue-400/10 p-2 text-blue-300"><Icon className="size-4"/></div><div><p className="font-medium text-white">{label}</p><p className="mt-1 text-xs leading-5 text-white/45">{description}</p></div></div><Switch checked={preferences[key]} onCheckedChange={checked=>void update({[key]:checked})}/></div>)}</CardContent></Card>
  <Card className="border-white/[0.08] bg-white/[0.025]"><CardHeader><CardTitle>Quiet hours & frequency</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center justify-between gap-4"><div><p className="font-medium text-white">Quiet hours</p><p className="text-xs text-white/45">No push reminders during your chosen rest window.</p></div><Switch checked={preferences.quiet_hours_enabled} onCheckedChange={checked=>void update({quiet_hours_enabled:checked})}/></div><Separator className="bg-white/[0.06]"/><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-white/45">Start<input type="time" value={preferences.quiet_start} onChange={e=>void update({quiet_start:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/></label><label className="text-xs text-white/45">End<input type="time" value={preferences.quiet_end} onChange={e=>void update({quiet_end:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/></label></div><p className="text-xs text-white/35">Maximum {preferences.max_daily} push notifications per day.</p></CardContent></Card>
  <Card className="border-white/[0.08] bg-white/[0.025]"><CardHeader><CardTitle>Recent notification activity</CardTitle></CardHeader><CardContent>{history.length===0?<div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-white/35">No notifications yet. Your history will appear here.</div>:<div className="space-y-3">{history.map(item=><div key={item.id} className={cn("rounded-2xl border border-white/[0.06] bg-white/[0.02] p-4")}><div className="flex items-center justify-between gap-3"><p className="font-medium text-white">{item.title}</p><span className="text-[11px] uppercase tracking-wider text-white/30">{item.category}</span></div><p className="mt-1 text-sm text-white/50">{item.body}</p></div>)}</div>}</CardContent></Card>
 </main>;
}
