import { createFileRoute } from "@tanstack/react-router";
import { motion, MotionConfig } from "framer-motion";
import { Check, Copy, Edit3, Flame, Focus, Medal, Save, Sparkles, Target, Timer, Trophy, TrendingUp, X, Zap } from "lucide-react";
import { useProfileState } from "@/hooks/use-profile-state";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_authenticated/profile")({
  head: () => ({ meta: [
    { title: "Profile — OUTSTAND" },
    { name: "description", content: "Your OUTSTAND identity, progress, momentum, habits, and achievements." },
  ] }),
  component: ProfilePage,
});

const ease = [0.22, 1, 0.36, 1] as const;
const panel = "rounded-[2rem] border border-white/[0.08] bg-white/[0.035] shadow-[0_30px_100px_-55px_rgba(34,211,238,.28)] backdrop-blur-2xl";
const input = "w-full rounded-xl border border-white/[0.08] bg-black/20 px-3.5 py-3 text-sm font-semibold text-white outline-none transition placeholder:text-slate-700 focus:border-cyan-300/30 focus:ring-2 focus:ring-cyan-300/10";
const fadeUp = { hidden: { opacity: 0, y: 16 }, show: { opacity: 1, y: 0, transition: { duration: .55, ease } } };

type ProfileState = ReturnType<typeof useProfileState>;

function ProfilePage() {
  const state = useProfileState();
  const initial = (state.name || "U").charAt(0).toUpperCase();
  const progress = Math.min(100, Math.max(0, state.pct));
  const rank = state.getRankTitle(state.level);
  const nextXp = Math.max(0, state.need - state.into);

  return <MotionConfig reducedMotion="user">
    <motion.main initial="hidden" animate="show" variants={{ hidden: {}, show: { transition: { staggerChildren: .045 } } }} className="mx-auto max-w-[1480px] space-y-5 px-4 pb-24 pt-3 sm:px-6 lg:space-y-6 lg:px-8 xl:px-10">
      <Hero state={state} initial={initial} rank={rank} />
      <motion.section variants={fadeUp} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Kpi icon={<Zap />} label="Total XP" value={state.xp.toLocaleString()} note="Lifetime progress" tone="cyan" />
        <Kpi icon={<TrendingUp />} label="Productivity" value={`${state.stats.productivity}%`} note="Current momentum" tone="emerald" />
        <Kpi icon={<Flame />} label="Best streak" value={`${state.bestStreak}d`} note="Consistency peak" tone="orange" />
        <Kpi icon={<Target />} label="Completions" value={state.stats.totalCompletions.toLocaleString()} note="Actions completed" tone="violet" />
      </motion.section>
      <motion.section variants={fadeUp} className="grid gap-5 lg:grid-cols-[.72fr_1.28fr]">
        <LevelCard state={state} progress={progress} nextXp={nextXp} rank={rank} />
        <MomentumCard state={state} />
      </motion.section>
      <motion.section variants={fadeUp} className={cn(panel, "overflow-hidden p-5 sm:p-7")}>
        <SectionHeading eyebrow="Consistency" title="Your 30-day operating rhythm" icon={<TrendingUp />} right={`${state.stats.avg} avg score`} />
        <div className="mt-7 overflow-x-auto pb-1"><div className="grid min-w-[720px] grid-cols-[repeat(30,minmax(18px,1fr))] items-end gap-1.5">
          {state.stats.dayStats.map((item) => <div key={item.d} className="group relative flex h-36 flex-col justify-end gap-2"><div className={cn("relative min-h-2 w-full rounded-md transition-all duration-300 group-hover:scale-y-105", item.ratio === 0 ? "bg-white/[0.045]" : item.ratio < .5 ? "bg-indigo-950" : item.ratio < 1 ? "bg-indigo-500" : "bg-emerald-400")} style={{ height: `${Math.max(7, item.ratio * 100)}%` }} /><span className="text-center text-[7px] font-bold text-slate-700">{item.d.slice(-2)}</span><div className="pointer-events-none absolute bottom-full left-1/2 z-10 mb-2 -translate-x-1/2 whitespace-nowrap rounded-xl border border-white/10 bg-slate-950 px-3 py-2 text-[10px] font-bold text-white opacity-0 shadow-2xl transition group-hover:opacity-100">{item.done}/{item.total} habits</div></div>)}
        </div></div>
        <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/[0.06] pt-4 text-[9px] font-black uppercase tracking-[.16em] text-slate-600"><span>30 days of behavior</span><span>{state.stats.totalCompletions ? `${Math.min(100, Math.round((state.stats.totalCompletions / Math.max(1, state.habits.length * 30)) * 100))}% habit density` : "Build consistency to reveal your signal"}</span></div>
      </motion.section>
      <motion.section variants={fadeUp} className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
        <section className={cn(panel, "p-5 sm:p-7")}><SectionHeading eyebrow="Your system" title="Strongest repetitions" icon={<Flame />} right={`${state.habits.length} active`} />
          {state.habits.length ? <div className="mt-5 grid gap-2.5 sm:grid-cols-2">{state.habits.slice(0, 6).map((habit, index) => { const streak = state.streaks.find((item) => item?.id === habit.id)?.streak ?? 0; return <motion.div key={habit.id} whileHover={{ y: -2 }} className="group flex items-center gap-3 rounded-2xl border border-white/[0.07] bg-black/10 p-3.5 transition hover:border-cyan-300/15 hover:bg-cyan-300/[0.025]"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/[0.07] bg-white/[0.03] text-xl">{habit.emoji}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-white">{habit.name}</p><div className="mt-1 flex items-center gap-2 text-[9px] font-black uppercase tracking-[.12em] text-slate-600"><span>Rank {index + 1}</span><span>·</span><span>{streak} day streak</span></div></div><div className="grid h-8 w-8 place-items-center rounded-lg border border-emerald-300/10 bg-emerald-300/[0.05] text-emerald-300"><Check className="h-4 w-4" /></div></motion.div>; })}</div> : <EmptyState />}
        </section>
        <section className={cn(panel, "p-5 sm:p-7")}><SectionHeading eyebrow="Activity" title="What you've built" icon={<Trophy />} /><div className="mt-5 grid grid-cols-2 gap-2.5"><MiniStat icon={<Timer />} label="Focus sessions" value={state.stats.focusCompleted.toLocaleString()} /><MiniStat icon={<Focus />} label="Focus minutes" value={state.stats.focusMinutes.toLocaleString()} /><MiniStat icon={<Zap />} label="Challenges" value={state.outstand.length.toLocaleString()} /><MiniStat icon={<Medal />} label="Habits built" value={state.habits.length.toLocaleString()} /></div><div className="mt-5 rounded-2xl border border-cyan-300/10 bg-gradient-to-br from-cyan-300/[0.06] to-violet-400/[0.03] p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-cyan-300/15 bg-cyan-300/[0.07] text-cyan-200"><Sparkles className="h-4 w-4" /></span><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-200/70">Identity signal</p><p className="mt-1 text-sm leading-5 text-slate-300">{state.getRankTitle(state.level)} energy. Keep stacking small actions until your results become obvious.</p></div></div></div></section>
      </motion.section>
      <motion.section variants={fadeUp} className={cn(panel, "p-5 sm:p-7")}><SectionHeading eyebrow="Performance" title="Weekly signal" icon={<TrendingUp />} right={`${state.stats.avg}/100 average`} /><div className="mt-6 h-44 overflow-hidden rounded-2xl border border-white/[0.06] bg-black/10 p-3"><SimpleTrend logs={state.logs} /></div></motion.section>
    </motion.main>
  </MotionConfig>;
}

function Hero({ state, initial, rank }: { state: ProfileState; initial: string; rank: string }) {
  return <motion.section variants={fadeUp} className="relative overflow-hidden rounded-[2.5rem] border border-white/10 bg-[radial-gradient(circle_at_8%_20%,rgba(34,211,238,.14),transparent_28%),radial-gradient(circle_at_88%_15%,rgba(139,92,246,.14),transparent_26%),radial-gradient(circle_at_75%_100%,rgba(16,185,129,.08),transparent_30%),linear-gradient(135deg,rgba(255,255,255,.055),rgba(255,255,255,.018))] p-5 shadow-[0_40px_120px_-70px_rgba(34,211,238,.5)] sm:p-8 lg:p-10">
    <div className="pointer-events-none absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.018)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.018)_1px,transparent_1px)] [background-size:42px_42px]" /><div className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl" />
    <div className="relative grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center">
      <div className="flex min-w-0 flex-col gap-5 sm:flex-row sm:items-center"><div className="relative shrink-0"><button type="button" onClick={() => state.fileInputRef.current?.click()} aria-label="Change avatar" className="group relative grid h-28 w-28 place-items-center overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950 shadow-2xl ring-1 ring-cyan-300/10 sm:h-32 sm:w-32">{state.isUploading ? <span className="text-[9px] font-black uppercase tracking-[.2em] text-cyan-200">Saving</span> : state.profile?.avatar_url ? <img src={state.profile.avatar_url} alt="Profile avatar" className="h-full w-full object-cover" /> : <span className="bg-gradient-to-br from-cyan-200 via-white to-violet-300 bg-clip-text text-5xl font-black text-transparent">{initial}</span>}<span className="absolute inset-x-0 bottom-0 bg-black/70 px-2 py-2 text-[9px] font-black uppercase tracking-[.18em] text-white opacity-0 backdrop-blur transition-opacity group-hover:opacity-100">Change photo</span></button><input ref={state.fileInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={state.handleAvatarUpload} className="sr-only" /><span className="absolute bottom-2 right-2 h-4 w-4 rounded-full border-[3px] border-slate-950 bg-emerald-400 shadow-[0_0_16px_rgba(52,211,153,.8)]" /></div>
      <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-cyan-300/15 bg-cyan-300/10 px-2.5 py-1 text-[9px] font-black uppercase tracking-[.2em] text-cyan-200">OUTSTAND IDENTITY</span><span className="rounded-full border border-violet-300/15 bg-violet-300/[0.06] px-2.5 py-1 text-[9px] font-black uppercase tracking-[.18em] text-violet-200">{rank}</span></div><h1 className="mt-3 break-words text-4xl font-black tracking-[-.055em] text-white sm:text-5xl lg:text-6xl">{state.name}<span className="text-cyan-300">.</span></h1>{state.profile?.username && <p className="mt-1 text-sm font-bold text-cyan-200/70">@{state.profile.username}</p>}<p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{state.profile?.bio || "Define the person you are becoming. Your profile turns progress into identity."}</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={state.handleCopyId} className="inline-flex items-center gap-2 rounded-full border border-white/[0.08] bg-black/20 px-3 py-1.5 text-[10px] font-bold text-slate-400 transition hover:border-cyan-300/20 hover:text-white">{state.copiedId ? <Check className="h-3.5 w-3.5 text-emerald-300" /> : <Copy className="h-3.5 w-3.5 text-cyan-300" />}{state.copiedId ? "ID copied" : `ID ${(state.user?.id || "unknown").slice(0, 8)}`}</button><span className="inline-flex items-center gap-1.5 rounded-full border border-orange-300/10 bg-orange-300/[0.05] px-3 py-1.5 text-[10px] font-bold text-orange-200"><Flame className="h-3.5 w-3.5" />{state.bestStreak} day best streak</span></div></div></div>
      <div className="flex flex-col gap-3 lg:min-w-[220px] lg:items-end"><div className="text-right"><p className="text-[9px] font-black uppercase tracking-[.2em] text-slate-600">Current standing</p><p className="mt-1 text-3xl font-black text-white">Level {state.level}</p><p className="text-xs font-semibold text-slate-500">{state.xp.toLocaleString()} XP earned</p></div>{!state.isEditing ? <button type="button" onClick={state.beginEdit} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-xs font-black text-slate-950 shadow-[0_15px_40px_-18px_rgba(255,255,255,.7)] transition hover:-translate-y-0.5 hover:bg-cyan-50"><Edit3 className="h-4 w-4" />Edit profile</button> : <div className="flex gap-2"><button type="button" onClick={state.saveProfile} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-black text-slate-950"><Save className="h-4 w-4" />Save</button><button type="button" onClick={() => state.setIsEditing(false)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.05] px-4 py-2.5 text-xs font-black text-white"><X className="h-4 w-4" />Cancel</button></div>}</div>
    </div>
    {state.isEditing && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} className="relative mt-7 grid gap-3 border-t border-white/[0.07] pt-6 md:grid-cols-3"><Field label="Name"><input value={state.draftName} onChange={(e) => state.setDraftName(e.target.value)} maxLength={80} className={input} /></Field><Field label="Username"><input value={state.draftUsername} onChange={(e) => state.setDraftUsername(e.target.value)} maxLength={24} placeholder="your_handle" className={input} /></Field><Field label="Bio"><textarea value={state.draftBio} onChange={(e) => state.setDraftBio(e.target.value)} maxLength={240} rows={2} placeholder="What are you building?" className={cn(input, "resize-none")} /></Field></motion.div>}
  </motion.section>;
}

function LevelCard({ state, progress, nextXp, rank }: { state: ProfileState; progress: number; nextXp: number; rank: string }) { return <section className={cn(panel, "relative overflow-hidden p-6 sm:p-8")}><div className="absolute -right-20 -top-20 h-56 w-56 rounded-full bg-violet-500/[0.08] blur-3xl" /><div className="relative"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-violet-200/60">Current level</p><p className="mt-2 text-7xl font-black tracking-[-.07em] text-white">{state.level}</p><p className="text-sm font-bold text-slate-500">{rank} class</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl border border-violet-300/15 bg-violet-300/[0.07] text-violet-200"><Medal className="h-5 w-5" /></div></div><div className="mt-10"><div className="mb-2 flex items-center justify-between text-[10px] font-black uppercase tracking-[.14em] text-slate-600"><span>Next level</span><span className="text-white">{progress}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-white/[0.06]"><motion.div initial={{ width: 0 }} animate={{ width: `${progress}%` }} transition={{ duration: .9, ease }} className="h-full rounded-full bg-gradient-to-r from-violet-500 via-cyan-400 to-emerald-300" /></div><div className="mt-3 flex items-center justify-between text-xs text-slate-600"><span>{state.into.toLocaleString()} / {state.need.toLocaleString()} XP</span><span>{nextXp.toLocaleString()} XP remaining</span></div></div></div></section>; }
function MomentumCard({ state }: { state: ProfileState }) { return <section className={cn(panel, "p-6 sm:p-8")}><div className="flex items-end justify-between gap-4"><SectionHeading eyebrow="Momentum" title="Your recent signal" icon={<TrendingUp />} /><div className="text-right"><p className="text-3xl font-black text-white">{state.stats.avg}</p><p className="text-[9px] font-black uppercase tracking-[.18em] text-slate-600">7-day avg</p></div></div><div className="mt-6 h-48 overflow-hidden rounded-2xl border border-white/[0.06] bg-black/10 p-3"><SimpleTrend logs={state.logs} /></div><div className="mt-4 grid grid-cols-3 gap-2"><MiniStat label="Focus" value={`${state.stats.focusMinutes}m`} icon={<Timer />} /><MiniStat label="Consistency" value={`${state.stats.habitPct}%`} icon={<Target />} /><MiniStat label="Peak" value={`${state.stats.longest}d`} icon={<Flame />} /></div></section>; }
function SectionHeading({ eyebrow, title, icon, right }: { eyebrow: string; title: string; icon: React.ReactNode; right?: string }) { return <div className="flex items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-[.22em] text-cyan-300/80">{icon}{eyebrow}</div><h2 className="mt-2 text-xl font-black tracking-tight text-white sm:text-2xl">{title}</h2></div>{right && <span className="text-[9px] font-black uppercase tracking-[.14em] text-slate-600">{right}</span>}</div>; }
function Kpi({ icon, label, value, note, tone }: { icon: React.ReactNode; label: string; value: string; note: string; tone: "cyan" | "emerald" | "orange" | "violet" }) { const colors = { cyan: "text-cyan-300", emerald: "text-emerald-300", orange: "text-orange-300", violet: "text-violet-300" }; return <motion.div whileHover={{ y: -3 }} className={cn(panel, "p-5 transition hover:border-white/[0.14]")}><span className={cn("grid h-9 w-9 place-items-center rounded-xl border border-white/[0.07] bg-white/[0.03]", colors[tone])}>{icon}</span><p className="mt-4 text-[9px] font-black uppercase tracking-[.2em] text-slate-600">{label}</p><p className="mt-1 text-3xl font-black tracking-tight text-white">{value}</p><p className="mt-1 text-[10px] font-semibold text-slate-600">{note}</p></motion.div>; }
function MiniStat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-xl border border-white/[0.06] bg-black/10 px-3 py-2.5"><div className="flex items-center gap-1.5 text-slate-600"><span className="text-cyan-300/70">{icon}</span><span className="text-[8px] font-black uppercase tracking-[.15em]">{label}</span></div><p className="mt-1 text-sm font-black text-white">{value}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-[9px] font-black uppercase tracking-[.16em] text-slate-600">{label}</span>{children}</label>; }
function EmptyState() { return <div className="mt-5 rounded-2xl border border-dashed border-cyan-300/10 bg-cyan-300/[0.02] p-6"><Sparkles className="h-5 w-5 text-cyan-300" /><p className="mt-3 text-sm font-bold text-white">Your system starts here.</p><p className="mt-1 text-xs leading-5 text-slate-600">Build a few meaningful habits and your profile will become a living record of your consistency.</p></div>; }
function SimpleTrend({ logs }: { logs: { score?: number; date?: string }[] }) { const values = logs.length ? logs.slice(-7).map((log) => Math.max(0, Math.min(100, Number(log.score) || 0))) : [0]; const max = Math.max(100, ...values); return <div className="flex h-full items-end gap-2">{values.map((value, index) => <div key={`${index}-${value}`} className="group relative flex h-full flex-1 items-end"><motion.div initial={{ height: 0 }} animate={{ height: `${Math.max(4, (value / max) * 100)}%` }} transition={{ duration: .7, delay: index * .04 }} className="w-full rounded-xl bg-gradient-to-t from-indigo-600 via-cyan-400 to-emerald-300 opacity-80 transition group-hover:opacity-100" /><span className="pointer-events-none absolute bottom-full left-1/2 mb-2 -translate-x-1/2 rounded-lg border border-white/10 bg-slate-950 px-2 py-1 text-[9px] font-bold text-white opacity-0 transition group-hover:opacity-100">{value}</span></div>)}</div>; }
