import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BrainCircuit, Play, Route, ShieldCheck, Trophy } from "lucide-react";
import { Link } from "@tanstack/react-router";
import type { DailyLog } from "@/hooks/use-dopamine";

export function ExecutionSystemsCard({ logs }: { logs: DailyLog[] }) {
  const [seconds, setSeconds] = useState(0);
  const [running, setRunning] = useState(false);
  const [done, setDone] = useState(false);
  const recorded = logs.filter((l) => l.recorded);
  const recent = recorded.slice(-7);
  const scores = recorded.map((l) => l.score);
  const avg = scores.length ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : 0;
  const best = scores.length ? Math.max(...scores) : 0;
  const high = recorded.filter((l) => l.score >= 80).length;
  const friction = recorded.filter((l) => l.negatives.length >= 2).length;
  const accelerator = recorded.filter((l) => l.positives.length >= 2).length;
  const consistency = recorded.length ? Math.round(recorded.filter((l) => l.positives.length > 0).length / recorded.length * 100) : 0;
  const trend = useMemo(() => { if (recent.length < 4) return 0; const h = Math.floor(recent.length / 2); const a = recent.slice(0, h).reduce((s, l) => s + l.score, 0) / h; const b = recent.slice(h).reduce((s, l) => s + l.score, 0) / (recent.length - h); return Math.round(b - a); }, [recent]);
  const insight = !recorded.length ? "Start logging real days to unlock behavioral patterns." : friction > accelerator ? "Friction is outweighing your accelerators. Protect one important task before adding more goals." : trend >= 8 ? "Momentum is rising. Repeat the conditions behind your recent high-score days." : consistency >= 70 ? "You are consistent. Focus on quality of execution rather than adding more tasks." : "Your pattern is still forming. Keep the log simple and look for repeatable wins.";
  useEffect(() => { if (!running) return; const id = window.setInterval(() => setSeconds((s) => { if (s >= 600) { setRunning(false); setDone(true); return 600; } return s + 1; }), 1000); return () => window.clearInterval(id); }, [running]);
  const minutes = String(Math.floor((600 - seconds) / 60)).padStart(2, "0"); const secs = String((600 - seconds) % 60).padStart(2, "0");
  return <div className="space-y-6">
    <section className="rounded-[2rem] border border-cyan-400/15 bg-cyan-950/10 p-6 shadow-2xl sm:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.25em] text-cyan-300"><Route className="h-3.5 w-3.5" /> Dopamine → Roadmap</div><h2 className="mt-2 text-2xl font-black">Turn momentum into execution.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{avg < 55 || friction >= 4 ? "Your signals suggest protecting the next roadmap block from friction." : "Your momentum signals are healthy. Use the next roadmap block as your execution anchor."}</p></div><Link to="/roadmap" className="inline-flex shrink-0 items-center rounded-xl bg-cyan-300 px-5 py-3 text-sm font-black text-slate-950">Open roadmap <ArrowRight className="ml-2 h-4 w-4" /></Link></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Momentum avg" value={`${avg}/100`} /><Metric label="High-momentum days" value={String(high)} /><Metric label="Recent trend" value={`${trend >= 0 ? "+" : ""}${trend}`} /></div></section>
    <section className="rounded-[2rem] border border-amber-300/15 bg-amber-950/10 p-6 shadow-2xl sm:p-8"><div className="flex items-start gap-4"><div className="rounded-xl border border-amber-300/20 bg-amber-300/10 p-3"><ShieldCheck className="h-5 w-5 text-amber-200" /></div><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-amber-200">Intervention mode</p><h2 className="mt-2 text-2xl font-black">10-minute momentum reset.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">A real countdown: phone away → reset → move → open your next task → work. No fake completion.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-5">{["Phone away · 2m","Reset · 1m","Move · 3m","Open task · 1m","Work · 3m"].map((s, i) => <div key={s} className={`rounded-xl border p-3 text-center text-xs font-bold ${done ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-200" : "border-white/7 bg-black/20 text-slate-400"}`}><span className="mr-1 text-amber-200">0{i+1}</span>{s}</div>)}</div><div className="mt-6 flex flex-wrap items-center gap-3"><div className="rounded-xl border border-white/10 bg-black/20 px-5 py-3 font-mono text-2xl font-black tracking-widest">{done ? "DONE" : `${minutes}:${secs}`}</div><button type="button" onClick={() => { setSeconds(0); setDone(false); setRunning(true); }} className="inline-flex items-center rounded-xl bg-amber-300 px-5 py-3 text-sm font-black text-slate-950"><Play className="mr-2 h-4 w-4" />{running ? "Restart" : done ? "Run again" : "Start reset"}</button>{running && <button type="button" onClick={() => setRunning(false)} className="rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-black">Pause</button>}</div></section>
    <section className="rounded-[2rem] border border-indigo-400/15 bg-indigo-950/10 p-6 shadow-2xl sm:p-8"><div className="flex items-center gap-3"><div className="rounded-xl border border-indigo-300/20 bg-indigo-300/10 p-3"><Trophy className="h-5 w-5 text-indigo-200" /></div><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-indigo-300">Personal records</p><h2 className="mt-1 text-2xl font-black">Your best execution signals.</h2></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Best momentum" value={`${best}/100`} /><Metric label="High days" value={String(high)} /><Metric label="Consistency" value={`${consistency}%`} /><Metric label="Accelerator / friction" value={`${accelerator} / ${friction}`} /></div></section>
    <section className="rounded-[2rem] border border-violet-400/15 bg-violet-950/10 p-6 shadow-2xl sm:p-8"><div className="flex items-center gap-3"><div className="rounded-xl border border-violet-300/20 bg-violet-300/10 p-3"><BrainCircuit className="h-5 w-5 text-violet-200" /></div><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-violet-300">Behavioral analytics</p><h2 className="mt-1 text-2xl font-black">What your data is saying.</h2></div></div><p className="mt-5 max-w-3xl text-sm leading-7 text-slate-300">{insight}</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Logged days" value={String(recorded.length)} /><Metric label="Accelerator days" value={String(accelerator)} /><Metric label="Friction days" value={String(friction)} /><Metric label="7d signal" value={trend >= 0 ? `+${trend}` : String(trend)} /></div><p className="mt-5 text-xs leading-5 text-slate-500">These are behavioral signals from OUTSTAND logs, not medical or psychological diagnoses.</p></section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/7 bg-black/20 p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>; }
