export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.17" }
  public: {
    Tables: {
      activity_events: { Row: { created_at: string; event_type: string; id: string; metadata: Json; source_id: string | null; user_id: string }; Insert: { created_at?: string; event_type: string; id?: string; metadata?: Json; source_id?: string | null; user_id: string }; Update: { created_at?: string; event_type?: string; id?: string; metadata?: Json; source_id?: string | null; user_id?: string }; Relationships: [] }
      activity_log: { Row: { created_at: string | null; description: string; id: string; type: string; user_id: string; xp_awarded: number | null }; Insert: { created_at?: string | null; description: string; id?: string; type: string; user_id: string; xp_awarded?: number | null }; Update: { created_at?: string | null; description?: string; id?: string; type?: string; user_id?: string; xp_awarded?: number | null }; Relationships: [] }
      ai_roadmap_progress: { Row: { assigned_date: string; completed_missions: number; completion_pct: number; id: string; roadmap_day: number; roadmap_id: string; total_missions: number; updated_at: string; user_id: string }; Insert: { assigned_date?: string; completed_missions?: number; completion_pct?: number; id?: string; roadmap_day: number; roadmap_id: string; total_missions?: number; updated_at?: string; user_id: string }; Update: { assigned_date?: string; completed_missions?: number; completion_pct?: number; id?: string; roadmap_day?: number; roadmap_id?: string; total_missions?: number; updated_at?: string; user_id?: string }; Relationships: [{ foreignKeyName: "ai_roadmap_progress_roadmap_id_fkey"; columns: ["roadmap_id"]; isOneToOne: false; referencedRelation: "ai_roadmaps"; referencedColumns: ["id"] }] }
      ai_roadmaps: { Row: { answers: Json; category: string; created_at: string; difficulty: string; duration_days: number; habits_snapshot: Json; id: string; is_active: boolean; plan: Json; summary: string; title: string; updated_at: string; user_id: string }; Insert: { answers?: Json; category: string; created_at?: string; difficulty: string; duration_days: number; habits_snapshot?: Json; id?: string; is_active?: boolean; plan?: Json; summary: string; title: string; updated_at?: string; user_id: string }; Update: { answers?: Json; category?: string; created_at?: string; difficulty?: string; duration_days?: number; habits_snapshot?: Json; id?: string; is_active?: boolean; plan?: Json; summary?: string; title?: string; updated_at?: string; user_id?: string }; Relationships: [] }
      analyzed_games: { Row: { analysis_summary: Json; chess_com_game_id: string; created_at: string; game_url: string | null; id: string; opponent_rating: number | null; opponent_username: string | null; pgn: string | null; played_at: string | null; result: string | null; time_control: string | null; updated_at: string; user_color: string | null; user_id: string; user_rating: number | null }; Insert: { analysis_summary?: Json; chess_com_game_id: string; created_at?: string; game_url?: string | null; id?: string; opponent_rating?: number | null; opponent_username?: string | null; pgn?: string | null; played_at?: string | null; result?: string | null; time_control?: string | null; updated_at?: string; user_color?: string | null; user_id: string; user_rating?: number | null }; Update: { analysis_summary?: Json; chess_com_game_id?: string; created_at?: string; game_url?: string | null; id?: string; opponent_rating?: number | null; opponent_username?: string | null; pgn?: string | null; played_at?: string | null; result?: string | null; time_control?: string | null; updated_at?: string; user_color?: string | null; user_id?: string; user_rating?: number | null }; Relationships: [] }
      brilliant_moves: { Row: { annotation_type: string; created_at: string; fen_position: string; game_id: string; id: string; move_san: string; move_uci: string | null; user_id: string }; Insert: { annotation_type?: string; created_at?: string; fen_position: string; game_id: string; id?: string; move_san: string; move_uci?: string | null; user_id: string }; Update: { annotation_type?: string; created_at?: string; fen_position?: string; game_id?: string; id?: string; move_san?: string; move_uci?: string | null; user_id?: string }; Relationships: [{ foreignKeyName: "brilliant_moves_game_id_fkey"; columns: ["game_id"]; isOneToOne: false; referencedRelation: "analyzed_games"; referencedColumns: ["id"] }] }
      chess_coach_move_results: { Row: { after_mate: number | null; after_score: number | null; before_mate: number | null; before_score: number | null; best_engine_move: string | null; classification: string; created_at: string; evaluation_drop: number | null; fen_after_move: string; fen_before_move: string; game_id: string | null; id: string; played_move: string; principal_variation: string[]; solved: boolean; user_id: string }; Insert: { after_mate?: number | null; after_score?: number | null; before_mate?: number | null; before_score?: number | null; best_engine_move?: string | null; classification: string; created_at?: string; evaluation_drop?: number | null; fen_after_move: string; fen_before_move: string; game_id?: string | null; id?: string; played_move: string; principal_variation?: string[]; solved?: boolean; user_id: string }; Update: { after_mate?: number | null; after_score?: number | null; before_mate?: number | null; before_score?: number | null; best_engine_move?: string | null; classification?: string; created_at?: string; evaluation_drop?: number | null; fen_after_move?: string; fen_before_move?: string; game_id?: string | null; id?: string; played_move?: string; principal_variation?: string[]; solved?: boolean; user_id?: string }; Relationships: [{ foreignKeyName: "chess_coach_move_results_game_id_fkey"; columns: ["game_id"]; isOneToOne: false; referencedRelation: "analyzed_games"; referencedColumns: ["id"] }] }
      chess_roadmap_profiles: { Row: { blitz_rating: number | null; bullet_rating: number | null; chess_com_avatar: string | null; chess_com_title: string | null; chess_com_username: string; created_at: string; generated_roadmap: Json | null; rapid_rating: number | null; ratings: Json; roadmap_generated_at: string | null; tactics_rating: number | null; updated_at: string; user_id: string }; Insert: { blitz_rating?: number | null; bullet_rating?: number | null; chess_com_avatar?: string | null; chess_com_title?: string | null; chess_com_username: string; created_at?: string; generated_roadmap?: Json | null; rapid_rating?: number | null; ratings?: Json; roadmap_generated_at?: string | null; tactics_rating?: number | null; updated_at?: string; user_id: string }; Update: { blitz_rating?: number | null; bullet_rating?: number | null; chess_com_avatar?: string | null; chess_com_title?: string | null; chess_com_username?: string; created_at?: string; generated_roadmap?: Json | null; rapid_rating?: number | null; ratings?: Json; roadmap_generated_at?: string | null; tactics_rating?: number | null; updated_at?: string; user_id?: string }; Relationships: [] }
      chat_conversations: { Row: { created_at: string; id: string; updated_at: string; user_id: string }; Insert: { created_at?: string; id?: string; updated_at?: string; user_id: string }; Update: { created_at?: string; id?: string; updated_at?: string; user_id?: string }; Relationships: [] }
      chat_messages: { Row: { content: string; conversation_id: string; created_at: string; id: string; role: string; user_id: string }; Insert: { content: string; conversation_id: string; created_at?: string; id?: string; role: string; user_id: string }; Update: { content?: string; conversation_id?: string; created_at?: string; id?: string; role?: string; user_id?: string }; Relationships: [{ foreignKeyName: "chat_messages_conversation_id_fkey"; columns: ["conversation_id"]; isOneToOne: false; referencedRelation: "chat_conversations"; referencedColumns: ["id"] }] }
      curated_resources: { Row: { created_at: string; educator_name: string; id: string; mind_map_url: string | null; quick_revision_text: string | null; topic_name: string; youtube_url: string | null }; Insert: { created_at?: string; educator_name: string; id?: string; mind_map_url?: string | null; quick_revision_text?: string | null; topic_name: string; youtube_url?: string | null }; Update: { created_at?: string; educator_name?: string; id?: string; mind_map_url?: string | null; quick_revision_text?: string | null; topic_name?: string; youtube_url?: string | null }; Relationships: [] }
      daily_logs: { Row: { created_at: string; id: string; log_date: string; negatives: Json; positives: Json; score: number; updated_at: string; user_id: string }; Insert: { created_at?: string; id?: string; log_date: string; negatives?: Json; positives?: Json; score?: number; updated_at?: string; user_id: string }; Update: { created_at?: string; id?: string; log_date?: string; negatives?: Json; positives?: Json; score?: number; updated_at?: string; user_id?: string }; Relationships: [] }
      daily_quests: { Row: { assigned_date: string | null; completed: boolean | null; completed_at: string | null; id: string; quest_id: string; roadmap_day: number | null; roadmap_id: string | null; source_key: string | null; user_id: string }; Insert: { assigned_date?: string | null; completed?: boolean | null; completed_at?: string | null; id?: string; quest_id: string; roadmap_day?: number | null; roadmap_id?: string | null; source_key?: string | null; user_id: string }; Update: { assigned_date?: string | null; completed?: boolean | null; completed_at?: string | null; id?: string; quest_id?: string; roadmap_day?: number | null; roadmap_id?: string | null; source_key?: string | null; user_id?: string }; Relationships: [{ foreignKeyName: "daily_quests_quest_id_fkey"; columns: ["quest_id"]; isOneToOne: false; referencedRelation: "quests"; referencedColumns: ["id"] }, { foreignKeyName: "daily_quests_roadmap_id_fkey"; columns: ["roadmap_id"]; isOneToOne: false; referencedRelation: "ai_roadmaps"; referencedColumns: ["id"] }] }
      direct_conversations: { Row: { created_at: string; id: string; updated_at: string; user_a: string; user_b: string }; Insert: { created_at?: string; id?: string; updated_at?: string; user_a: string; user_b: string }; Update: { created_at?: string; id?: string; updated_at?: string; user_a?: string; user_b?: string }; Relationships: [] }
      direct_messages: { Row: { content: string; conversation_id: string; created_at: string; deleted_at: string | null; deleted_by: string | null; id: string; image_url: string | null; read_at: string | null; sender_id: string; updated_at: string }; Insert: { content: string; conversation_id: string; created_at?: string; deleted_at?: string | null; deleted_by?: string | null; id?: string; image_url?: string | null; read_at?: string | null; sender_id: string; updated_at?: string }; Update: { content?: string; conversation_id?: string; created_at?: string; deleted_at?: string | null; deleted_by?: string | null; id?: string; image_url?: string | null; read_at?: string | null; sender_id?: string; updated_at?: string }; Relationships: [{ foreignKeyName: "direct_messages_conversation_id_fkey"; columns: ["conversation_id"]; isOneToOne: false; referencedRelation: "direct_conversations"; referencedColumns: ["id"] }] }
      dpp_completions: { Row: { chapter_id: string; completed_at: string; difficulty: string; id: string; subject: string; user_id: string; xp_awarded: number }; Insert: { chapter_id: string; completed_at?: string; difficulty: string; id?: string; subject: string; user_id: string; xp_awarded: number }; Update: { chapter_id?: string; completed_at?: string; difficulty?: string; id?: string; subject?: string; user_id?: string; xp_awarded?: number }; Relationships: [] }
      dpp_questions: { Row: { correct_answer: string; created_at: string | null; dpp_id: string | null; id: string; options: Json; question_text: string }; Insert: { correct_answer: string; created_at?: string | null; dpp_id?: string | null; id?: string; options: Json; question_text: string }; Update: { correct_answer?: string; created_at?: string | null; dpp_id?: string | null; id?: string; options?: Json; question_text?: string }; Relationships: [{ foreignKeyName: "dpp_questions_dpp_id_fkey"; columns: ["dpp_id"]; isOneToOne: false; referencedRelation: "dpps"; referencedColumns: ["id"] }] }
      dpps: { Row: { created_at: string; difficulty: string; estimatedTime: string; id: string; subject: string; topic: string; xp: number }; Insert: { created_at?: string; difficulty: string; estimatedTime: string; id?: string; subject: string; topic: string; xp: number }; Update: { created_at?: string; difficulty?: string; estimatedTime?: string; id?: string; subject?: string; topic?: string; xp?: number }; Relationships: [] }
      focus_sessions: { Row: { completed_at: string | null; created_at: string; duration_minutes: number; id: string; user_id: string }; Insert: { completed_at?: string | null; created_at?: string; duration_minutes?: number; id?: string; user_id?: string }; Update: { completed_at?: string | null; created_at?: string; duration_minutes?: number; id?: string; user_id?: string }; Relationships: [] }
      friend_requests: { Row: { created_at: string; id: string; receiver_id: string; sender_id: string; status: string; updated_at: string }; Insert: { created_at?: string; id?: string; receiver_id: string; sender_id: string; status?: string; updated_at?: string }; Update: { created_at?: string; id?: string; receiver_id?: string; sender_id?: string; status?: string; updated_at?: string }; Relationships: [] }
      friendships: { Row: { created_at: string; friend_id: string; id: string; user_id: string }; Insert: { created_at?: string; friend_id: string; id?: string; user_id: string }; Update: { created_at?: string; friend_id?: string; id?: string; user_id?: string }; Relationships: [] }
      nightly_reviews: { Row: { adaptation: Json; ai_feedback: string | null; ai_summary: string | null; blockers: Json; daily_log_id: string; generated_at: string; id: string; review_date: string; roadmap_id: string; strengths: Json; user_id: string }; Insert: { adaptation?: Json; ai_feedback?: string | null; ai_summary?: string | null; blockers?: Json; daily_log_id: string; generated_at?: string; id?: string; review_date: string; roadmap_id: string; strengths?: Json; user_id: string }; Update: { adaptation?: Json; ai_feedback?: string | null; ai_summary?: string | null; blockers?: Json; daily_log_id?: string; generated_at?: string; id?: string; review_date?: string; roadmap_id?: string; strengths?: Json; user_id?: string }; Relationships: [{ foreignKeyName: "nightly_reviews_daily_log_id_fkey"; columns: ["daily_log_id"]; isOneToOne: false; referencedRelation: "roadmap_daily_logs"; referencedColumns: ["id"] }, { foreignKeyName: "nightly_reviews_roadmap_id_fkey"; columns: ["roadmap_id"]; isOneToOne: false; referencedRelation: "roadmaps"; referencedColumns: ["id"] }] }
      notification_delivery_log: { Row: { category: string; dedupe_key: string; id: string; sent_at: string; user_id: string }; Insert: { category: string; dedupe_key: string; id?: string; sent_at?: string; user_id: string }; Update: { category?: string; dedupe_key?: string; id?: string; sent_at?: string; user_id?: string }; Relationships: [] }
      notification_events: { Row: { body: string; category: string; created_at: string; dedupe_key: string | null; delivered_at: string | null; id: string; title: string; url: string; user_id: string }; Insert: { body: string; category: string; created_at?: string; dedupe_key?: string | null; delivered_at?: string | null; id?: string; title: string; url?: string; user_id: string }; Update: { body?: string; category?: string; created_at?: string; dedupe_key?: string | null; delivered_at?: string | null; id?: string; title?: string; url?: string; user_id?: string }; Relationships: [] }
      notification_preferences: { Row: { coaching_enabled: boolean; goals_enabled: boolean; habits_enabled: boolean; max_daily: number; motivational_enabled: boolean; push_enabled: boolean; quiet_end: string; quiet_hours_enabled: boolean; quiet_start: string; timezone: string; updated_at: string; updates_enabled: boolean; user_id: string }; Insert: { coaching_enabled?: boolean; goals_enabled?: boolean; habits_enabled?: boolean; max_daily?: number; motivational_enabled?: boolean; push_enabled?: boolean; quiet_end?: string; quiet_hours_enabled?: boolean; quiet_start?: string; timezone?: string; updated_at?: string; updates_enabled?: boolean; user_id: string }; Update: { coaching_enabled?: boolean; goals_enabled?: boolean; habits_enabled?: boolean; max_daily?: number; motivational_enabled?: boolean; push_enabled?: boolean; quiet_end?: string; quiet_hours_enabled?: boolean; quiet_start?: string; timezone?: string; updated_at?: string; updates_enabled?: boolean; user_id?: string }; Relationships: [] }
      notifications: { Row: { created_at: string; id: string; is_read: boolean | null; message: string; title: string; type: string | null; user_id: string }; Insert: { created_at?: string; id?: string; is_read?: boolean | null; message: string; title: string; type?: string | null; user_id: string }; Update: { created_at?: string; id?: string; is_read?: boolean | null; message?: string; title?: string; type?: string | null; user_id?: string }; Relationships: [{ foreignKeyName: "notifications_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] }] }
      outstand_logs: { Row: { challenge_id: string; created_at: string; duration_minutes: number; id: string; title: string; user_id: string; xp_earned: number }; Insert: { challenge_id: string; created_at?: string; duration_minutes?: number; id?: string; title: string; user_id: string; xp_earned?: number }; Update: { challenge_id?: string; created_at?: string; duration_minutes?: number; id?: string; title?: string; user_id?: string; xp_earned?: number }; Relationships: [] }
      profiles: { Row: { avatar_url: string | null; best_streak: number; bio: string | null; created_at: string; current_level: number | null; current_streak: number; display_name: string | null; full_name: string | null; has_completed_onboarding: boolean | null; id: string; last_seen_at: string | null; last_streak_date: string | null; screen_time: number | null; total_xp: number | null; updated_at: string; username: string | null }; Insert: { avatar_url?: string | null; best_streak?: number; bio?: string | null; created_at?: string; current_level?: number | null; current_streak?: number; display_name?: string | null; full_name?: string | null; has_completed_onboarding?: boolean | null; id: string; last_seen_at?: string | null; last_streak_date?: string | null; screen_time?: number | null; total_xp?: number | null; updated_at?: string; username?: string | null }; Update: { avatar_url?: string | null; best_streak?: number; bio?: string | null; created_at?: string; current_level?: number | null; current_streak?: number; display_name?: string | null; full_name?: string | null; has_completed_onboarding?: boolean | null; id?: string; last_seen_at?: string | null; last_streak_date?: string | null; screen_time?: number | null; total_xp?: number | null; updated_at?: string; username?: string | null }; Relationships: [] }
      push_subscriptions: { Row: { auth_key: string; created_at: string; endpoint: string; id: string; p256dh_key: string; user_id: string }; Insert: { auth_key: string; created_at?: string; endpoint: string; id?: string; p256dh_key: string; user_id: string }; Update: { auth_key?: string; created_at?: string; endpoint?: string; id?: string; p256dh_key?: string; user_id?: string }; Relationships: [] }
      quests: { Row: { category: string; difficulty: string; id: string; is_active: boolean | null; title: string; xp_reward: number }; Insert: { category: string; difficulty: string; id?: string; is_active?: boolean | null; title: string; xp_reward: number }; Update: { category?: string; difficulty?: string; id?: string; is_active?: boolean | null; title?: string; xp_reward?: number }; Relationships: [] }
      roadmap_daily_logs: { Row: { completed_tasks: number; completion_percent: number; created_at: string; difficulty_rating: number | null; energy_level: number | null; id: string; log_date: string; planned_tasks: number; reflection: string | null; roadmap_id: string; updated_at: string; user_id: string }; Insert: { completed_tasks?: number; completion_percent?: number; created_at?: string; difficulty_rating?: number | null; energy_level?: number | null; id?: string; log_date: string; planned_tasks?: number; reflection?: string | null; roadmap_id: string; updated_at?: string; user_id: string }; Update: { completed_tasks?: number; completion_percent?: number; created_at?: string; difficulty_rating?: number | null; energy_level?: number | null; id?: string; log_date?: string; planned_tasks?: number; reflection?: string | null; roadmap_id?: string; updated_at?: string; user_id?: string }; Relationships: [{ foreignKeyName: "roadmap_daily_logs_roadmap_id_fkey"; columns: ["roadmap_id"]; isOneToOne: false; referencedRelation: "roadmaps"; referencedColumns: ["id"] }] }
      roadmap_milestones: { Row: { created_at: string; day_end: number; day_start: number; description: string | null; id: string; methodology_tags: string[]; milestone_order: number; outcome: string | null; roadmap_id: string; title: string; user_id: string }; Insert: { created_at?: string; day_end: number; day_start: number; description?: string | null; id?: string; methodology_tags?: string[]; milestone_order: number; outcome?: string | null; roadmap_id: string; title: string; user_id: string }; Update: { created_at?: string; day_end?: number; day_start?: number; description?: string | null; id?: string; methodology_tags?: string[]; milestone_order?: number; outcome?: string | null; roadmap_id?: string; title?: string; user_id?: string }; Relationships: [{ foreignKeyName: "roadmap_milestones_roadmap_id_fkey"; columns: ["roadmap_id"]; isOneToOne: false; referencedRelation: "roadmaps"; referencedColumns: ["id"] }] }
      roadmap_task_progress: { Row: { completed_at: string | null; id: string; notes: string | null; roadmap_id: string; status: string; task_id: string; updated_at: string; user_id: string }; Insert: { completed_at?: string | null; id?: string; notes?: string | null; roadmap_id: string; status?: string; task_id: string; updated_at?: string; user_id: string }; Update: { completed_at?: string | null; id?: string; notes?: string | null; roadmap_id?: string; status?: string; task_id?: string; updated_at?: string; user_id?: string }; Relationships: [{ foreignKeyName: "roadmap_task_progress_roadmap_id_fkey"; columns: ["roadmap_id"]; isOneToOne: false; referencedRelation: "roadmaps"; referencedColumns: ["id"] }, { foreignKeyName: "roadmap_task_progress_task_id_fkey"; columns: ["task_id"]; isOneToOne: false; referencedRelation: "roadmap_tasks"; referencedColumns: ["id"] }] }
      roadmap_tasks: { Row: { created_at: string; day_number: number; difficulty: string | null; end_time: string | null; estimated_minutes: number | null; guidance: Json; id: string; instructions: string; is_required: boolean; methodology_tags: string[]; milestone_id: string; resources: Json; roadmap_id: string; spaced_repetition_day: number | null; start_time: string | null; success_criteria: string | null; task_order: number; task_type: string; title: string; user_id: string }; Insert: { created_at?: string; day_number: number; difficulty?: string | null; end_time?: string | null; estimated_minutes?: number | null; guidance?: Json; id?: string; instructions: string; is_required?: boolean; methodology_tags?: string[]; milestone_id: string; resources?: Json; roadmap_id: string; spaced_repetition_day?: number | null; start_time?: string | null; success_criteria?: string | null; task_order: number; task_type?: string; title: string; user_id: string }; Update: { created_at?: string; day_number?: number; difficulty?: string | null; end_time?: string | null; estimated_minutes?: number | null; guidance?: Json; id?: string; instructions?: string; is_required?: boolean; methodology_tags?: string[]; milestone_id?: string; resources?: Json; roadmap_id?: string; spaced_repetition_day?: number | null; start_time?: string | null; success_criteria?: string | null; task_order?: number; task_type?: string; title?: string; user_id?: string }; Relationships: [{ foreignKeyName: "roadmap_tasks_milestone_id_fkey"; columns: ["milestone_id"]; isOneToOne: false; referencedRelation: "roadmap_milestones"; referencedColumns: ["id"] }, { foreignKeyName: "roadmap_tasks_roadmap_id_fkey"; columns: ["roadmap_id"]; isOneToOne: false; referencedRelation: "roadmaps"; referencedColumns: ["id"] }] }
      roadmaps: { Row: { category: string; created_at: string; duration_days: number; generation_metadata: Json; goal: string; id: string; questionnaire: Json; start_date: string; status: string; structured_content: Json; target_date: string | null; title: string; updated_at: string; user_id: string; version: number }; Insert: { category?: string; created_at?: string; duration_days: number; generation_metadata?: Json; goal: string; id?: string; questionnaire?: Json; start_date?: string; status?: string; structured_content?: Json; target_date?: string | null; title: string; updated_at?: string; user_id: string; version?: number }; Update: { category?: string; created_at?: string; duration_days?: number; generation_metadata?: Json; goal?: string; id?: string; questionnaire?: Json; start_date?: string; status?: string; structured_content?: Json; target_date?: string | null; title?: string; updated_at?: string; user_id?: string; version?: number }; Relationships: [] }
      user_chess_profiles: { Row: { avatar_url: string | null; cached_30d_stats: Json; chess_username: string; created_at: string; id: string; last_synced_at: string | null; updated_at: string }; Insert: { avatar_url?: string | null; cached_30d_stats?: Json; chess_username: string; created_at?: string; id: string; last_synced_at?: string | null; updated_at?: string }; Update: { avatar_url?: string | null; cached_30d_stats?: Json; chess_username?: string; created_at?: string; id?: string; last_synced_at?: string | null; updated_at?: string }; Relationships: [] }
      user_feedback: { Row: { created_at: string; id: string; message: string; user_id: string }; Insert: { created_at?: string; id?: string; message: string; user_id: string }; Update: { created_at?: string; id?: string; message?: string; user_id?: string }; Relationships: [] }
      user_mistakes: { Row: { best_engine_move: string; created_at: string; evaluation_drop: number; fen_after_move: string; fen_before_move: string; game_id: string; id: string; is_solved: boolean; played_move: string; user_id: string }; Insert: { best_engine_move: string; created_at?: string; evaluation_drop: number; fen_after_move: string; fen_before_move: string; game_id: string; id?: string; is_solved?: boolean; played_move: string; user_id: string }; Update: { best_engine_move?: string; created_at?: string; evaluation_drop?: number; fen_after_move?: string; fen_before_move?: string; game_id?: string; id?: string; is_solved?: boolean; played_move?: string; user_id?: string }; Relationships: [{ foreignKeyName: "user_mistakes_game_id_fkey"; columns: ["game_id"]; isOneToOne: false; referencedRelation: "analyzed_games"; referencedColumns: ["id"] }] }
      user_productivity_state: { Row: { habits: Json; outstand: Json; sessions: Json; updated_at: string; user_id: string }; Insert: { habits?: Json; outstand?: Json; sessions?: Json; updated_at?: string; user_id: string }; Update: { habits?: Json; outstand?: Json; sessions?: Json; updated_at?: string; user_id?: string }; Relationships: [] }
      user_stats: { Row: { current_level_xp: number | null; focus_minutes_today: number | null; last_active_date: string | null; level: number | null; streak_days: number | null; total_xp: number | null; updated_at: string | null; user_id: string }; Insert: { current_level_xp?: number | null; focus_minutes_today?: number | null; last_active_date?: string | null; level?: number | null; streak_days?: number | null; total_xp?: number | null; updated_at?: string | null; user_id: string }; Update: { current_level_xp?: number | null; focus_minutes_today?: number | null; last_active_date?: string | null; level?: number | null; streak_days?: number | null; total_xp?: number | null; updated_at?: string | null; user_id?: string }; Relationships: [] }
      xp_transactions: { Row: { amount: number; created_at: string; description: string | null; id: string; metadata: Json; reference_id: string; source: string; user_id: string }; Insert: { amount: number; created_at?: string; description?: string | null; id?: string; metadata?: Json; reference_id: string; source: string; user_id: string }; Update: { amount?: number; created_at?: string; description?: string | null; id?: string; metadata?: Json; reference_id?: string; source?: string; user_id?: string }; Relationships: [] }
    }
    Views: { [_ in never]: never }
    Functions: {
      accept_friend_request: { Args: { request_id: string }; Returns: boolean }
      award_user_xp: { Args: { p_amount: number; p_user_id: string }; Returns: undefined }
      award_xp: { Args: { p_amount: number; p_description?: string; p_metadata?: Json; p_reference_id?: string; p_source: string }; Returns: { current_level: number; granted: number; total_xp: number }[] }
      complete_daily_quest: { Args: { p_daily_quest_id: string }; Returns: boolean }
      complete_dpp_and_award_xp: { Args: { p_chapter_id: string; p_difficulty: string; p_subject: string; p_user_id: string; p_xp_amount: number }; Returns: boolean }
      complete_focus_session: { Args: { p_duration_minutes: number; p_session_id: string }; Returns: number }
      get_friend_count: { Args: { target_user: string }; Returns: number }
      get_friend_state: { Args: { target_user: string }; Returns: string }
      get_or_create_direct_conversation: { Args: { target_user: string }; Returns: string }
      get_productivity_analytics: { Args: { p_days?: number }; Returns: { active_roadmap_tasks: number; focus_minutes: number; focus_sessions: number; period_days: number; xp_earned: number }[] }
      invoke_outstand_notification_engine: { Args: never; Returns: undefined }
      log_focus_session: { Args: { p_duration_minutes: number }; Returns: boolean }
      record_daily_streak: { Args: { p_date?: string; p_user_id: string }; Returns: { best_streak: number; current_streak: number; last_streak_date: string }[] }
      refresh_ai_roadmap_progress: { Args: never; Returns: Json }
      relocate_roadmap_tasks: { Args: { p_roadmap_id: string; p_start_minute: number }; Returns: number }
      remove_friend: { Args: { target_user: string }; Returns: boolean }
      send_friend_request: { Args: { target_user: string }; Returns: string }
      sync_ai_roadmap_today_missions: { Args: never; Returns: number }
      upsert_user_productivity_state: { Args: { p_habits: Json; p_outstand: Json; p_sessions: Json }; Returns: undefined }
      xp_level_from_total: { Args: { p_xp: number }; Returns: number }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]
export type Tables<T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]), N extends T = T> = (DefaultSchema["Tables"] & DefaultSchema["Views"])[N] extends { Row: infer R } ? R : never
export type TablesInsert<T extends keyof DefaultSchema["Tables"], N extends T = T> = DefaultSchema["Tables"][N] extends { Insert: infer I } ? I : never
export type TablesUpdate<T extends keyof DefaultSchema["Tables"], N extends T = T> = DefaultSchema["Tables"][N] extends { Update: infer U } ? U : never
export type Enums<T extends keyof DefaultSchema["Enums"]> = DefaultSchema["Enums"][T]
export type CompositeTypes<T extends keyof DefaultSchema["CompositeTypes"]> = DefaultSchema["CompositeTypes"][T]
export const Constants = { public: { Enums: {} } } as const
