export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.17" }
  public: {
    Tables: {
      activity_events: { Row: { created_at: string; event_type: string; id: string; metadata: Json; source_id: string | null; user_id: string }; Insert: { created_at?: string; event_type: string; id?: string; metadata?: Json; source_id?: string | null; user_id: string }; Update: { created_at?: string; event_type?: string; id?: string; metadata?: Json; source_id?: string | null; user_id?: string }; Relationships: [] }
      activity_log: { Row: { created_at: string | null; description: string; id: string; type: string; user_id: string; xp_awarded: number | null }; Insert: { created_at?: string | null; description: string; id?: string; type: string; user_id: string; xp_awarded?: number | null }; Update: { created_at?: string | null; description?: string; id?: string; type?: string; user_id?: string; xp_awarded?: number | null }; Relationships: [] }
      ai_roadmap_progress: { Row: { assigned_date: string; completed_missions: number; completion_pct: number; id: string; roadmap_day: number; roadmap_id: string; total_missions: number; updated_at: string; user_id: string }; Insert: { assigned_date?: string; completed_missions?: number; completion_pct?: number; id?: string; roadmap_day: number; roadmap_id: string; total_missions?: number; updated_at?: string; user_id: string }; Update: { assigned_date?: string; completed_missions?: number; completion_pct?: number; id?: string; roadmap_day?: number; roadmap_id?: string; total_missions?: number; updated_at?: string; user_id?: string }; Relationships: [{ foreignKeyName: "ai_roadmap_progress_roadmap_id_fkey"; columns: ["roadmap_id"]; isOneToOne: false; referencedRelation: "ai_roadmaps"; referencedColumns: ["id"] }] }
      ai_roadmaps: { Row: { answers: Json; category: string; created_at: string; difficulty: string; duration_days: number; habits_snapshot: Json; id: string; is_active: boolean; plan: Json; summary: string; title: string; updated_at: string; user_id: string }; Insert: { answers?: Json; category: string; created_at?: string; difficulty: string; duration_days: number; habits_snapshot?: Json; id?: string; is_active?: boolean; plan?: Json; summary: string; title: string; updated_at?: string; user_id: string }; Update: { answers?: Json; category?: string; created_at?: string; difficulty?: string; duration_days?: number; habits_snapshot?: Json; id?: string; is_active?: boolean; plan?: Json; summary?: string; title?: string; updated_at?: string; user_id?: string }; Relationships: [] }
      analyzed_games: { Row: { analysis_summary: Json; chess_com_game_id: string; created_at: string; game_url: string | null; id: string; opponent_rating: number | null; opponent_username: string | null; pgn: string | null; played_at: string | null; result: string | null; time_control: string | null; updated_at: string; user_color: string | null; user_id: string; user_rating: number | null }; Insert: { analysis_summary?: Json; chess_com_game_id: string; created_at?: string; game_url?: string | null; id?: string; opponent_rating?: number | null; opponent_username?: string | null; pgn?: string | null; played_at?: string | null; result?: string | null; time_control?: string | null; updated_at?: string; user_color?: string | null; user_id: string; user_rating?: number | null }; Update: { analysis_summary?: Json; chess_com_game_id?: string; created_at?: string; game_url?: string | null; id?: string; opponent_rating?: number | null; opponent_username?: string | null; pgn?: string | null; played_at?: string | null; result?: string | null; time_control?: string | null; updated_at?: string; user_color?: string | null; user_id?: string; user_rating?: number | null }; Relationships: [] }
      chess_coach_move_results: { Row: { after_mate: number | null; after_score: number | null; before_mate: number | null; before_score: number | null; best_engine_move: string | null; classification: string; created_at: string; evaluation_drop: number | null; fen_after_move: string; fen_before_move: string; game_id: string | null; id: string; played_move: string; principal_variation: string[]; solved: boolean; user_id: string }; Insert: { after_mate?: number | null; after_score?: number | null; before_mate?: number | null; before_score?: number | null; best_engine_move?: string | null; classification: string; created_at?: string; evaluation_drop?: number | null; fen_after_move: string; fen_before_move: string; game_id?: string | null; id?: string; played_move: string; principal_variation?: string[]; solved?: boolean; user_id: string }; Update: { after_mate?: number | null; after_score?: number | null; before_mate?: number | null; before_score?: number | null; best_engine_move?: string | null; classification?: string; created_at?: string; evaluation_drop?: number | null; fen_after_move?: string; fen_before_move?: string; game_id?: string | null; id?: string; played_move?: string; principal_variation?: string[]; solved?: boolean; user_id?: string }; Relationships: [{ foreignKeyName: "chess_coach_move_results_game_id_fkey"; columns: ["game_id"]; isOneToOne: false; referencedRelation: "analyzed_games"; referencedColumns: ["id"] }] }
      chess_roadmap_profiles: { Row: { blitz_rating: number | null; bullet_rating: number | null; chess_com_avatar: string | null; chess_com_title: string | null; chess_com_username: string; created_at: string; generated_roadmap: Json | null; rapid_rating: number | null; ratings: Json; roadmap_generated_at: string | null; tactics_rating: number | null; updated_at: string; user_id: string }; Insert: { blitz_rating?: number | null; bullet_rating?: number | null; chess_com_avatar?: string | null; chess_com_title?: string | null; chess_com_username: string; created_at?: string; generated_roadmap?: Json | null; rapid_rating?: number | null; ratings?: Json; roadmap_generated_at?: string | null; tactics_rating?: number | null; updated_at?: string; user_id?: string }; Update: { blitz_rating?: number | null; bullet_rating?: number | null; chess_com_avatar?: string | null; chess_com_title?: string | null; chess_com_username?: string; created_at?: string; generated_roadmap?: Json | null; rapid_rating?: number | null; ratings?: Json; roadmap_generated_at?: string | null; tactics_rating?: number | null; updated_at?: string; user_id?: string }; Relationships: [] }
      chat_conversations: { Row: { created_at: string; id: string; updated_at: string; user_id: string }; Insert: { created_at?: string; id?: string; updated_at?: string; user_id?: string }; Update: { created_at?: string; id?: string; updated_at?: string; user_id?: string }; Relationships: [] }
      chat_messages: { Row: { content: string; conversation_id: string; created_at: string; id: string; role: string; user_id: string }; Insert: { content: string; conversation_id: string; created_at?: string; id?: string; role: string; user_id: string }; Update: { content?: string; conversation_id?: string; created_at?: string; id?: string; role?: string; user_id?: string }; Relationships: [{ foreignKeyName: "chat_messages_conversation_id_fkey"; columns: ["conversation_id"]; isOneToOne: false; referencedRelation: "chat_conversations"; referencedColumns: ["id"] }] }
      curated_resources: { Row: { created_at: string; educator_name: string; id: string; mind_map_url: string | null; quick_revision_text: string | null; topic_name: string; youtube_url: string | null }; Insert: { created_at?: string; educator_name: string; id?: string; mind_map_url?: string | null; quick_revision_text?: string | null; topic_name: string; id?: string; youtube_url?: string | null }; Update: { created_at?: string; educator_name?: string; id?: string; mind_map_url?: string | null; quick_revision_text?: string | null; topic_name?: string; youtube_url?: string | null }; Relationships: [] }
      daily_logs: { Row: { created_at: string; id: string; log_date: string; negatives: Json; positives: Json; score: number; updated_at: string; user_id: string }; Insert: { created_at?: string; id?: string; log_date: string; negatives?: Json; positives?: Json; score?: number; updated_at?: string; user_id: string }; Update: { created_at?: string; id?: string; log_date?: string; negatives?: Json; positives?: Json; score?: number; updated_at?: string; user_id?: string }; Relationships: [] }
      daily_quests: { Row: { assigned_date: string | null; completed: boolean | null; completed_at: string | null; id: string; quest_id: string; roadmap_day: number | null; roadmap_id: string | null; source_key: string | null; user_id: string }; Insert: { assigned_date?: string | null; completed?: boolean | null; completed_at?: string | null; id?: string; quest_id: string; roadmap_day?: number | null; roadmap_id?: string | null; source_key?: string | null; user_id: string }; Update: { assigned_date?: string | null; completed?: boolean | null; completed_at?: string | null; id?: string; quest_id?: string; roadmap_day?: number | null; roadmap_id?: string | null; source_key?: string | null; user_id?: string }; Relationships: [{ foreignKeyName: "daily_quests_quest_id_fkey"; columns: ["quest_id"]; isOneToOne: false; referencedRelation: "quests"; referencedColumns: ["id"] }] }
    },
    Views: {},
    Functions: {},
    Enums: {},
    CompositeTypes: {},
  }
}
