import { jsonSchema, tool, type ToolSet } from "ai";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createBasicRoadmap, getOwnedRoadmap, smartChangeRoadmap, deleteOwnedRoadmap, listOwnedRoadmaps } from "./roadmap-service.js";

type Db = SupabaseClient<any, "public", any>;
const today = () => new Date().toISOString().slice(0, 10);
const dayNumber = (startDate: string) => Math.max(1, Math.floor((Date.now() - new Date(startDate).getTime()) / 86400000) + 1);

async function resolveRoadmap(client: Db, userId: string, roadmapId?: string, title?: string) {
  if (roadmapId) return getOwnedRoadmap(client, userId, roadmapId);
  const roadmaps = await listOwnedRoadmaps(client, userId);
  if (title?.trim()) {
    const needle = title.trim().toLowerCase();
    const matches = roadmaps.filter((roadmap: any) => String(roadmap.title || "").toLowerCase() === needle || String(roadmap.title || "").toLowerCase().includes(needle));
    if (matches.length === 1) return matches[0];
    if (matches.length > 1) throw new Error(`Multiple roadmaps match “${title}”. Please specify the exact roadmap title.`);
    throw new Error(`No roadmap matched “${title}”.`);
  }
  if (roadmaps.length === 1) return roadmaps[0];
  if (roadmaps.length === 0) throw new Error("You do not have an active roadmap yet.");
  throw new Error("You have multiple active roadmaps. Specify which roadmap you want to change by title.");
}

export function createProductivityTools(client: Db, userId: string, accessToken: string): ToolSet {
  const tools = {} as ToolSet;
  tools.list_roadmaps = tool({ description: "List the user's active or paused canonical roadmaps. Use this before changing or deleting a roadmap when more than one may exist.", inputSchema: jsonSchema({ type: "object", properties: {}, additionalProperties: false }), execute: async () => ({ roadmaps: await listOwnedRoadmaps(client, userId) }) });
  tools.change_roadmap = tool({ description: "Apply a real AI-directed roadmap change. Use roadmapId when known; otherwise provide roadmapTitle or let the tool resolve the only active roadmap. Supports rename/goal changes and safe task/schedule restructuring.", inputSchema: jsonSchema<{ roadmapId?: string; roadmapTitle?: string; request: string }>({ type: "object", properties: { roadmapId: { type: "string" }, roadmapTitle: { type: "string" }, request: { type: "string", minLength: 5, maxLength: 500 } }, required: ["request"], additionalProperties: false }), execute: async ({ roadmapId, roadmapTitle, request }) => { const roadmap = await resolveRoadmap(client, userId, roadmapId, roadmapTitle); const result = await smartChangeRoadmap(client, userId, roadmap.id, request); const changed = "changed" in result ? result.changed : "updated" in result ? result.updated === true : false; const affectedTasks = "affectedTasks" in result ? result.affectedTasks : undefined; return { ...result, changed, roadmapId: roadmap.id, message: changed ? `Roadmap changed successfully.${typeof affectedTasks === "number" ? ` ${affectedTasks} task(s) updated.` : ""}` : "No roadmap changes were made." }; } });
  tools.delete_roadmap = tool({ description: "Permanently delete one of the user's roadmaps. Use only when the user explicitly asks. Provide roadmapId when known, otherwise roadmapTitle or use the only active roadmap.", inputSchema: jsonSchema<{ roadmapId?: string; roadmapTitle?: string }>({ type: "object", properties: { roadmapId: { type: "string" }, roadmapTitle: { type: "string" } }, additionalProperties: false }), execute: async ({ roadmapId, roadmapTitle }) => { const roadmap = await resolveRoadmap(client, userId, roadmapId, roadmapTitle); const result = await deleteOwnedRoadmap(client, userId, roadmap.id); return { ...result, deleted: true, message: `Roadmap “${result.title}” was deleted successfully.` }; } });
  tools.create_roadmap = tool({ description: "Create a real canonical roadmap. category and goal are required. If plan is supplied, it must contain milestones with day, title, outcome and actions; otherwise a basic roadmap is created safely. Respect the server-side maximum of 4 active roadmaps.", inputSchema: jsonSchema<{ category?: string; goal?: string; title?: string; durationDays?: number; answers?: Record<string, unknown>; plan?: { milestones?: Array<{ day?: number; title?: string; outcome?: string; actions?: string[] }> } }>({ type: "object", properties: { category: { type: "string", minLength: 2 }, goal: { type: "string", minLength: 5 }, title: { type: "string", maxLength: 120 }, durationDays: { type: "integer", minimum: 7, maximum: 180 }, answers: { type: "object", additionalProperties: true }, plan: { type: "object", properties: { milestones: { type: "array", items: { type: "object", properties: { day: { type: "integer", minimum: 1 }, title: { type: "string" }, outcome: { type: "string" }, actions: { type: "array", items: { type: "string" } } }, required: ["title", "actions"], additionalProperties: false } } }, required: ["milestones"], additionalProperties: false } }, additionalProperties: false }), execute: async ({ category, goal, title, durationDays, answers, plan }) => { const cleanCategory = (category || "custom").trim(); const cleanGoal = (goal || "").trim(); if (!cleanGoal) return { created: false, needsMoreInfo: true, questions: [{ id: "goal", question: "What result are you aiming for?", type: "multiline", required: true }], message: "More information is required before creating the roadmap." }; const duration = Math.max(7, Math.min(180, Number(durationDays) || Number((answers as any)?.durationDays) || 30)); if (plan?.milestones?.length) { const { data, error } = await client.rpc("create_canonical_roadmap_from_plan", { p_category: cleanCategory, p_title: (title || cleanGoal.slice(0, 60) || "My roadmap").trim().slice(0, 120), p_goal: cleanGoal, p_questionnaire: answers || {}, p_generation_metadata: { source: "assistant" }, p_duration_days: duration, p_start_date: typeof (answers as any)?.start_date === "string" ? (answers as any).start_date : today(), p_plan: plan }); if (error) throw error; if (!data) throw new Error("Roadmap creation did not return an id."); return { created: true, roadmapId: data, verified: true, message: "Roadmap created successfully." }; } const result = await createBasicRoadmap(client, userId, cleanCategory, { ...(answers || {}), goal: cleanGoal, title, durationDays: duration }); if (result.error) throw new Error(String(result.error)); if (result.needsMoreInfo) return { created: false, needsMoreInfo: true, questions: result.questions || [], message: "More information is required before creating the roadmap." }; return { created: true, roadmapId: result.roadmapId, roadmap: result.roadmap, verified: result.verified === true, message: "Roadmap created successfully." }; } });
  tools.get_today = tool({ description: "Read the user's current active roadmap and today's canonical roadmap tasks.", inputSchema: jsonSchema({ type: "object", properties: {}, additionalProperties: false }), execute: async () => { const roadmaps = await listOwnedRoadmaps(client, userId); if (!roadmaps.length) return { date: today(), roadmap: null, todayTasks: [] }; const roadmap = roadmaps[0]; const day = dayNumber(roadmap.start_date); const { data, error } = await client.from("roadmap_tasks").select("id,title,instructions,estimated_minutes,start_time,end_time,is_required,success_criteria,task_type,day_number,task_order").eq("roadmap_id", roadmap.id).eq("user_id", userId).eq("day_number", day).order("start_time").order("task_order"); if (error) throw error; return { date: today(), roadmap: { ...roadmap, currentDay: day }, todayTasks: data || [], availableRoadmaps: roadmaps.map((item: any) => ({ id: item.id, title: item.title, status: item.status })) }; } });
  return tools;
}
