import { jsonSchema, tool, type ToolSet } from "ai";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createBasicRoadmap, getOwnedRoadmap, smartChangeRoadmap, deleteOwnedRoadmap, listOwnedRoadmaps } from "./roadmap-service.js";

type Db = SupabaseClient<any, "public", any>;
type ProductivityState = { habits: any[]; sessions: any[]; outstand: any[] };
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };
const dayNumber = (startDate: string, durationDays?: number) => Math.min(Math.max(1, Math.floor((Date.now() - new Date(`${startDate}T00:00:00`).getTime()) / 86400000) + 1), Math.max(1, Number(durationDays) || 1));
const validTime = (value?: string | null) => value == null || /^([01]\d|2[0-3]):[0-5]\d$/.test(value);

async function resolveRoadmap(client: Db, userId: string, roadmapId?: string, title?: string) {
  if (roadmapId) return getOwnedRoadmap(client, userId, roadmapId);
  const roadmaps = await listOwnedRoadmaps(client, userId);
  if (title?.trim()) {
    const needle = title.trim().toLowerCase();
    const matches = roadmaps.filter((roadmap: any) => String(roadmap.title || "").toLowerCase() === needle || String(roadmap.title || "").toLowerCase().includes(needle));
    if (matches.length === 1) return matches[0];
    if (matches.length > 1) throw new Error(`Multiple roadmaps match “${title}”. Please specify the exact roadmap title.`);
    throw new Error(`No roadmap matched “${title}”.`);
  }
  if (roadmaps.length === 1) return roadmaps[0];
  if (roadmaps.length === 0) throw new Error("You do not have an active roadmap yet.");
  throw new Error("You have multiple active roadmaps. Specify which roadmap you want to change by title.");
}

async function readProductivityState(client: Db, userId: string): Promise<ProductivityState> {
  const { data, error } = await client.from("user_productivity_state").select("habits,sessions,outstand,updated_at").eq("user_id", userId).maybeSingle();
  if (error) throw error;
  return { habits: Array.isArray(data?.habits) ? data.habits : [], sessions: Array.isArray(data?.sessions) ? data.sessions : [], outstand: Array.isArray(data?.outstand) ? data.outstand : [] };
}
async function writeProductivityState(client: Db, state: ProductivityState) {
  const { data, error } = await client.rpc("upsert_user_productivity_state", { p_habits: state.habits, p_sessions: state.sessions, p_outstand: state.outstand });
  if (error) throw error;
  if (!data) throw new Error("Productivity state update could not be verified.");
  return data;
}
async function findHabit(client: Db, userId: string, id?: string, name?: string) {
  const state = await readProductivityState(client, userId);
  if (id) { const habit = state.habits.find((item: any) => item?.id === id); if (!habit) throw new Error("Habit not found."); return { state, habit }; }
  const needle = String(name || "").trim().toLocaleLowerCase();
  if (!needle) throw new Error("Specify a habit by id or name.");
  const matches = state.habits.filter((item: any) => String(item?.name || "").trim().toLocaleLowerCase() === needle);
  if (matches.length === 1) return { state, habit: matches[0] };
  if (matches.length > 1) throw new Error(`Multiple habits match “${name}”. Please specify the exact habit name.`);
  throw new Error(`No habit matched “${name}”.`);
}

export function createProductivityTools(client: Db, userId: string, _accessToken: string): ToolSet {
  const tools = {} as ToolSet;
  tools.list_roadmaps = tool({ description: "List the user's active or paused canonical roadmaps.", inputSchema: jsonSchema({ type: "object", properties: {}, additionalProperties: false }), execute: async () => ({ roadmaps: await listOwnedRoadmaps(client, userId), verified: true }) });
  tools.change_roadmap = tool({ description: "Apply a real AI-directed roadmap change. Use roadmapId when known; otherwise provide roadmapTitle. Supports rename/goal changes and safe task/schedule restructuring.", inputSchema: jsonSchema<{ roadmapId?: string; roadmapTitle?: string; request: string }>({ type: "object", properties: { roadmapId: { type: "string" }, roadmapTitle: { type: "string" }, request: { type: "string", minLength: 5, maxLength: 500 } }, required: ["request"], additionalProperties: false }), execute: async ({ roadmapId, roadmapTitle, request }) => { const roadmap = await resolveRoadmap(client, userId, roadmapId, roadmapTitle); const result = await smartChangeRoadmap(client, userId, roadmap.id, request); const changed = "changed" in result ? result.changed : "updated" in result ? result.updated === true : false; const affectedTasks = "affectedTasks" in result ? result.affectedTasks : undefined; return { ...result, changed, roadmapId: roadmap.id, message: changed ? `Roadmap changed successfully.${typeof affectedTasks === "number" ? ` ${affectedTasks} task(s) updated.` : ""}` : "No roadmap changes were made." }; } });
  tools.delete_roadmap = tool({ description: "Permanently delete one of the user's roadmaps. Use only when the user explicitly asks.", inputSchema: jsonSchema<{ roadmapId?: string; roadmapTitle?: string }>({ type: "object", properties: { roadmapId: { type: "string" }, roadmapTitle: { type: "string" } }, additionalProperties: false }), execute: async ({ roadmapId, roadmapTitle }) => { const roadmap = await resolveRoadmap(client, userId, roadmapId, roadmapTitle); const result = await deleteOwnedRoadmap(client, userId, roadmap.id); return { ...result, deleted: true, message: `Roadmap “${result.title}” was deleted successfully.` }; } });
  tools.create_roadmap = tool({ description: "Create a real canonical roadmap. Provide a goal and optionally a structured milestone plan. Respect the server-side maximum of 4 active roadmaps.", inputSchema: jsonSchema<{ category?: string; goal: string; title?: string; durationDays?: number; answers?: Record<string, unknown>; plan?: { milestones?: Array<{ day?: number; title?: string; outcome?: string; actions?: string[] }> } }>({ type: "object", properties: { category: { type: "string", minLength: 2 }, goal: { type: "string", minLength: 5 }, title: { type: "string", maxLength: 120 }, durationDays: { type: "integer", minimum: 7, maximum: 180 }, answers: { type: "object", additionalProperties: true }, plan: { type: "object", properties: { milestones: { type: "array", items: { type: "object", properties: { day: { type: "integer", minimum: 1 }, title: { type: "string", minLength: 2 }, outcome: { type: "string" }, actions: { type: "array", items: { type: "string", minLength: 1 } } }, required: ["title", "actions"], additionalProperties: false } } }, required: ["milestones"], additionalProperties: false } }, required: ["goal"], additionalProperties: false }), execute: async ({ category, goal, title, durationDays, answers, plan }) => { const cleanCategory = (category || "custom").trim() || "custom"; const cleanGoal = goal.trim(); const duration = Math.max(7, Math.min(180, Number(durationDays) || Number((answers as any)?.durationDays) || 30)); if (plan?.milestones?.length) { const { data, error } = await client.rpc("create_canonical_roadmap_from_plan", { p_category: cleanCategory, p_title: (title || cleanGoal.slice(0, 60) || "My roadmap").trim().slice(0, 120), p_goal: cleanGoal, p_questionnaire: answers || {}, p_generation_metadata: { source: "assistant" }, p_duration_days: duration, p_start_date: typeof (answers as any)?.start_date === "string" ? (answers as any).start_date : today(), p_plan: plan }); if (error) throw error; if (!data) throw new Error("Roadmap creation did not return an id."); return { created: true, roadmapId: data, verified: true, message: "Roadmap created successfully." }; } const result = await createBasicRoadmap(client, userId, cleanCategory, { ...(answers || {}), goal: cleanGoal, title, durationDays: duration }); if (result.error) throw new Error(String(result.error)); return { ...result, created: result.created === true, verified: result.verified === true, message: result.created ? "Roadmap created successfully." : "More information is required before creating the roadmap." }; } });
  tools.get_today = tool({ description: "Read today's canonical roadmap tasks. If several roadmaps exist, require a roadmapId or roadmapTitle instead of guessing.", inputSchema: jsonSchema<{ roadmapId?: string; roadmapTitle?: string }>({ type: "object", properties: { roadmapId: { type: "string" }, roadmapTitle: { type: "string" } }, additionalProperties: false }), execute: async ({ roadmapId, roadmapTitle }) => { const roadmaps = await listOwnedRoadmaps(client, userId); if (!roadmaps.length) return { date: today(), roadmap: null, todayTasks: [], availableRoadmaps: [] }; const roadmap = roadmapId || roadmapTitle ? await resolveRoadmap(client, userId, roadmapId, roadmapTitle) : roadmaps.length === 1 ? roadmaps[0] : null; if (!roadmap) return { date: today(), roadmap: null, todayTasks: [], availableRoadmaps: roadmaps.map((item: any) => ({ id: item.id, title: item.title, status: item.status })), needsRoadmapSelection: true }; const day = dayNumber(roadmap.start_date, roadmap.duration_days); const { data, error } = await client.from("roadmap_tasks").select("id,title,instructions,estimated_minutes,start_time,end_time,is_required,success_criteria,task_type,day_number,task_order").eq("roadmap_id", roadmap.id).eq("user_id", userId).eq("day_number", day).order("start_time").order("task_order"); if (error) throw error; return { date: today(), roadmap: { ...roadmap, currentDay: day }, todayTasks: data || [], availableRoadmaps: roadmaps.map((item: any) => ({ id: item.id, title: item.title, status: item.status })), verified: true }; } });
  tools.list_habits = tool({ description: "Read the user's synchronized habits and today's completion state.", inputSchema: jsonSchema({ type: "object", properties: {}, additionalProperties: false }), execute: async () => { const state = await readProductivityState(client, userId); const date = today(); return { date, habits: state.habits.map((habit: any) => ({ ...habit, completedToday: Array.isArray(habit.history) && habit.history.includes(date) })), verified: true }; } });
  tools.mark_habit = tool({ description: "Mark a user's habit complete or incomplete for a date. Only use when explicitly requested.", inputSchema: jsonSchema<{ habitId?: string; habitName?: string; completed: boolean; date?: string }>({ type: "object", properties: { habitId: { type: "string" }, habitName: { type: "string" }, completed: { type: "boolean" }, date: { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" } }, required: ["completed"], additionalProperties: false }), execute: async ({ habitId, habitName, completed, date }) => { const targetDate = date || today(); const { state, habit } = await findHabit(client, userId, habitId, habitName); const history = Array.isArray(habit.history) ? [...new Set(habit.history)] : []; const nextHistory = completed ? (history.includes(targetDate) ? history : [...history, targetDate]).sort() : history.filter((item: string) => item !== targetDate); const next = { ...habit, history: nextHistory }; await writeProductivityState(client, { ...state, habits: state.habits.map((item: any) => item.id === habit.id ? next : item) }); return { changed: true, habitId: habit.id, habitName: habit.name, date: targetDate, completed: Boolean(completed), verified: true, message: `${habit.name} marked ${completed ? "complete" : "incomplete"} for ${targetDate}.` }; } });
  tools.update_habit = tool({ description: "Update a user's habit name, icon, color, or notification time without changing its history.", inputSchema: jsonSchema<{ habitId?: string; habitName?: string; name?: string; emoji?: string; color?: string; notificationTime?: string | null }>({ type: "object", properties: { habitId: { type: "string" }, habitName: { type: "string" }, name: { type: "string", minLength: 1, maxLength: 120 }, emoji: { type: "string", maxLength: 16 }, color: { type: "string", minLength: 1, maxLength: 40 }, notificationTime: { type: ["string", "null"], pattern: "^([01]\\d|2[0-3]):[0-5]\\d$" } }, additionalProperties: false }), execute: async ({ habitId, habitName, name, emoji, color, notificationTime }) => { if (notificationTime !== undefined && !validTime(notificationTime)) throw new Error("Notification time must use HH:MM format."); const { state, habit } = await findHabit(client, userId, habitId, habitName); const nextName = name === undefined ? habit.name : name.trim(); if (!nextName) throw new Error("Habit name cannot be empty."); if (state.habits.some((item: any) => item.id !== habit.id && String(item.name || "").trim().toLocaleLowerCase() === nextName.toLocaleLowerCase())) throw new Error(`A habit named “${nextName}” already exists.`); const next = { ...habit, ...(emoji === undefined ? {} : { emoji }), ...(color === undefined ? {} : { color }), ...(notificationTime === undefined ? {} : { notificationTime }), name: nextName }; await writeProductivityState(client, { ...state, habits: state.habits.map((item: any) => item.id === habit.id ? next : item) }); return { changed: true, habitId: habit.id, habit: next, verified: true, message: `Habit “${nextName}” updated successfully.` }; } });
  tools.delete_habit = tool({ description: "Delete a habit only after the user explicitly asks to remove it.", inputSchema: jsonSchema<{ habitId?: string; habitName?: string }>({ type: "object", properties: { habitId: { type: "string" }, habitName: { type: "string" } }, additionalProperties: false }), execute: async ({ habitId, habitName }) => { const { state, habit } = await findHabit(client, userId, habitId, habitName); await writeProductivityState(client, { ...state, habits: state.habits.filter((item: any) => item.id !== habit.id) }); return { deleted: true, habitId: habit.id, habitName: habit.name, verified: true, message: `Habit “${habit.name}” was deleted.` }; } });
  tools.set_reminder = tool({ description: "Set or clear a daily reminder time for an existing habit using its notification time.", inputSchema: jsonSchema<{ habitId?: string; habitName?: string; time: string | null }>({ type: "object", properties: { habitId: { type: "string" }, habitName: { type: "string" }, time: { type: ["string", "null"], pattern: "^([01]\\d|2[0-3]):[0-5]\\d$" } }, required: ["time"], additionalProperties: false }), execute: async ({ habitId, habitName, time }) => { if (time !== null && !validTime(time)) throw new Error("Reminder time must use HH:MM format."); const { state, habit } = await findHabit(client, userId, habitId, habitName); const next = { ...habit, notificationTime: time }; await writeProductivityState(client, { ...state, habits: state.habits.map((item: any) => item.id === habit.id ? next : item) }); return { changed: true, habitId: habit.id, habitName: habit.name, time, verified: true, message: time ? `Reminder for “${habit.name}” set to ${time}.` : `Reminder for “${habit.name}” cleared.` }; } });
  tools.log_outstand = tool({ description: "Record a completed OUTSTAND item when the user explicitly asks to log it.", inputSchema: jsonSchema<{ title: string; xp?: number }>({ type: "object", properties: { title: { type: "string", minLength: 1, maxLength: 200 }, xp: { type: "number", minimum: 0, maximum: 10000 } }, required: ["title"], additionalProperties: false }), execute: async ({ title, xp }) => { const state = await readProductivityState(client, userId); const item = { id: crypto.randomUUID(), title: title.trim(), xp: Math.max(0, Math.round(Number(xp) || 0)), completedAt: new Date().toISOString() }; await writeProductivityState(client, { ...state, outstand: [item, ...state.outstand].slice(0, 200) }); return { created: true, item, verified: true, message: `Logged “${item.title}” successfully.` }; });
  return tools;
}
