import type { VercelRequest, VercelResponse } from "@vercel/node";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

type Db = SupabaseClient<any, "public", any, any>;
const env = (...names: string[]) => names.map((name) => process.env[name]).find((value) => typeof value === "string" && value.trim());
async function auth(req: VercelRequest) { const authorization = req.headers.authorization; if (!authorization?.startsWith("Bearer ")) return { error: 401, message: "Authentication required." }; const token = authorization.slice(7).trim(); const url = env("SUPABASE_URL", "VITE_SUPABASE_URL"); const key = env("SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY", "SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"); if (!url || !key || !token) return { error: 401, message: "Authentication is unavailable." }; const client = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false }, global: { headers: { Authorization: authorization } } }) as Db; const { data, error } = await client.auth.getUser(token); if (error || !data.user) return { error: 401, message: "Authentication failed." }; return { client, userId: data.user.id }; }
function json(res: VercelResponse, status: number, body: unknown) { res.status(status).setHeader("Cache-Control", "no-store").json(body); }
function validateSchedule(changes: any[]) { for (const change of changes) { if (!change?.taskId || !Number.isInteger(change.day) || change.day < 1 || typeof change.startTime !== "string" || typeof change.endTime !== "string") throw new Error("Invalid smart-change schedule returned by AI."); } }
async function callAI(prompt: string) { const key = env("OPENAI_API_KEY"); if (!key) throw new Error("AI service is not configured."); const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: env("OPENAI_MODEL") || "gpt-5", input: prompt, text: { format: { type: "json_object" } } }) }); if (!response.ok) throw new Error("AI service request failed."); const data = await response.json(); const text = data.output?.flatMap((item: any) => item.content || []).find((item: any) => item.type === "output_text")?.text; if (!text) throw new Error("AI returned no edit plan."); return JSON.parse(text); }
export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") return json(res, 405, { error: "Method not allowed." });
  const session = await auth(req); if ("error" in session) return json(res, session.error, { error: session.message }); const { client, userId } = session;
  try {
    const input = req.body && typeof req.body === "object" ? req.body : {}; const roadmapId = typeof input.roadmapId === "string" ? input.roadmapId : ""; const request = typeof input.request === "string" ? input.request.trim() : ""; if (!roadmapId || request.length < 3) return json(res, 400, { error: "Roadmap ID and a change request are required." });
    const { data: roadmap, error: roadmapError } = await client.from("roadmaps").select("id,title,category,duration_days").eq("id", roadmapId).eq("user_id", userId).single(); if (roadmapError || !roadmap) return json(res, 404, { error: "Roadmap not found." });
    const [{ data: tasks, error: taskError }, { data: progressRows, error: progressError }] = await Promise.all([client.from("roadmap_tasks").select("id,day_number,title,estimated_minutes,start_time,end_time,is_required,instructions,success_criteria").eq("roadmap_id", roadmapId).eq("user_id", userId).order("day_number").order("start_time").order("task_order"), client.from("roadmap_task_progress").select("task_id,status").eq("roadmap_id", roadmapId).eq("user_id", userId)]); if (taskError) throw taskError; if (progressError) throw progressError;
    const completed = new Set((progressRows || []).filter((row: any) => row.status === "completed").map((row: any) => row.task_id)); const editableTasks = (tasks || []).map((task: any) => ({ id: task.id, day: task.day_number, title: task.title, minutes: task.estimated_minutes, start: task.start_time, end: task.end_time, required: task.is_required, completed: completed.has(task.id) }));
    const prompt = `You are patching an existing roadmap. Do NOT generate a roadmap. Do NOT create tasks. Do NOT delete tasks. Do NOT change the roadmap title, goal, duration, dates, or milestones. Only move/retime/rename/rewrite EXISTING incomplete tasks when directly required by the request. Completed tasks are immutable. If no safe change is needed, return changed=false.\n\nRoadmap context: ${JSON.stringify({ title: roadmap.title, category: roadmap.category, durationDays: roadmap.duration_days })}\nExisting tasks: ${JSON.stringify(editableTasks)}\nUser request: ${request}\n\nReturn ONLY: {"changed":true|false,"message":"brief","taskChanges":[{"taskId":"existing id","day":1,"startTime":"HH:MM","endTime":"HH:MM","title":"only if needed","instructions":"only if needed","successCriteria":"only if needed","estimatedMinutes":30,"isRequired":true}]}\nRules: taskId MUST come from the supplied list; max 8 changes; omit unchanged fields; never return a new task; never return the full roadmap; keep the response concise.`;
    const result = await callAI(prompt); if (result?.changed === false) return json(res, 200, result); const scheduleChanges = Array.isArray(result?.taskChanges) ? result.taskChanges : []; validateSchedule(scheduleChanges);
    const updates: Array<{ taskId: string; patch: Record<string, unknown> }> = []; for (const change of scheduleChanges) { const original = editableTasks.find((task: any) => task.id === change.taskId); if (!original || original.completed) continue; const patch: Record<string, unknown> = { day_number: change.day, start_time: change.startTime, end_time: change.endTime, estimated_minutes: change.estimatedMinutes }; if (typeof change.title === "string" && change.title.trim()) patch.title = change.title.trim().slice(0, 200); if (typeof change.instructions === "string" && change.instructions.trim()) patch.instructions = change.instructions.trim().slice(0, 2000); if (typeof change.successCriteria === "string" && change.successCriteria.trim()) patch.success_criteria = change.successCriteria.trim().slice(0, 1000); if (typeof change.isRequired === "boolean") patch.is_required = change.isRequired; updates.push({ taskId: change.taskId, patch }); }
    for (const update of updates) { const { error } = await client.from("roadmap_tasks").update(update.patch).eq("id", update.taskId).eq("roadmap_id", roadmapId).eq("user_id", userId); if (error) throw error; }
    return json(res, 200, { changed: updates.length > 0, message: result?.message || (updates.length ? "Smart change applied to existing tasks." : "No safe changes were needed."), changesApplied: updates.length });
  } catch (error) { const status = Number((error as any)?.status) || 500; console.error("[roadmap-edit]", error); return json(res, status, { error: error instanceof Error ? error.message : "Could not apply smart change." }); }
}
