import type { VercelRequest, VercelResponse } from "@vercel/node";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

type DbClient = SupabaseClient<any, "public", any>;
type AuthResult = { client: DbClient; userId: string } | { error: { status: number; message: string } };
const env = (...names: string[]) => names.map((name) => process.env[name]).find((value) => typeof value === "string" && value.trim());
const json = (res: VercelResponse, status: number, data: unknown) => res.status(status).setHeader("Cache-Control", "no-store").json(data);
const bearer = (req: VercelRequest) => req.headers.authorization?.startsWith("Bearer ") ? req.headers.authorization.slice(7).trim() : "";

async function authenticate(req: VercelRequest): Promise<AuthResult> {
  const token = bearer(req); if (!token) return { error: { status: 401, message: "Authentication required." } };
  const url = env("SUPABASE_URL", "VITE_SUPABASE_URL"); const key = env("SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY");
  if (!url || !key) return { error: { status: 500, message: "Supabase server configuration is missing." } };
  const client = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false }, global: { headers: { Authorization: `Bearer ${token}` } } }) as DbClient;
  const { data, error } = await client.auth.getUser(token); if (error || !data.user) return { error: { status: 401, message: "Authentication failed." } };
  return { client, userId: data.user.id };
}
function extractJson(text: string) { const cleaned = text.replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/```$/i, "").trim(); try { return JSON.parse(cleaned); } catch { const a = cleaned.indexOf("{"); const b = cleaned.lastIndexOf("}"); if (a >= 0 && b > a) return JSON.parse(cleaned.slice(a, b + 1)); const c = cleaned.indexOf("["); const d = cleaned.lastIndexOf("]"); if (c >= 0 && d > c) return JSON.parse(cleaned.slice(c, d + 1)); throw new Error("The AI returned invalid structured data."); } }
const baseRules = `You are OUTSTAND Intelligence, an adaptive personal planning AI. Never invent user facts. Ask for missing information before planning. Plans must be realistic, specific and measurable. Use evidence-informed learning methods when relevant: active recall, retrieval practice, spaced repetition, deliberate practice, interleaving, chunking, worked examples, error correction, reflection, and progressive difficulty. Never schedule over school, work, sleep, meals, or fixed commitments. Return JSON only.`;
async function askGroq(prompt: string) { const key = env("GROQ_API_KEY"); if (!key) throw Object.assign(new Error("Groq API configuration is missing."), { status: 503, code: "GROQ_CONFIG_MISSING" }); const r = await fetch("https://api.groq.com/openai/v1/chat/completions", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: "llama-3.1-8b-instant", temperature: 0.2, max_tokens: 7000, response_format: { type: "json_object" }, messages: [{ role: "system", content: baseRules }, { role: "user", content: prompt }] }) }); const raw = await r.text(); if (!r.ok) throw Object.assign(new Error(`Groq request failed (${r.status}).`), { status: r.status, code: r.status === 429 ? "AI_QUOTA_EXCEEDED" : "GROQ_REQUEST_FAILED" }); const parsed = JSON.parse(raw); const content = parsed?.choices?.[0]?.message?.content; if (typeof content !== "string" || !content.trim()) throw new Error("Groq returned an empty response."); return extractJson(content); }
async function askGemini(prompt: string) { const key = env("GEMINI_API_KEY", "GOOGLE_GENERATIVE_AI_API_KEY", "GOOGLE_API_KEY"); if (!key) throw Object.assign(new Error("Gemini API configuration is missing."), { status: 503, code: "GEMINI_CONFIG_MISSING" }); const r = await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent", { method: "POST", headers: { "Content-Type": "application/json", "x-goog-api-key": key }, body: JSON.stringify({ contents: [{ role: "user", parts: [{ text: `${baseRules}\n\n${prompt}` }] }], generationConfig: { responseMimeType: "application/json" } }) }); const raw = await r.text(); if (!r.ok) throw Object.assign(new Error(`Gemini request failed (${r.status}).`), { status: r.status, code: r.status === 429 ? "AI_QUOTA_EXCEEDED" : "GEMINI_REQUEST_FAILED" }); const parsed = JSON.parse(raw); const content = parsed?.candidates?.[0]?.content?.parts?.map((part: any) => part?.text || "").join(""); if (typeof content !== "string" || !content.trim()) throw new Error("Gemini returned an empty response."); return extractJson(content); }
async function ask(prompt: string) { try { return await askGroq(prompt); } catch (error: any) { if ((error?.status === 429 || error?.code === "GROQ_REQUEST_FAILED") && env("GEMINI_API_KEY", "GOOGLE_GENERATIVE_AI_API_KEY", "GOOGLE_API_KEY")) return askGemini(prompt); throw error; } }
async function requestBody(req: VercelRequest) { if (req.body && typeof req.body === "object") return req.body as any; if (typeof req.body === "string") return JSON.parse(req.body); return {}; }
function validateTime(value: unknown) { return typeof value === "string" && /^([01]\d|2[0-3]):[0-5]\d$/.test(value); }
function validatePlan(plan: any) { if (!plan || typeof plan !== "object" || typeof plan.title !== "string" || !Number.isInteger(plan.durationDays) || !Array.isArray(plan.milestones) || plan.milestones.length === 0 || !Array.isArray(plan.dailySchedule) || !plan.dailySchedule.length) throw new Error("The AI returned an invalid roadmap structure."); for (const block of plan.dailySchedule) { if (!Number.isInteger(block.day) || block.day < 1 || typeof block.title !== "string" || !validateTime(block.startTime) || !validateTime(block.endTime) || typeof block.instructions !== "string" || !Number.isInteger(block.estimatedMinutes)) throw new Error("The AI returned an invalid timetable block."); if (block.estimatedMinutes < 15 || block.estimatedMinutes > 120) throw new Error("The AI returned an unrealistic timetable duration."); } for (const milestone of plan.milestones) if (!Number.isInteger(milestone.day) || typeof milestone.title !== "string" || !Array.isArray(milestone.actions)) throw new Error("The AI returned an invalid milestone."); return plan; }
type CuratedResource = { id: string; topic_name: string; educator_name: string; youtube_url: string; mind_map_url: string; quick_revision_text: string; created_at: string };
type LearningMilestone = { milestone_title: string; video_url: string; mind_map_url: string; revision_notes: string; quiz: Array<{ question: string; options: string[]; correct_answer: string }> };
function resourceSearchTerms(category: string, answers: Record<string, unknown>) { const raw = [category, answers.goal, answers.target, answers.subject, answers.topic, answers.topics, answers.exam, answers.currentLevel].flatMap((value) => Array.isArray(value) ? value : [value]).filter((value) => typeof value === "string" && value.trim()).join(" "); return [...new Set(raw.toLowerCase().split(/[^a-z0-9]+/).filter((word) => word.length >= 3 && !["the", "and", "for", "with", "from", "this", "that", "study", "learn"].includes(word)))].slice(0, 10); }
async function retrieveCuratedResources(client: DbClient, category: string, answers: Record<string, unknown>) { const terms = resourceSearchTerms(category, answers); const topicFilters = terms.map((term) => `topic_name.ilike.*${term.replace(/[%_,]/g, "")}*`); const query = client.from("curated_resources").select("id,topic_name,educator_name,youtube_url,mind_map_url,quick_revision_text,created_at").limit(40); const { data, error } = topicFilters.length ? await query.or(topicFilters.join(",")) : await query; if (error) throw Object.assign(new Error("Could not retrieve curated learning resources."), { status: 500, code: "CURATED_RESOURCE_QUERY_FAILED" }); const rows = (data || []) as CuratedResource[]; const haystack = `${category} ${JSON.stringify(answers)}`.toLowerCase(); return rows.sort((a, b) => { const score = (resource: CuratedResource) => resource.topic_name.toLowerCase().split(/[^a-z0-9]+/).filter((word) => word.length >= 3).reduce((total, word) => total + (haystack.includes(word) ? 1 : 0), 0); return score(b) - score(a); }).slice(0, 20); }
function validateLearningMilestones(value: unknown, resources: CuratedResource[]) { if (!Array.isArray(value) || value.length === 0) throw new Error("The AI returned no learning milestones."); const byTopic = new Map(resources.map((resource) => [resource.topic_name.trim().toLowerCase(), resource])); return value.map((raw, index) => { if (!raw || typeof raw !== "object") throw new Error(`Milestone ${index + 1} is invalid.`); const item = raw as any; const title = typeof item.milestone_title === "string" ? item.milestone_title.trim() : ""; if (!title) throw new Error(`Milestone ${index + 1} is missing milestone_title.`); const resource = byTopic.get(title.toLowerCase()); if (!resource) throw new Error(`Milestone ${index + 1} does not map to a curated topic.`); if (!Array.isArray(item.quiz) || item.quiz.length < 3 || item.quiz.length > 5) throw new Error(`Milestone ${index + 1} must contain 3-5 quiz questions.`); const quiz = item.quiz.map((question: any, quizIndex: number) => { if (!question || typeof question.question !== "string" || !Array.isArray(question.options) || question.options.length < 3 || question.options.length > 5 || typeof question.correct_answer !== "string") throw new Error(`Milestone ${index + 1}, quiz question ${quizIndex + 1} is invalid.`); const options = question.options.map(String); if (!options.includes(question.correct_answer)) throw new Error(`Milestone ${index + 1}, quiz question ${quizIndex + 1} has an invalid correct_answer.`); return { question: question.question.trim(), options, correct_answer: question.correct_answer.trim() }; }); return { milestone_title: resource.topic_name, video_url: resource.youtube_url || "", mind_map_url: resource.mind_map_url || "", revision_notes: resource.quick_revision_text || "", quiz }; }); }

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method === "OPTIONS") return res.status(204).end(); if (req.method !== "POST") return json(res, 405, { error: "Method not allowed." });
  const auth = await authenticate(req); if ("error" in auth) return json(res, auth.error.status, { error: auth.error.message });
  try {
    const input = await requestBody(req); const mode = ["questions", "plan", "adapt"].includes(input?.mode) ? input.mode : "questions"; const category = typeof input?.category === "string" ? input.category : "custom"; const answers = input?.answers && typeof input.answers === "object" ? input.answers : {};
    if (mode === "questions") {
      const answered = Object.entries(answers).map(([key, value]) => `${key}: ${String(value)}`).join("\n") || "No answers yet.";
      return json(res, 200, await ask(`Create the next 4 to 6 highest-value adaptive questions for a ${category} goal. Do not repeat answered information. The interview MUST collect: exact outcome and measurable target; current baseline; deadline; wake and sleep times; fixed commitments such as school/work; realistic daily study/work window; preferred session length; current skill level; constraints; and the user's normal weekday schedule. At least one question must capture exactly when focused work can happen so the final timetable can assign real clock times. Return exactly {"questions":[{"id":"string","question":"string","type":"text|number|choice|multiline","required":true,"options":["..."],"placeholder":"..."}].\n\nAnswered:\n${answered}`));
    }
    if (mode === "plan") {
      const durationDays = Math.max(1, Math.min(730, Number(answers.durationDays) || 30));
      const resources = await retrieveCuratedResources(auth.client, category, answers);
      if (!resources.length) return json(res, 422, { error: "No curated learning resources match this roadmap yet.", code: "NO_CURATED_RESOURCES", needsCuratedContent: true });
      const resourceContext = resources.map((resource) => ({ id: resource.id, topic_name: resource.topic_name, educator_name: resource.educator_name, youtube_url: resource.youtube_url, mind_map_url: resource.mind_map_url, quick_revision_text: resource.quick_revision_text })).slice(0, 20);
      const raw: any = await ask(`Create a concise, goal-first roadmap for ${category}. Output one JSON object with milestones and dailySchedule. milestones: 4-8 coherent topics, no duplicates, each with milestone_title, video_url, mind_map_url, revision_notes, quiz (3-5 MCQs). dailySchedule: 1-6 blocks for a typical day using startTime/endTime in HH:MM. Build it around the user's actual fixed commitments and available focus window. Prefer 30-60 minute work blocks, add short breaks when useful, and never schedule over sleep, school, work, meals, or commitments. The daily schedule must tell the user exactly what to do and when, with day, title, instructions, taskType, methodologyTags, estimatedMinutes, successCriteria, resources. Keep tasks short, specific, and finishable. Do not return a giant checklist or long progression path. milestone_title must exactly equal a supplied curated topic_name. Do not invent URLs or resources.\n\nCATEGORY: ${category}\nUSER INTERVIEW: ${JSON.stringify(answers)}\nCURATED RESOURCES: ${JSON.stringify(resourceContext)}`);
      const milestones = validateLearningMilestones(raw?.milestones, resources);
      const schedule = Array.isArray(raw?.dailySchedule) ? raw.dailySchedule.slice(0, 6).map((block: any) => ({ ...block, estimatedMinutes: Number(block.estimatedMinutes) || 45 })) : [];
      if (!schedule.length) throw new Error("The AI returned no daily timetable.");
      const plan = { title: `${category || "Goal"} Roadmap`, summary: `A concise ${category} plan with a personalized daily timetable.`, durationDays, difficulty: "adaptive", assumptions: [], milestones: milestones.map((milestone, index) => ({ day: Math.min(durationDays, index + 1), title: milestone.milestone_title, outcome: "Complete the topic checkpoint.", actions: [{ title: `Study ${milestone.milestone_title}`, instructions: "Study the curated lesson and complete the checkpoint quiz.", estimatedMinutes: 45, taskType: "practice", methodologyTags: ["retrieval_practice"], resources: milestone.video_url ? [{ title: "Curated lesson", url: milestone.video_url, note: "Curated by OUTSTAND." }] : [], spacedRepetitionDay: null, successCriteria: "Pass the checkpoint quiz." }] })), dailySchedule: schedule, adaptationRule: "Use quiz performance and completed tasks to adjust future work." };
      validatePlan(plan);
      return json(res, 200, { plan, milestones, retrieval: { count: resources.length, resourceIds: resources.map((resource) => resource.id) } });
    }
    return json(res, 200, { changed: false, reason: "The plan remains on track.", plan: null });
  } catch (error: any) { console.error("OUTSTAND roadmap request failed", error); return json(res, error?.status === 503 ? 503 : 500, { error: error?.message || "Roadmap service failed.", code: "ROADMAP_FAILED" }); }
}
